// =============================================================================
// PART 10: MULTI-TABLE 4-WAY ENTERPRISE PIPELINES (40 DISTINCT CASES: 13 Easy, 14 Medium, 13 Hard)
// Complex Multi-Table Chained Joins Across 4+ Normalized Tables in 10 Industries
// =============================================================================

module.exports = [
  // --- FINTECH ---
  {
    title: "End-to-End Card Fraud Dispute Pipeline (Customers -> Accounts -> Charges -> Disputes)",
    ind: "Fintech",
    diff: "Medium",
    table: "BankCustomers",
    scenario: "Tracking disputed credit card charges from the cardholder profile through their account, card swipe transaction, and resulting chargeback claim.",
    businessObjective: "Execute a 4-table join linking Customers, Accounts, CardTransactions, and ChargebackClaims to calculate total disputed volume per customer risk tier.",
    schemaSnippet: "`BankCustomers (customer_id VARCHAR(32) PRIMARY KEY, customer_name VARCHAR(100), risk_tier VARCHAR(16))` & `CustomerAccounts (account_id VARCHAR(32) PRIMARY KEY, customer_id VARCHAR(32))` & `CardTransactions (tx_id VARCHAR(32) PRIMARY KEY, account_id VARCHAR(32), amount_usd DECIMAL(10,2))` & `ChargebackClaims (dispute_id VARCHAR(32) PRIMARY KEY, tx_id VARCHAR(32), dispute_reason VARCHAR(32))`",
    targetQuery: `SELECT c.risk_tier,\n       COUNT(DISTINCT c.customer_id) AS impacted_customers,\n       COUNT(d.dispute_id) AS total_disputes_filed,\n       SUM(t.amount_usd) AS total_disputed_usd\nFROM BankCustomers c\nINNER JOIN CustomerAccounts a\n  ON c.customer_id = a.customer_id\nINNER JOIN CardTransactions t\n  ON a.account_id = t.account_id\nINNER JOIN ChargebackClaims d\n  ON t.tx_id = d.tx_id\nGROUP BY c.risk_tier\nORDER BY total_disputed_usd DESC;`,
    eli5Story: "Tracing stolen money all the way through the system: starting with the customer, finding their bank account, finding the fraudulent transaction, and pulling up the fraud investigation file.",
    commonMistakes: "Using COUNT(c.customer_id) without DISTINCT when customers have multiple disputed charges.",
    learningOutcomes: "Navigate 4-table normalized transactional chains and aggregate financial dispute exposure."
  },
  {
    title: "Multi-Asset Wealth Management NAV Mark-to-Market Pipeline",
    ind: "Fintech",
    diff: "Hard",
    table: "WealthManagers",
    scenario: "Computing net asset value (NAV) mark-to-market valuations by joining advisors to client portfolios, individual asset holdings, and real-time exchange pricing feeds.",
    businessObjective: "Join WealthManagers to ClientPortfolios, AssetHoldings, and ExchangePrices to compute aggregate portfolio valuations per wealth advisor.",
    schemaSnippet: "`WealthManagers (advisor_id VARCHAR(16) PRIMARY KEY, advisor_name VARCHAR(100))` & `ClientPortfolios (portfolio_id VARCHAR(32) PRIMARY KEY, advisor_id VARCHAR(16))` & `AssetHoldings (holding_id BIGINT PRIMARY KEY, portfolio_id VARCHAR(32), ticker VARCHAR(10), shares DECIMAL(12,4))` & `ExchangePrices (ticker VARCHAR(10) PRIMARY KEY, current_price_usd DECIMAL(10,2))`",
    targetQuery: `SELECT m.advisor_name,\n       COUNT(DISTINCT p.portfolio_id) AS total_client_portfolios,\n       ROUND(SUM(h.shares * e.current_price_usd), 2) AS total_aum_usd\nFROM WealthManagers m\nINNER JOIN ClientPortfolios p\n  ON m.advisor_id = p.advisor_id\nINNER JOIN AssetHoldings h\n  ON p.portfolio_id = h.portfolio_id\nINNER JOIN ExchangePrices e\n  ON h.ticker = e.ticker\nGROUP BY m.advisor_id, m.advisor_name\nHAVING SUM(h.shares * e.current_price_usd) >= 50000000.00\nORDER BY total_aum_usd DESC;`,
    eli5Story: "Multiplying how many Apple and Google shares every client owns by today's stock price to calculate the total $50M+ wealth managed by each financial advisor.",
    commonMistakes: "Joining ExchangePrices without index on ticker, resulting in full table scans across stock catalogs.",
    learningOutcomes: "Calculate portfolio mark-to-market AUM across 4 normalized financial tables."
  },
  {
    title: "Syndicated Loan Collateral Coverage Pipeline",
    ind: "Fintech",
    diff: "Hard",
    table: "CommercialBorrowersPipeline",
    scenario: "Verifying collateral coverage for multi-bank syndicated loan agreements by joining borrower records, credit facilities, drawdown loans, and pledged collateral assets.",
    businessObjective: "Join Borrowers to Facilities, Drawdowns, and Collateral to compute loan-to-value (LTV) ratios per borrower.",
    schemaSnippet: "`CommercialBorrowersPipeline (borrower_id VARCHAR(32) PRIMARY KEY, company_name VARCHAR(100))` & `SyndicatedFacilities (facility_id VARCHAR(32) PRIMARY KEY, borrower_id VARCHAR(32))` & `FacilityDrawdowns (draw_id VARCHAR(32) PRIMARY KEY, facility_id VARCHAR(32), drawn_usd DECIMAL(12,2))` & `PledgedCollateral (collateral_id VARCHAR(32) PRIMARY KEY, facility_id VARCHAR(32), appraised_value_usd DECIMAL(12,2))`",
    targetQuery: `SELECT b.company_name,\n       d.total_drawn_usd,\n       c.total_collateral_usd,\n       ROUND((d.total_drawn_usd / NULLIF(c.total_collateral_usd, 0)) * 100.0, 2) AS ltv_ratio_pct\nFROM CommercialBorrowersPipeline b\nINNER JOIN SyndicatedFacilities f\n  ON b.borrower_id = f.borrower_id\nLEFT JOIN (\n  SELECT facility_id, SUM(drawn_usd) AS total_drawn_usd\n  FROM FacilityDrawdowns\n  GROUP BY facility_id\n) d ON f.facility_id = d.facility_id\nLEFT JOIN (\n  SELECT facility_id, SUM(appraised_value_usd) AS total_collateral_usd\n  FROM PledgedCollateral\n  GROUP BY facility_id\n) c ON f.facility_id = c.facility_id\nORDER BY ltv_ratio_pct DESC;`,
    eli5Story: "Comparing how much money a corporation borrowed from a syndicate of banks against the market value of the real estate and factories they put up as collateral.",
    commonMistakes: "Directly joining drawdowns and collateral without pre-aggregating, causing an explosive cross product of loans multiplied by collateral items.",
    learningOutcomes: "Combine multi-table pipeline joins with dual pre-aggregated subqueries to prevent Cartesian traps."
  },
  {
    title: "Card Settlement Clearing Pipeline (Cardholders -> Cards -> Authorizations -> Merchants)",
    ind: "Fintech",
    diff: "Easy",
    table: "Cardholders",
    scenario: "Auditing consumer card transactions across merchant categories by joining cardholder profiles, physical cards, authorization swipes, and merchant directories.",
    businessObjective: "Join Cardholders to Cards, AuthSwipes, and Merchants to report cardholder spend per merchant category.",
    schemaSnippet: "`Cardholders (cardholder_id VARCHAR(32) PRIMARY KEY, full_name VARCHAR(100))` & `IssuedCards (card_token VARCHAR(32) PRIMARY KEY, cardholder_id VARCHAR(32))` & `AuthSwipes (swipe_id VARCHAR(32) PRIMARY KEY, card_token VARCHAR(32), merchant_id VARCHAR(32), amount_usd DECIMAL(10,2))` & `Merchants (merchant_id VARCHAR(32) PRIMARY KEY, merchant_name VARCHAR(64), category VARCHAR(32))`",
    targetQuery: `SELECT m.category AS merchant_category,\n       COUNT(s.swipe_id) AS total_swipes,\n       SUM(s.amount_usd) AS total_spend_usd\nFROM Cardholders ch\nINNER JOIN IssuedCards ic\n  ON ch.cardholder_id = ic.cardholder_id\nINNER JOIN AuthSwipes s\n  ON ic.card_token = s.card_token\nINNER JOIN Merchants m\n  ON s.merchant_id = m.merchant_id\nGROUP BY m.category\nORDER BY total_spend_usd DESC;`,
    eli5Story: "Tracing a credit card purchase from the human cardholder, through their plastic card token, through the card swipe record, to the store directory.",
    commonMistakes: "Skipping the intermediate IssuedCards token table in normalized tokenized card architectures.",
    learningOutcomes: "Execute 4-table normalized relational queries in compliance with PCI-DSS tokenization schemas."
  },

  // --- SAAS ---
  {
    title: "Full SaaS Customer Adoption Funnel (Orgs -> Workspaces -> Users -> ActivityLogs)",
    ind: "SaaS",
    diff: "Medium",
    table: "EnterpriseOrgs",
    scenario: "Measuring product engagement depth by traversing from parent enterprise organizations, to child team workspaces, to active users, to feature click events.",
    businessObjective: "Join EnterpriseOrgs to Workspaces, Users, and FeatureClicks to calculate total feature engagement per enterprise customer.",
    schemaSnippet: "`EnterpriseOrgs (org_id VARCHAR(32) PRIMARY KEY, org_name VARCHAR(100))` & `OrgWorkspaces (workspace_id VARCHAR(32) PRIMARY KEY, org_id VARCHAR(32))` & `WorkspaceUsers (user_id VARCHAR(32) PRIMARY KEY, workspace_id VARCHAR(32))` & `FeatureClicks (event_id BIGINT PRIMARY KEY, user_id VARCHAR(32), feature_key VARCHAR(32))`",
    targetQuery: `SELECT o.org_name,\n       COUNT(DISTINCT w.workspace_id) AS active_workspaces,\n       COUNT(DISTINCT u.user_id) AS active_users,\n       COUNT(f.event_id) AS total_feature_clicks\nFROM EnterpriseOrgs o\nINNER JOIN OrgWorkspaces w\n  ON o.org_id = w.org_id\nINNER JOIN WorkspaceUsers u\n  ON w.workspace_id = u.workspace_id\nINNER JOIN FeatureClicks f\n  ON u.user_id = f.user_id\nGROUP BY o.org_id, o.org_name\nORDER BY total_feature_clicks DESC;`,
    eli5Story: "Counting how many clicks employees at Microsoft or Amazon made inside our software: linking the company, to their department team, to the individual employee, to their click logs.",
    commonMistakes: "Using COUNT(w.workspace_id) without DISTINCT, which counts clicks instead of unique workspaces.",
    learningOutcomes: "Perform multi-level product analytics rollups across 4-tier SaaS account hierarchies."
  },
  {
    title: "SaaS Dunning and Failed Payment Recovery Pipeline (Tenants -> Subscriptions -> Invoices -> Payments)",
    ind: "SaaS",
    diff: "Hard",
    table: "SaaSTenants",
    scenario: "Managing automated dunning workflows by identifying enterprise tenants whose recent subscription invoices failed payment retries.",
    businessObjective: "Join Tenants to Subscriptions, Invoices, and PaymentAttempts to isolate accounts with multiple consecutive failed payment attempts.",
    schemaSnippet: "`SaaSTenants (tenant_id VARCHAR(32) PRIMARY KEY, company_name VARCHAR(100))` & `TenantSubscriptions (sub_id VARCHAR(32) PRIMARY KEY, tenant_id VARCHAR(32))` & `SubscriptionInvoices (invoice_id VARCHAR(32) PRIMARY KEY, sub_id VARCHAR(32), amount_due_usd DECIMAL(10,2))` & `PaymentAttempts (attempt_id VARCHAR(32) PRIMARY KEY, invoice_id VARCHAR(32), status VARCHAR(16))`",
    targetQuery: `SELECT t.tenant_id, t.company_name,\n       inv.invoice_id, inv.amount_due_usd,\n       COUNT(p.attempt_id) AS failed_payment_attempts\nFROM SaaSTenants t\nINNER JOIN TenantSubscriptions s\n  ON t.tenant_id = s.tenant_id\nINNER JOIN SubscriptionInvoices inv\n  ON s.sub_id = inv.sub_id\nINNER JOIN PaymentAttempts p\n  ON inv.invoice_id = p.invoice_id\nWHERE p.status = 'DECLINED'\nGROUP BY t.tenant_id, t.company_name, inv.invoice_id, inv.amount_due_usd\nHAVING COUNT(p.attempt_id) >= 3\nORDER BY inv.amount_due_usd DESC;`,
    eli5Story: "Finding software customers whose credit card failed 3 times in a row so our accounting team can reach out before their service gets turned off.",
    commonMistakes: "Filtering on status = 'DECLINED' on a table that was LEFT JOINed without handling nulls.",
    learningOutcomes: "Identify involuntary churn risks across 4-stage SaaS billing dunning pipelines."
  },
  {
    title: "Kubernetes FinOps Infrastructure Cost Allocation Pipeline",
    ind: "SaaS",
    diff: "Hard",
    table: "CloudProviders",
    scenario: "Allocating cloud infrastructure bills to internal engineering teams by joining cloud provider billing accounts, Kubernetes clusters, namespaces, and pod runtime telemetry.",
    businessObjective: "Join CloudAccounts to Clusters, Namespaces, and PodMetrics to calculate monthly compute cost per engineering service namespace.",
    schemaSnippet: "`CloudAccounts (account_id VARCHAR(16) PRIMARY KEY, provider_name VARCHAR(16))` & `K8sClusters (cluster_id VARCHAR(32) PRIMARY KEY, account_id VARCHAR(16))` & `K8sNamespaces (namespace_id VARCHAR(32) PRIMARY KEY, cluster_id VARCHAR(32), owner_team VARCHAR(32))` & `PodMetrics (pod_id VARCHAR(32) PRIMARY KEY, namespace_id VARCHAR(32), cpu_cost_usd DECIMAL(8,2))`",
    targetQuery: `SELECT n.owner_team,\n       COUNT(DISTINCT c.cluster_id) AS clusters_utilized,\n       COUNT(p.pod_id) AS total_pods_deployed,\n       ROUND(SUM(p.cpu_cost_usd), 2) AS total_monthly_compute_usd\nFROM CloudAccounts a\nINNER JOIN K8sClusters c\n  ON a.account_id = c.account_id\nINNER JOIN K8sNamespaces n\n  ON c.cluster_id = n.cluster_id\nINNER JOIN PodMetrics p\n  ON n.namespace_id = p.namespace_id\nGROUP BY n.owner_team\nORDER BY total_monthly_compute_usd DESC;`,
    eli5Story: "Breaking down our $500,000 monthly Amazon AWS bill to show how much each engineering team (Search, Payments, Mobile) spent running their server pods.",
    commonMistakes: "Grouping by team name without including cluster count, masking cross-cluster resource sprawl.",
    learningOutcomes: "Model complex FinOps containerized cloud infrastructure cost allocation across 4 normalized tiers."
  },
  {
    title: "Complex Usage-Based Contract Billing Pipeline (Accounts -> Contracts -> AddOns -> MeterLogs)",
    ind: "SaaS",
    diff: "Easy",
    table: "EnterpriseBillingAccounts",
    scenario: "Generating monthly enterprise invoices by joining accounts to active contracts, licensed add-ons, and metered hourly consumption logs.",
    businessObjective: "Join Accounts to Contracts, AddOns, and UsageLogs to compute total billable consumption revenue.",
    schemaSnippet: "`EnterpriseBillingAccounts (acct_id VARCHAR(32) PRIMARY KEY, client_name VARCHAR(100))` & `MasterContracts (contract_id VARCHAR(32) PRIMARY KEY, acct_id VARCHAR(32))` & `ContractAddOns (addon_id VARCHAR(32) PRIMARY KEY, contract_id VARCHAR(32), feature_name VARCHAR(32))` & `HourlyMeterLogs (log_id BIGINT PRIMARY KEY, addon_id VARCHAR(32), units_consumed INT, unit_rate_usd DECIMAL(6,4))`",
    targetQuery: `SELECT a.client_name,\n       ao.feature_name,\n       SUM(m.units_consumed) AS total_units_consumed,\n       ROUND(SUM(m.units_consumed * m.unit_rate_usd), 2) AS total_feature_charge_usd\nFROM EnterpriseBillingAccounts a\nINNER JOIN MasterContracts c\n  ON a.acct_id = c.acct_id\nINNER JOIN ContractAddOns ao\n  ON c.contract_id = ao.contract_id\nINNER JOIN HourlyMeterLogs m\n  ON ao.addon_id = m.addon_id\nGROUP BY a.client_name, ao.feature_name\nORDER BY total_feature_charge_usd DESC;`,
    eli5Story: "Calculating a customer's monthly cloud bill: linking their company account, to their contract terms, to their add-on features, to their hourly usage logs.",
    commonMistakes: "Omitting the feature_name in the GROUP BY clause when aggregating multiple contract features.",
    learningOutcomes: "Calculate multi-product consumption billing using 4-table relational pipelines."
  },

  // --- RETAIL ---
  {
    title: "End-to-End E-Commerce Order Fulfillment Pipeline (Customers -> Orders -> Items -> Products)",
    ind: "Retail",
    diff: "Easy",
    table: "EcomCustomers",
    scenario: "Reporting top customer purchasing preferences by joining customers to completed orders, order line items, and product catalog metadata.",
    businessObjective: "Execute a 4-table join linking Customers, Orders, LineItems, and Products to summarize total spend per product category.",
    schemaSnippet: "`EcomCustomers (customer_id VARCHAR(32) PRIMARY KEY, full_name VARCHAR(100))` & `EcomOrders (order_id VARCHAR(32) PRIMARY KEY, customer_id VARCHAR(32), order_date DATE)` & `OrderLines (line_id BIGINT PRIMARY KEY, order_id VARCHAR(32), sku VARCHAR(32), quantity INT)` & `CatalogProducts (sku VARCHAR(32) PRIMARY KEY, product_name VARCHAR(100), category VARCHAR(32), unit_price DECIMAL(8,2))`",
    targetQuery: `SELECT p.category,\n       COUNT(DISTINCT o.order_id) AS total_orders,\n       SUM(l.quantity) AS total_units_sold,\n       ROUND(SUM(l.quantity * p.unit_price), 2) AS gross_sales_usd\nFROM EcomCustomers c\nINNER JOIN EcomOrders o\n  ON c.customer_id = o.customer_id\nINNER JOIN OrderLines l\n  ON o.order_id = l.order_id\nINNER JOIN CatalogProducts p\n  ON l.sku = p.sku\nWHERE o.order_date >= '2026-01-01'\nGROUP BY p.category\nORDER BY gross_sales_usd DESC;`,
    eli5Story: "Connecting shoppers, to the orders they placed, to the specific shoes and shirts in their box, to the product catalog to calculate total category sales.",
    commonMistakes: "Using `SUM(p.unit_price)` instead of `SUM(l.quantity * p.unit_price)`, ignoring multi-unit purchases.",
    learningOutcomes: "Master the canonical 4-table e-commerce order-to-product transactional join pipeline."
  },
  {
    title: "Inbound Supply Chain Traceability Pipeline (Suppliers -> POs -> Cartons -> InventoryBins)",
    ind: "Retail",
    diff: "Medium",
    table: "WholesaleSuppliers",
    scenario: "Tracing defective warehouse inventory back to its origin supplier by joining suppliers, purchase orders, shipping cartons, and warehouse bin slots.",
    businessObjective: "Join Suppliers to PurchaseOrders, ReceivedCartons, and WarehouseBins to identify which warehouse aisles store products from a flagged supplier.",
    schemaSnippet: "`WholesaleSuppliers (supplier_id VARCHAR(32) PRIMARY KEY, supplier_name VARCHAR(100))` & `ProcurementOrders (po_id VARCHAR(32) PRIMARY KEY, supplier_id VARCHAR(32))` & `ReceivedCartons (carton_id VARCHAR(32) PRIMARY KEY, po_id VARCHAR(32), bin_id VARCHAR(16))` & `WarehouseStorageBins (bin_id VARCHAR(16) PRIMARY KEY, aisle_number INT, shelf_level INT)`",
    targetQuery: `SELECT s.supplier_name,\n       b.aisle_number,\n       COUNT(c.carton_id) AS cartons_stored_in_aisle\nFROM WholesaleSuppliers s\nINNER JOIN ProcurementOrders po\n  ON s.supplier_id = po.supplier_id\nINNER JOIN ReceivedCartons c\n  ON po.po_id = c.po_id\nINNER JOIN WarehouseStorageBins b\n  ON c.bin_id = b.bin_id\nWHERE s.supplier_name = 'Acme Global Manufacturing'\nGROUP BY s.supplier_name, b.aisle_number\nORDER BY cartons_stored_in_aisle DESC;`,
    eli5Story: "A supplier just called to say a batch of electronics is defective: this query tells warehouse staff exactly which warehouse aisles contain boxes from that supplier.",
    commonMistakes: "Filtering on supplier name before joining, instead of allowing index seeks on foreign keys.",
    learningOutcomes: "Trace physical supply chain inventory across 4 normalized logistics tables."
  },
  {
    title: "Retail POS Cashier Shift Audit Reconciliation Pipeline (Stores -> Registers -> Transactions -> Cashiers)",
    ind: "Retail",
    diff: "Hard",
    table: "RetailOutlets",
    scenario: "Auditing point-of-sale store operations by joining physical retail stores, electronic cash registers, sales transactions, and logged cashier operator profiles.",
    businessObjective: "Join Stores to Registers, PosSales, and Cashiers to compute cashier average transaction speed and revenue per register.",
    schemaSnippet: "`RetailOutlets (store_id VARCHAR(16) PRIMARY KEY, city VARCHAR(32))` & `CashRegisters (register_id VARCHAR(16) PRIMARY KEY, store_id VARCHAR(16))` & `PosSales (sale_id VARCHAR(32) PRIMARY KEY, register_id VARCHAR(16), cashier_id VARCHAR(16), total_usd DECIMAL(10,2))` & `CashierStaff (cashier_id VARCHAR(16) PRIMARY KEY, cashier_name VARCHAR(100))`",
    targetQuery: `SELECT s.city, r.register_id, c.cashier_name,\n       COUNT(tx.sale_id) AS transaction_count,\n       SUM(tx.total_usd) AS total_sales_volume_usd,\n       ROUND(AVG(tx.total_usd), 2) AS avg_basket_size_usd\nFROM RetailOutlets s\nINNER JOIN CashRegisters r\n  ON s.store_id = r.store_id\nINNER JOIN PosSales tx\n  ON r.register_id = tx.register_id\nINNER JOIN CashierStaff c\n  ON tx.cashier_id = c.cashier_id\nGROUP BY s.city, r.register_id, c.cashier_name\nHAVING COUNT(tx.sale_id) >= 20\nORDER BY total_sales_volume_usd DESC;`,
    eli5Story: "Reviewing store registers: showing which cashier rang up the most sales at Register #1 in the Chicago store today.",
    commonMistakes: "Omitting the cashier_name in the GROUP BY clause.",
    learningOutcomes: "Reconcile brick-and-mortar retail operational performance across 4 normalized entities."
  },
  {
    title: "Omnichannel Promotion Attribution Pipeline (Campaigns -> Coupons -> Orders -> Customers)",
    ind: "Retail",
    diff: "Medium",
    table: "MarketingCampaigns",
    scenario: "Evaluating digital marketing ROI by joining marketing campaigns, generated discount coupon codes, customer orders, and customer demographics.",
    businessObjective: "Join Campaigns to Coupons, Orders, and Customers to calculate customer acquisition costs across marketing campaigns.",
    schemaSnippet: "`MarketingCampaigns (campaign_id VARCHAR(32) PRIMARY KEY, campaign_name VARCHAR(64), ad_spend_usd DECIMAL(10,2))` & `IssuedCoupons (coupon_code VARCHAR(20) PRIMARY KEY, campaign_id VARCHAR(32))` & `CustomerOrdersPlaced (order_id VARCHAR(32) PRIMARY KEY, coupon_code VARCHAR(20), customer_id VARCHAR(32), order_amount DECIMAL(10,2))` & `ShopperProfiles (customer_id VARCHAR(32) PRIMARY KEY, acquisition_channel VARCHAR(32))`",
    targetQuery: `SELECT mc.campaign_name,\n       mc.ad_spend_usd,\n       COUNT(DISTINCT o.customer_id) AS unique_customers_acquired,\n       SUM(o.order_amount) AS total_revenue_generated_usd,\n       ROUND(SUM(o.order_amount) / NULLIF(mc.ad_spend_usd, 0), 2) AS campaign_roas\nFROM MarketingCampaigns mc\nINNER JOIN IssuedCoupons ic\n  ON mc.campaign_id = ic.campaign_id\nINNER JOIN CustomerOrdersPlaced o\n  ON ic.coupon_code = o.coupon_code\nINNER JOIN ShopperProfiles sp\n  ON o.customer_id = sp.customer_id\nGROUP BY mc.campaign_id, mc.campaign_name, mc.ad_spend_usd\nORDER BY campaign_roas DESC;`,
    eli5Story: "Tracking marketing success: linking the $10k Instagram ad campaign, to the discount coupon 'INSTA20', to the orders placed, to the new shoppers.",
    commonMistakes: "Using `COUNT(o.customer_id)` instead of `COUNT(DISTINCT o.customer_id)`, counting repeat orders as separate new customers.",
    learningOutcomes: "Calculate marketing campaign ROAS using 4-table promotional attribution pipelines."
  },

  // --- HEALTHCARE ---
  {
    title: "Clinical Care Continuity Pipeline (Patients -> Encounters -> Diagnoses -> Prescriptions)",
    ind: "Healthcare",
    diff: "Hard",
    table: "ClinicalPatients",
    scenario: "Analyzing treatment protocols for chronic illnesses by joining patient demographics, hospital clinical visits, ICD-10 diagnoses, and dispensed prescriptions.",
    businessObjective: "Join Patients to Encounters, Diagnoses, and Prescriptions to evaluate drug treatment patterns for type-2 diabetes.",
    schemaSnippet: "`ClinicalPatients (patient_id VARCHAR(32) PRIMARY KEY, birth_year INT)` & `HospitalVisits (encounter_id VARCHAR(32) PRIMARY KEY, patient_id VARCHAR(32), visit_date DATE)` & `VisitDiagnoses (diagnosis_id BIGINT PRIMARY KEY, encounter_id VARCHAR(32), icd_code VARCHAR(10))` & `PrescriptionsDispensed (rx_id VARCHAR(32) PRIMARY KEY, encounter_id VARCHAR(32), drug_name VARCHAR(64))`",
    targetQuery: `SELECT d.icd_code, rx.drug_name,\n       COUNT(DISTINCT p.patient_id) AS distinct_patients_treated,\n       COUNT(rx.rx_id) AS total_prescriptions_written\nFROM ClinicalPatients p\nINNER JOIN HospitalVisits v\n  ON p.patient_id = v.patient_id\nINNER JOIN VisitDiagnoses d\n  ON v.encounter_id = d.encounter_id\nINNER JOIN PrescriptionsDispensed rx\n  ON v.encounter_id = rx.encounter_id\nWHERE d.icd_code LIKE 'E11%'\nGROUP BY d.icd_code, rx.drug_name\nORDER BY distinct_patients_treated DESC;`,
    eli5Story: "Checking what diabetes medications doctors prescribe to patients who visit the hospital: linking the patient, their visit, their disease diagnosis, and their pill prescriptions.",
    commonMistakes: "Joining prescriptions directly to diagnoses without going through the shared encounter_id, creating accidental Cartesian explosion.",
    learningOutcomes: "Analyze clinical treatment efficacy across 4 normalized electronic health record tables."
  },
  {
    title: "Hospital Bed Occupancy and Acuity Pipeline (Hospitals -> Wards -> Beds -> Admissions)",
    ind: "Healthcare",
    diff: "Medium",
    table: "HospitalFacilities",
    scenario: "Monitoring hospital capacity by traversing from hospital campuses, to clinical wards, to physical beds, to active patient admissions.",
    businessObjective: "Join Hospitals to Wards, Beds, and ActiveAdmissions to calculate bed occupancy percentages per hospital ward.",
    schemaSnippet: "`HospitalFacilities (hospital_id VARCHAR(16) PRIMARY KEY, hospital_name VARCHAR(64))` & `ClinicalWards (ward_id VARCHAR(16) PRIMARY KEY, hospital_id VARCHAR(16), ward_name VARCHAR(32))` & `WardBeds (bed_id VARCHAR(16) PRIMARY KEY, ward_id VARCHAR(16))` & `ActiveAdmissions (admission_id VARCHAR(32) PRIMARY KEY, bed_id VARCHAR(16), patient_acuity_score INT)`",
    targetQuery: `SELECT h.hospital_name, w.ward_name,\n       COUNT(b.bed_id) AS total_beds_in_ward,\n       COUNT(a.admission_id) AS occupied_beds,\n       ROUND((COUNT(a.admission_id) * 100.0) / COUNT(b.bed_id), 1) AS ward_occupancy_pct,\n       ROUND(AVG(a.patient_acuity_score), 1) AS avg_patient_acuity\nFROM HospitalFacilities h\nINNER JOIN ClinicalWards w\n  ON h.hospital_id = w.hospital_id\nINNER JOIN WardBeds b\n  ON w.ward_id = b.ward_id\nLEFT JOIN ActiveAdmissions a\n  ON b.bed_id = a.bed_id\nGROUP BY h.hospital_name, w.ward_name\nORDER BY ward_occupancy_pct DESC;`,
    eli5Story: "Checking how full the Intensive Care Unit and Surgery wards are at Memorial Hospital, and making sure empty beds are counted properly.",
    commonMistakes: "Using an INNER JOIN on ActiveAdmissions which drops all empty beds and causes occupancy to calculate as 100% everywhere.",
    learningOutcomes: "Combine multi-table inner joins with terminal outer joins to calculate capacity utilization."
  },
  {
    title: "Medical Billing Revenue Cycle Management Pipeline (Doctors -> Clinics -> Encounters -> Claims)",
    ind: "Healthcare",
    diff: "Easy",
    table: "PractitionerDirectory",
    scenario: "Tracking medical insurance reimbursement collections by joining physicians, outpatient clinics, patient clinical encounters, and submitted insurance claims.",
    businessObjective: "Join Doctors to Clinics, Encounters, and InsuranceClaims to report revenue collection rates per medical specialty.",
    schemaSnippet: "`PractitionerDirectory (doctor_npi VARCHAR(10) PRIMARY KEY, specialty VARCHAR(32))` & `OutpatientClinics (clinic_id VARCHAR(16) PRIMARY KEY, doctor_npi VARCHAR(10))` & `PatientEncounters (encounter_id VARCHAR(32) PRIMARY KEY, clinic_id VARCHAR(16))` & `SubmittedClaims (claim_id VARCHAR(32) PRIMARY KEY, encounter_id VARCHAR(32), billed_usd DECIMAL(10,2), paid_usd DECIMAL(10,2))`",
    targetQuery: `SELECT doc.specialty,\n       COUNT(c.claim_id) AS claims_filed,\n       SUM(c.billed_usd) AS total_billed_usd,\n       SUM(c.paid_usd) AS total_collected_usd,\n       ROUND((SUM(c.paid_usd) * 100.0) / NULLIF(SUM(c.billed_usd), 0), 1) AS collection_realization_pct\nFROM PractitionerDirectory doc\nINNER JOIN OutpatientClinics cl\n  ON doc.doctor_npi = cl.doctor_npi\nINNER JOIN PatientEncounters e\n  ON cl.clinic_id = e.clinic_id\nINNER JOIN SubmittedClaims c\n  ON e.encounter_id = c.encounter_id\nGROUP BY doc.specialty\nORDER BY total_collected_usd DESC;`,
    eli5Story: "Adding up how much money insurance companies paid vs what the doctors billed for cardiology and orthopedic clinic visits.",
    commonMistakes: "Dividing by zero when billed_usd is 0 without using NULLIF.",
    learningOutcomes: "Model healthcare revenue cycle management across 4 relational billing entities."
  },
  {
    title: "Pharma Clinical Trial Biomarker Monitoring Pipeline (Trials -> Arms -> Patients -> LabResults)",
    ind: "Healthcare",
    diff: "Hard",
    table: "PharmaTrials",
    scenario: "Evaluating drug efficacy across Phase-III oncology trials by joining trial protocols, randomized study arms, enrolled subjects, and blood lab biomarker readings.",
    businessObjective: "Join Trials to StudyArms, Subjects, and BiomarkerTests to compute average biomarker reduction across placebo vs active test arms.",
    schemaSnippet: "`PharmaTrials (trial_nct VARCHAR(16) PRIMARY KEY, drug_name VARCHAR(64))` & `StudyArms (arm_id VARCHAR(16) PRIMARY KEY, trial_nct VARCHAR(16), arm_type VARCHAR(16))` & `EnrolledSubjects (subject_id VARCHAR(32) PRIMARY KEY, arm_id VARCHAR(16))` & `BiomarkerTests (test_id BIGINT PRIMARY KEY, subject_id VARCHAR(32), biomarker_level DECIMAL(6,2))`",
    targetQuery: `SELECT t.drug_name, a.arm_type,\n       COUNT(DISTINCT s.subject_id) AS enrolled_patient_count,\n       ROUND(AVG(b.biomarker_level), 2) AS mean_biomarker_level\nFROM PharmaTrials t\nINNER JOIN StudyArms a\n  ON t.trial_nct = a.trial_nct\nINNER JOIN EnrolledSubjects s\n  ON a.arm_id = s.arm_id\nINNER JOIN BiomarkerTests b\n  ON s.subject_id = b.subject_id\nGROUP BY t.drug_name, a.arm_type\nORDER BY mean_biomarker_level ASC;`,
    eli5Story: "Comparing blood test results of cancer patients taking the new medicine vs patients taking the sugar pill (placebo) across a clinical study.",
    commonMistakes: "Using `COUNT(s.subject_id)` instead of `COUNT(DISTINCT s.subject_id)`, overcounting patients with multiple blood tests.",
    learningOutcomes: "Analyze clinical trial pharmacological efficacy using 4-table scientific schemas."
  },

  // --- LOGISTICS ---
  {
    title: "End-to-End Freight Booking Pipeline (Shippers -> Bookings -> Consignments -> Carriers)",
    ind: "Logistics",
    diff: "Easy",
    table: "CommercialShippers",
    scenario: "Tracking corporate freight logistics by joining manufacturing shippers, freight master bookings, individual cargo consignments, and transport carriers.",
    businessObjective: "Join Shippers to Bookings, Consignments, and Carriers to report freight volume by transport carrier.",
    schemaSnippet: "`CommercialShippers (shipper_id VARCHAR(32) PRIMARY KEY, company_name VARCHAR(100))` & `FreightBookings (booking_id VARCHAR(32) PRIMARY KEY, shipper_id VARCHAR(32), carrier_id VARCHAR(16))` & `CargoConsignments (cons_id VARCHAR(32) PRIMARY KEY, booking_id VARCHAR(32), weight_lbs INT)` & `FreightCarriersPipeline (carrier_id VARCHAR(16) PRIMARY KEY, carrier_name VARCHAR(64))`",
    targetQuery: `SELECT c.carrier_name,\n       COUNT(DISTINCT b.booking_id) AS total_master_bookings,\n       SUM(co.weight_lbs) AS total_freight_weight_lbs\nFROM CommercialShippers s\nINNER JOIN FreightBookings b\n  ON s.shipper_id = b.shipper_id\nINNER JOIN CargoConsignments co\n  ON b.booking_id = co.booking_id\nINNER JOIN FreightCarriersPipeline c\n  ON b.carrier_id = c.carrier_id\nGROUP BY c.carrier_name\nORDER BY total_freight_weight_lbs DESC;`,
    eli5Story: "Adding up how many pounds of cargo shippers moved with Maersk, J.B. Hunt, and FedEx: linking the shipper, the booking, the cargo boxes, and the trucking carrier.",
    commonMistakes: "Joining consignments directly to carriers when carriers are keyed to the master booking header.",
    learningOutcomes: "Navigate supply chain shipping manifests across 4 normalized logistics entities."
  },
  {
    title: "Maritime Container Vessel Customs Clearance Pipeline (Vessels -> Voyages -> Containers -> Customs)",
    ind: "Logistics",
    diff: "Medium",
    table: "OceanVessels",
    scenario: "Auditing port border security clearance by joining ocean container vessels, scheduled international voyages, sea containers, and customs inspection filings.",
    businessObjective: "Join Vessels to Voyages, Containers, and CustomsFilings to identify quarantined cargo holds per ocean voyage.",
    schemaSnippet: "`OceanVessels (imo_number VARCHAR(10) PRIMARY KEY, vessel_name VARCHAR(100))` & `VesselVoyages (voyage_id VARCHAR(32) PRIMARY KEY, imo_number VARCHAR(10), arrival_port VARCHAR(5))` & `OceanContainers (container_no VARCHAR(11) PRIMARY KEY, voyage_id VARCHAR(32))` & `CustomsFilings (filing_id VARCHAR(32) PRIMARY KEY, container_no VARCHAR(11), clearance_status VARCHAR(16))`",
    targetQuery: `SELECT v.vessel_name, vy.arrival_port,\n       COUNT(c.container_no) AS total_containers_carried,\n       SUM(CASE WHEN cf.clearance_status = 'CLEARED' THEN 1 ELSE 0 END) AS cleared_containers,\n       SUM(CASE WHEN cf.clearance_status = 'HELD_FOR_INSPECTION' THEN 1 ELSE 0 END) AS quarantined_containers\nFROM OceanVessels v\nINNER JOIN VesselVoyages vy\n  ON v.imo_number = vy.imo_number\nINNER JOIN OceanContainers c\n  ON vy.voyage_id = c.voyage_id\nLEFT JOIN CustomsFilings cf\n  ON c.container_no = cf.container_no\nGROUP BY v.vessel_name, vy.arrival_port\nORDER BY quarantined_containers DESC;`,
    eli5Story: "Checking 5,000 sea containers arriving on a container ship from Asia: finding which containers were cleared and which were flagged by Customs for drug/fruit inspections.",
    commonMistakes: "Using an INNER JOIN on CustomsFilings which drops containers whose customs paperwork hasn't been submitted yet.",
    learningOutcomes: "Model international ocean shipping customs compliance using multi-table joins."
  },
  {
    title: "Automated Warehouse AGV Routing Pipeline (Hubs -> Aisles -> Bins -> RobotTasks)",
    ind: "Logistics",
    diff: "Hard",
    table: "FulfillmentCenters",
    scenario: "Measuring robotic warehouse efficiency by joining distribution hubs, storage aisles, physical bin locations, and automated guided vehicle (AGV) pick tasks.",
    businessObjective: "Join Hubs to Aisles, Bins, and RobotTasks to evaluate average robotic retrieval speed per facility zone.",
    schemaSnippet: "`FulfillmentCenters (hub_id VARCHAR(16) PRIMARY KEY, hub_name VARCHAR(64))` & `WarehouseAislesTable (aisle_id VARCHAR(16) PRIMARY KEY, hub_id VARCHAR(16), zone_code VARCHAR(8))` & `StorageBinSlots (bin_id VARCHAR(16) PRIMARY KEY, aisle_id VARCHAR(16))` & `RobotPickTasks (task_id BIGINT PRIMARY KEY, bin_id VARCHAR(16), retrieval_seconds INT)`",
    targetQuery: `SELECT h.hub_name, a.zone_code,\n       COUNT(t.task_id) AS total_robotic_picks,\n       ROUND(AVG(t.retrieval_seconds), 1) AS avg_pick_seconds\nFROM FulfillmentCenters h\nINNER JOIN WarehouseAislesTable a\n  ON h.hub_id = a.hub_id\nINNER JOIN StorageBinSlots b\n  ON a.aisle_id = b.aisle_id\nINNER JOIN RobotPickTasks t\n  ON b.bin_id = t.bin_id\nGROUP BY h.hub_name, a.zone_code\nORDER BY avg_pick_seconds ASC;`,
    eli5Story: "Measuring how fast robotic Amazon warehouse carts can retrieve shoe boxes from Shelf 3B in Zone Green compared to Zone Blue.",
    commonMistakes: "Omitting the intermediate bin slots table, attempting to join robot tasks directly to aisles.",
    learningOutcomes: "Analyze facility automation telemetry across 4 physical warehouse hierarchy levels."
  },
  {
    title: "Last-Mile Delivery Route Performance Pipeline (Depots -> Vehicles -> Routes -> DeliveryStops)",
    ind: "Logistics",
    diff: "Easy",
    table: "DeliveryDepots",
    scenario: "Evaluating last-mile courier delivery efficiency by joining regional delivery depots, delivery vans, planned dispatch routes, and completed customer doorstep drop-off stops.",
    businessObjective: "Join Depots to Vehicles, Routes, and DeliveryStops to calculate on-time delivery percentages per metropolitan delivery depot.",
    schemaSnippet: "`DeliveryDepots (depot_id VARCHAR(16) PRIMARY KEY, city_name VARCHAR(32))` & `DeliveryFleet (van_id VARCHAR(16) PRIMARY KEY, depot_id VARCHAR(16))` & `DispatchRoutes (route_id VARCHAR(32) PRIMARY KEY, van_id VARCHAR(16))` & `DoorstepStops (stop_id BIGINT PRIMARY KEY, route_id VARCHAR(32), is_on_time BOOLEAN)`",
    targetQuery: `SELECT d.city_name,\n       COUNT(DISTINCT v.van_id) AS vans_dispatched,\n       COUNT(s.stop_id) AS total_doorstep_deliveries,\n       ROUND((SUM(CASE WHEN s.is_on_time = TRUE THEN 1 ELSE 0 END) * 100.0) / COUNT(s.stop_id), 1) AS on_time_delivery_pct\nFROM DeliveryDepots d\nINNER JOIN DeliveryFleet v\n  ON d.depot_id = v.depot_id\nINNER JOIN DispatchRoutes r\n  ON v.van_id = r.van_id\nINNER JOIN DoorstepStops s\n  ON r.route_id = s.route_id\nGROUP BY d.city_name\nORDER BY on_time_delivery_pct DESC;`,
    eli5Story: "Checking on-time delivery scores for parcel vans in Atlanta, Dallas, and Seattle: linking the depot building, to the delivery truck, to the driving route, to the package drop-off at the customer's porch.",
    commonMistakes: "Using `COUNT(v.van_id)` instead of `COUNT(DISTINCT v.van_id)`, overcounting delivery vans by the number of doorstep deliveries made.",
    learningOutcomes: "Calculate logistics SLA on-time percentages using 4-tier last-mile delivery schemas."
  },

  // --- MEDIA ---
  {
    title: "Streaming Video Viewer Retention Pipeline (Subscribers -> Subscriptions -> PlaybackSessions -> Titles)",
    ind: "Media",
    diff: "Medium",
    table: "PlatformSubscribers",
    scenario: "Analyzing subscriber churn drivers by joining user profiles, subscription plans, video stream playback logs, and movie catalog metadata.",
    businessObjective: "Join Subscribers to Subscriptions, PlaybackSessions, and VideoCatalog to compute total hours streamed per subscription plan tier.",
    schemaSnippet: "`PlatformSubscribers (user_id VARCHAR(32) PRIMARY KEY, country VARCHAR(2))` & `PlanSubscriptions (sub_id VARCHAR(32) PRIMARY KEY, user_id VARCHAR(32), plan_type VARCHAR(16))` & `PlaybackSessions (session_id BIGINT PRIMARY KEY, user_id VARCHAR(32), title_id VARCHAR(32), watch_duration_sec INT)` & `VideoCatalog (title_id VARCHAR(32) PRIMARY KEY, genre VARCHAR(32))`",
    targetQuery: `SELECT p.plan_type, v.genre,\n       COUNT(DISTINCT s.user_id) AS unique_viewers,\n       ROUND(SUM(s.watch_duration_sec) / 3600.0, 1) AS total_stream_hours\nFROM PlatformSubscribers u\nINNER JOIN PlanSubscriptions p\n  ON u.user_id = p.user_id\nINNER JOIN PlaybackSessions s\n  ON u.user_id = s.user_id\nINNER JOIN VideoCatalog v\n  ON s.title_id = v.title_id\nGROUP BY p.plan_type, v.genre\nORDER BY total_stream_hours DESC;`,
    eli5Story: "Seeing whether customers who pay for the $19.99 4K Netflix plan watch more Sci-Fi or Comedy movies than customers on the basic $9.99 plan.",
    commonMistakes: "Joining PlaybackSessions to PlanSubscriptions on sub_id when playback sessions are directly keyed to user_id.",
    learningOutcomes: "Perform audience behavior cohort analysis using 4-table streaming media pipelines."
  },
  {
    title: "Music Catalog Publishing Royalty Distribution Pipeline (Artists -> Albums -> Tracks -> RoyaltySplits)",
    ind: "Media",
    diff: "Hard",
    table: "RecordingArtists",
    scenario: "Allocating publishing royalties to record producers and songwriters by joining music artists, released albums, audio tracks, and contractual royalty share agreements.",
    businessObjective: "Join Artists to Albums, Tracks, and RoyaltySplits to compute total royalties payable per songwriter.",
    schemaSnippet: "`RecordingArtists (artist_id VARCHAR(32) PRIMARY KEY, stage_name VARCHAR(100))` & `MusicAlbums (album_id VARCHAR(32) PRIMARY KEY, artist_id VARCHAR(32))` & `AudioTracks (track_id VARCHAR(32) PRIMARY KEY, album_id VARCHAR(32), net_streams BIGINT)` & `RoyaltySplits (split_id BIGINT PRIMARY KEY, track_id VARCHAR(32), contributor_name VARCHAR(100), split_percentage DECIMAL(5,2))`",
    targetQuery: `SELECT rs.contributor_name,\n       COUNT(DISTINCT t.track_id) AS tracks_credited,\n       ROUND(SUM(t.net_streams * 0.004 * (rs.split_percentage / 100.0)), 2) AS total_royalty_payable_usd\nFROM RecordingArtists a\nINNER JOIN MusicAlbums alb\n  ON a.artist_id = alb.artist_id\nINNER JOIN AudioTracks t\n  ON alb.album_id = t.album_id\nINNER JOIN RoyaltySplits rs\n  ON t.track_id = rs.track_id\nGROUP BY rs.contributor_name\nORDER BY total_royalty_payable_usd DESC;`,
    eli5Story: "Splitting streaming music money: multiplying millions of song plays by $0.004/stream and calculating the 20% songwriting check owed to the producer.",
    commonMistakes: "Omitting the percentage division (`/ 100.0`), giving contributors 100 times their legal share.",
    learningOutcomes: "Calculate multi-contributor intellectual property royalties across 4-level media catalogs."
  },
  {
    title: "Programmatic Ad Impression Delivery Pipeline (Advertisers -> Campaigns -> AdCreatives -> Impressions)",
    ind: "Media",
    diff: "Easy",
    table: "CorporateAdvertisers",
    scenario: "Auditing digital advertising campaigns by joining corporate advertisers, marketing campaigns, individual ad banner creatives, and verified impression delivery logs.",
    businessObjective: "Join Advertisers to Campaigns, Creatives, and ImpressionLogs to calculate ad click-through rates (CTR) per advertiser.",
    schemaSnippet: "`CorporateAdvertisers (advertiser_id VARCHAR(32) PRIMARY KEY, brand_name VARCHAR(100))` & `AdCampaignsPipeline (campaign_id VARCHAR(32) PRIMARY KEY, advertiser_id VARCHAR(32))` & `AdCreatives (creative_id VARCHAR(32) PRIMARY KEY, campaign_id VARCHAR(32), banner_format VARCHAR(16))` & `ImpressionLogs (impression_id BIGINT PRIMARY KEY, creative_id VARCHAR(32), was_clicked BOOLEAN)`",
    targetQuery: `SELECT a.brand_name,\n       c.banner_format,\n       COUNT(i.impression_id) AS impressions_served,\n       SUM(CASE WHEN i.was_clicked = TRUE THEN 1 ELSE 0 END) AS clicks_generated,\n       ROUND((SUM(CASE WHEN i.was_clicked = TRUE THEN 1 ELSE 0 END) * 100.0) / COUNT(i.impression_id), 2) AS ctr_percentage\nFROM CorporateAdvertisers a\nINNER JOIN AdCampaignsPipeline cp\n  ON a.advertiser_id = cp.advertiser_id\nINNER JOIN AdCreatives c\n  ON cp.campaign_id = c.campaign_id\nINNER JOIN ImpressionLogs i\n  ON c.creative_id = i.creative_id\nGROUP BY a.brand_name, c.banner_format\nORDER BY ctr_percentage DESC;`,
    eli5Story: "Calculating click-through rates: checking how many people saw Nike's mobile banner ad vs how many people clicked on it.",
    commonMistakes: "Using `COUNT(i.was_clicked)` instead of summing when `was_clicked` is TRUE (since `was_clicked = FALSE` would still be counted as non-null).",
    learningOutcomes: "Calculate programmatic advertising engagement metrics across 4-tier advertising pipelines."
  },
  {
    title: "Creator Economy Live-Stream Donation Pipeline (Creators -> Channels -> Streams -> SuperChats)",
    ind: "Media",
    diff: "Medium",
    table: "StreamerProfiles",
    scenario: "Reconciling live streaming revenue by joining creators, broadcast channels, live stream broadcast sessions, and viewer cash donations.",
    businessObjective: "Join Streamers to Channels, LiveSessions, and CashDonations to calculate platform gross revenue per streaming content category.",
    schemaSnippet: "`StreamerProfiles (streamer_id VARCHAR(32) PRIMARY KEY, handle VARCHAR(48))` & `BroadcastChannels (channel_id VARCHAR(32) PRIMARY KEY, streamer_id VARCHAR(32), content_category VARCHAR(32))` & `LiveSessions (session_id VARCHAR(32) PRIMARY KEY, channel_id VARCHAR(32))` & `CashDonations (donation_id BIGINT PRIMARY KEY, session_id VARCHAR(32), donation_amount_usd DECIMAL(8,2))`",
    targetQuery: `SELECT ch.content_category,\n       COUNT(DISTINCT p.streamer_id) AS active_streamers,\n       COUNT(d.donation_id) AS total_donations_sent,\n       SUM(d.donation_amount_usd) AS gross_donations_usd\nFROM StreamerProfiles p\nINNER JOIN BroadcastChannels ch\n  ON p.streamer_id = ch.streamer_id\nINNER JOIN LiveSessions s\n  ON ch.channel_id = s.channel_id\nINNER JOIN CashDonations d\n  ON s.session_id = d.session_id\nGROUP BY ch.content_category\nORDER BY gross_donations_usd DESC;`,
    eli5Story: "Adding up all the super-chat cash donations fans sent to video game streamers, cooking streamers, and music streamers during their live broadcasts.",
    commonMistakes: "Grouping by streamer handle when the prompt asks for categorical content revenue.",
    learningOutcomes: "Aggregate creator platform monetization metrics across 4-tier live broadcast schemas."
  },

  // --- SECURITY ---
  {
    title: "RBAC Access Governance Pipeline (Users -> AssignedRoles -> RolePermissions -> SystemResources)",
    ind: "Security",
    diff: "Medium",
    table: "CorporateUsers",
    scenario: "Enforcing cybersecurity least-privilege principles by joining user accounts, assigned RBAC roles, permission grants, and protected IT server resources.",
    businessObjective: "Join Users to AssignedRoles, RolePermissions, and ProtectedResources to audit who has administrative write access to production database systems.",
    schemaSnippet: "`CorporateUsers (user_id VARCHAR(32) PRIMARY KEY, email VARCHAR(100))` & `AssignedRoles (user_id VARCHAR(32), role_id VARCHAR(16), PRIMARY KEY(user_id, role_id))` & `RolePermissions (role_id VARCHAR(16), resource_id VARCHAR(32), permission_type VARCHAR(16), PRIMARY KEY(role_id, resource_id))` & `ProtectedResources (resource_id VARCHAR(32) PRIMARY KEY, resource_name VARCHAR(64), env VARCHAR(16))`",
    targetQuery: `SELECT u.email, r.resource_name, p.permission_type\nFROM CorporateUsers u\nINNER JOIN AssignedRoles ar\n  ON u.user_id = ar.user_id\nINNER JOIN RolePermissions p\n  ON ar.role_id = p.role_id\nINNER JOIN ProtectedResources r\n  ON p.resource_id = r.resource_id\nWHERE r.env = 'PRODUCTION'\n  AND p.permission_type = 'ADMIN_WRITE'\nORDER BY u.email ASC;`,
    eli5Story: "Checking who has the keys to the castle: showing every employee whose job role gives them permission to change or delete our production customer database.",
    commonMistakes: "Overlooking that junction tables (`AssignedRoles`, `RolePermissions`) can produce duplicates if an employee has multiple roles granting the same permission.",
    learningOutcomes: "Audit Role-Based Access Control (RBAC) security permissions across 4 normalized authorization tables."
  },
  {
    title: "Cloud VPC Network Architecture Security Pipeline (VPCs -> Subnets -> SecurityGroups -> ENIs)",
    ind: "Security",
    diff: "Easy",
    table: "VirtualPrivateClouds",
    scenario: "Auditing cloud network infrastructure isolation by joining VPC virtual networks, private subnets, firewall security groups, and attached virtual network interfaces.",
    businessObjective: "Join VPCs to Subnets, SecurityGroups, and NetworkInterfaces to count active network interfaces attached to public subnets.",
    schemaSnippet: "`VirtualPrivateClouds (vpc_id VARCHAR(21) PRIMARY KEY, vpc_name VARCHAR(64))` & `VpcSubnets (subnet_id VARCHAR(24) PRIMARY KEY, vpc_id VARCHAR(21), is_public BOOLEAN)` & `VpcSecurityGroups (group_id VARCHAR(20) PRIMARY KEY, vpc_id VARCHAR(21))` & `ElasticNetworkInterfaces (eni_id VARCHAR(21) PRIMARY KEY, subnet_id VARCHAR(24), group_id VARCHAR(20))`",
    targetQuery: `SELECT v.vpc_name,\n       s.is_public,\n       COUNT(e.eni_id) AS active_network_interfaces\nFROM VirtualPrivateClouds v\nINNER JOIN VpcSubnets s\n  ON v.vpc_id = s.vpc_id\nINNER JOIN ElasticNetworkInterfaces e\n  ON s.subnet_id = e.subnet_id\nINNER JOIN VpcSecurityGroups g\n  ON e.group_id = g.group_id\nGROUP BY v.vpc_name, s.is_public\nORDER BY active_network_interfaces DESC;`,
    eli5Story: "Mapping out our company's cloud network: showing which computers are plugged into private secure subnets vs public internet subnets.",
    commonMistakes: "Joining ElasticNetworkInterfaces to VpcSecurityGroups on vpc_id instead of group_id.",
    learningOutcomes: "Audit cloud networking topology and firewall attachment architecture using 4-tier joins."
  },
  {
    title: "Vulnerability Management Lifecycle Pipeline (Assets -> Detections -> Exploits -> Patches)",
    ind: "Security",
    diff: "Hard",
    table: "CorporateHosts",
    scenario: "Prioritizing urgent vulnerability patching by joining corporate hosts, scanner CVE detections, known weaponized exploit catalogs, and engineering Jira patch tickets.",
    businessObjective: "Join Hosts to Detections, ExploitFeeds, and PatchTickets to report unpatched weaponized vulnerabilities on production servers.",
    schemaSnippet: "`CorporateHosts (asset_id VARCHAR(32) PRIMARY KEY, hostname VARCHAR(64), tier VARCHAR(16))` & `HostDetections (finding_id BIGINT PRIMARY KEY, asset_id VARCHAR(32), cve_id VARCHAR(16))` & `ExploitFeeds (cve_id VARCHAR(16) PRIMARY KEY, is_weaponized BOOLEAN)` & `PatchTickets (cve_id VARCHAR(16) PRIMARY KEY, ticket_status VARCHAR(16))`",
    targetQuery: `SELECT h.hostname, h.tier, d.cve_id,\n       COALESCE(pt.ticket_status, 'NO_REMEDIATION_TICKET_LOGGED') AS patch_status\nFROM CorporateHosts h\nINNER JOIN HostDetections d\n  ON h.asset_id = d.asset_id\nINNER JOIN ExploitFeeds ef\n  ON d.cve_id = ef.cve_id\nLEFT JOIN PatchTickets pt\n  ON d.cve_id = pt.cve_id\nWHERE ef.is_weaponized = TRUE\n  AND h.tier = 'PRODUCTION'\n  AND (pt.ticket_status <> 'CLOSED' OR pt.ticket_status IS NULL)\nORDER BY h.hostname ASC;`,
    eli5Story: "Finding dangerous software bugs on our main production servers that hackers have already built automated attack tools for, where our IT team hasn't patched them yet.",
    commonMistakes: "Using an INNER JOIN on PatchTickets which hides the most dangerous vulnerabilities of all: the ones where nobody even filed a patch ticket yet!",
    learningOutcomes: "Execute threat intelligence vulnerability prioritization using combined inner and outer joins across 4 tables."
  },
  {
    title: "Endpoint Incident Containment Pipeline (Workstations -> EDR -> ThreatAlerts -> QuarantineActions)",
    ind: "Security",
    diff: "Medium",
    table: "WorkstationFleet",
    scenario: "Auditing automated malware containment by joining corporate workstations, installed EDR security agents, detected malware alarms, and automated network quarantine actions.",
    businessObjective: "Join Workstations to Agents, Alerts, and QuarantineActions to verify that 100% of high-severity malware alerts resulted in automated network isolation.",
    schemaSnippet: "`WorkstationFleet (endpoint_id VARCHAR(32) PRIMARY KEY, assigned_user VARCHAR(100))` & `EdrAgentsPipeline (agent_id VARCHAR(32) PRIMARY KEY, endpoint_id VARCHAR(32))` & `ThreatAlertsPipeline (alert_id BIGINT PRIMARY KEY, agent_id VARCHAR(32), severity VARCHAR(16))` & `QuarantineActions (action_id BIGINT PRIMARY KEY, alert_id BIGINT, is_isolated BOOLEAN)`",
    targetQuery: `SELECT w.endpoint_id, w.assigned_user, a.alert_id,\n       COALESCE(q.is_isolated, FALSE) AS network_isolated\nFROM WorkstationFleet w\nINNER JOIN EdrAgentsPipeline ag\n  ON w.endpoint_id = ag.endpoint_id\nINNER JOIN ThreatAlertsPipeline a\n  ON ag.agent_id = a.agent_id\nLEFT JOIN QuarantineActions q\n  ON a.alert_id = q.alert_id\nWHERE a.severity = 'CRITICAL'\nORDER BY network_isolated ASC;`,
    eli5Story: "Checking that whenever our anti-virus system detected critical ransomware on a laptop, it automatically unplugged that laptop from the network immediately.",
    commonMistakes: "Using INNER JOIN which hides critical alerts that failed to trigger a quarantine response.",
    learningOutcomes: "Audit automated cybersecurity incident response workflows using 4-table containment pipelines."
  },

  // --- HARDWARE ---
  {
    title: "Semiconductor Cleanroom Manufacturing Telemetry (Facilities -> Cleanrooms -> Steppers -> WaferRuns)",
    ind: "Hardware",
    diff: "Hard",
    table: "FabCampuses",
    scenario: "Tracking semiconductor cleanroom productivity by joining fabrication campuses, ISO cleanroom suites, EUV photolithography tools, and individual silicon wafer production runs.",
    businessObjective: "Join Campuses to Cleanrooms, StepperTools, and WaferRuns to report average optical overlay error per cleanroom facility.",
    schemaSnippet: "`FabCampuses (campus_id VARCHAR(16) PRIMARY KEY, campus_name VARCHAR(64))` & `CleanroomSuites (cleanroom_id VARCHAR(16) PRIMARY KEY, campus_id VARCHAR(16), iso_class INT)` & `StepperTools (tool_id VARCHAR(16) PRIMARY KEY, cleanroom_id VARCHAR(16))` & `FabWaferRuns (run_id BIGINT PRIMARY KEY, tool_id VARCHAR(16), overlay_error_nm DECIMAL(5,2))`",
    targetQuery: `SELECT c.campus_name, cr.iso_class,\n       COUNT(r.run_id) AS total_wafer_runs,\n       ROUND(AVG(r.overlay_error_nm), 2) AS avg_overlay_error_nm\nFROM FabCampuses c\nINNER JOIN CleanroomSuites cr\n  ON c.campus_id = cr.campus_id\nINNER JOIN StepperTools st\n  ON cr.cleanroom_id = st.cleanroom_id\nINNER JOIN FabWaferRuns r\n  ON st.tool_id = r.tool_id\nGROUP BY c.campus_name, cr.iso_class\nORDER BY avg_overlay_error_nm ASC;`,
    eli5Story: "Tracking precision chip-printing lasers: measuring laser alignment error across cleanroom facilities in Taiwan, Arizona, and Germany.",
    commonMistakes: "Grouping by tool_id when the executive query asks for campus cleanroom aggregations.",
    learningOutcomes: "Aggregate semiconductor manufacturing metrics across 4 physical facility and tooling tiers."
  },
  {
    title: "Electronics Supply Chain Component Traceability (Suppliers -> Parts -> Assemblies -> Inspections)",
    ind: "Hardware",
    diff: "Medium",
    table: "ElectronicPartsSuppliers",
    scenario: "Tracing component quality issues on finished laptop motherboards back to raw capacitor suppliers by joining suppliers, parts, circuit board assemblies, and optical inspection defect logs.",
    businessObjective: "Join Suppliers to Parts, BoardAssemblies, and OpticalInspections to calculate defect rates per raw electronics supplier.",
    schemaSnippet: "`ElectronicPartsSuppliers (supplier_id VARCHAR(32) PRIMARY KEY, supplier_name VARCHAR(100))` & `ElectronicParts (part_no VARCHAR(32) PRIMARY KEY, supplier_id VARCHAR(32))` & `BoardAssemblies (board_serial VARCHAR(32) PRIMARY KEY, part_no VARCHAR(32))` & `OpticalInspections (inspection_id BIGINT PRIMARY KEY, board_serial VARCHAR(32), is_defective BOOLEAN)`",
    targetQuery: `SELECT s.supplier_name,\n       COUNT(DISTINCT b.board_serial) AS boards_manufactured,\n       SUM(CASE WHEN i.is_defective = TRUE THEN 1 ELSE 0 END) AS defective_boards_count,\n       ROUND((SUM(CASE WHEN i.is_defective = TRUE THEN 1 ELSE 0 END) * 100.0) / COUNT(DISTINCT b.board_serial), 2) AS defect_rate_pct\nFROM ElectronicPartsSuppliers s\nINNER JOIN ElectronicParts p\n  ON s.supplier_id = p.supplier_id\nINNER JOIN BoardAssemblies b\n  ON p.part_no = b.part_no\nINNER JOIN OpticalInspections i\n  ON b.board_serial = i.board_serial\nGROUP BY s.supplier_name\nORDER BY defect_rate_pct DESC;`,
    eli5Story: "Finding out which microchip or capacitor supplier caused our factory's laptop motherboards to fail the quality laser scanner inspection.",
    commonMistakes: "Using `COUNT(b.board_serial)` instead of `COUNT(DISTINCT b.board_serial)` if a board underwent multiple inspection passes.",
    learningOutcomes: "Trace manufacturing defects across 4-level electronics assembly supply chains."
  },
  {
    title: "Automated Factory Assembly Quality Control Pipeline (Workstations -> Robots -> Tasks -> DefectLogs)",
    ind: "Hardware",
    diff: "Easy",
    table: "FactoryStationsTable",
    scenario: "Monitoring automotive robotic assembly lines by joining factory workstations, automated robot arms, scheduled assembly tasks, and automated defect sensor logs.",
    businessObjective: "Join Workstations to Robots, AssemblyTasks, and DefectLogs to identify robot arms experiencing high screw tightening torque failures.",
    schemaSnippet: "`FactoryStationsTable (station_id VARCHAR(16) PRIMARY KEY, station_name VARCHAR(32))` & `StationRobots (robot_id VARCHAR(16) PRIMARY KEY, station_id VARCHAR(16))` & `AssemblyTasks (task_id BIGINT PRIMARY KEY, robot_id VARCHAR(16), task_type VARCHAR(32))` & `TaskDefectLogs (defect_id BIGINT PRIMARY KEY, task_id BIGINT, error_code VARCHAR(16))`",
    targetQuery: `SELECT s.station_name, r.robot_id,\n       COUNT(d.defect_id) AS total_defects_logged\nFROM FactoryStationsTable s\nINNER JOIN StationRobots r\n  ON s.station_id = r.station_id\nINNER JOIN AssemblyTasks t\n  ON r.robot_id = t.robot_id\nINNER JOIN TaskDefectLogs d\n  ON t.task_id = d.task_id\nWHERE d.error_code = 'TORQUE_OUT_OF_SPEC'\nGROUP BY s.station_name, r.robot_id\nORDER BY total_defects_logged DESC;`,
    eli5Story: "Checking which robotic arm on the car assembly line is tightening lug nuts too loose or too tight so mechanics can recalibrate it.",
    commonMistakes: "Using a LEFT JOIN when the query explicitly asks to count logged defects.",
    learningOutcomes: "Analyze factory automation quality metrics across 4-tier manufacturing equipment models."
  },
  {
    title: "Hardware Stress Testing Lifecycle Pipeline (Models -> Units -> Chambers -> AcceptanceCerts)",
    ind: "Hardware",
    diff: "Hard",
    table: "DeviceModelsTable",
    scenario: "Certifying rugged industrial laptops for defense deployment by joining device model specs, manufactured physical units, thermal stress chamber logs, and final military-grade acceptance certificates.",
    businessObjective: "Join Models to Units, StressChambers, and AcceptanceCertificates to calculate military acceptance certification rates per device model.",
    schemaSnippet: "`DeviceModelsTable (model_id VARCHAR(16) PRIMARY KEY, model_name VARCHAR(64))` & `PhysicalUnits (unit_serial VARCHAR(32) PRIMARY KEY, model_id VARCHAR(16))` & `ChamberStressTests (test_id BIGINT PRIMARY KEY, unit_serial VARCHAR(32), passed_thermal BOOLEAN)` & `AcceptanceCertificates (cert_id VARCHAR(32) PRIMARY KEY, unit_serial VARCHAR(32))`",
    targetQuery: `SELECT m.model_name,\n       COUNT(DISTINCT u.unit_serial) AS total_units_built,\n       COUNT(DISTINCT c.cert_id) AS military_certified_units,\n       ROUND((COUNT(DISTINCT c.cert_id) * 100.0) / COUNT(DISTINCT u.unit_serial), 1) AS certification_yield_pct\nFROM DeviceModelsTable m\nINNER JOIN PhysicalUnits u\n  ON m.model_id = u.model_id\nINNER JOIN ChamberStressTests t\n  ON u.unit_serial = t.unit_serial\nLEFT JOIN AcceptanceCertificates c\n  ON u.unit_serial = c.unit_serial\nWHERE t.passed_thermal = TRUE\nGROUP BY m.model_name\nORDER BY certification_yield_pct DESC;`,
    eli5Story: "Testing tough military laptops in freezing and boiling ovens: calculating what percentage of built laptops earned their official Pentagon quality seal.",
    commonMistakes: "Using INNER JOIN on AcceptanceCertificates which would make the certification yield calculate as 100% everywhere.",
    learningOutcomes: "Model hardware environmental qualification testing across 4 normalized certification tables."
  },

  // --- HR ---
  {
    title: "Corporate Organizational Hierarchy Rollup (Companies -> Divisions -> Departments -> Staff)",
    ind: "HR",
    diff: "Easy",
    table: "CorporateHoldings",
    scenario: "Generating an enterprise headcount and payroll summary by traversing from corporate holding companies, to regional divisions, to cost-center departments, to individual employees.",
    businessObjective: "Join Holdings to Divisions, Departments, and Staff to report headcount and average salary per division.",
    schemaSnippet: "`CorporateHoldings (holding_id VARCHAR(16) PRIMARY KEY, holding_name VARCHAR(64))` & `CompanyDivisions (division_id VARCHAR(16) PRIMARY KEY, holding_id VARCHAR(16), division_name VARCHAR(64))` & `CostDepartments (dept_id VARCHAR(16) PRIMARY KEY, division_id VARCHAR(16), dept_name VARCHAR(64))` & `EmployeeStaffTable (emp_id VARCHAR(32) PRIMARY KEY, dept_id VARCHAR(16), salary_usd DECIMAL(10,2))`",
    targetQuery: `SELECT d.division_name,\n       COUNT(e.emp_id) AS total_headcount,\n       ROUND(AVG(e.salary_usd), 2) AS avg_annual_salary_usd,\n       SUM(e.salary_usd) AS total_payroll_expenditure_usd\nFROM CorporateHoldings h\nINNER JOIN CompanyDivisions d\n  ON h.holding_id = d.holding_id\nINNER JOIN CostDepartments cd\n  ON d.division_id = cd.division_id\nINNER JOIN EmployeeStaffTable e\n  ON cd.dept_id = e.dept_id\nGROUP BY d.division_name\nORDER BY total_payroll_expenditure_usd DESC;`,
    eli5Story: "Rolling up corporate payroll: adding up salary and employee count across North America, Europe, and Asia divisions for executive reporting.",
    commonMistakes: "Joining departments directly to holdings, bypassing the division intermediate tier.",
    learningOutcomes: "Aggregate financial and human resources metrics across 4-level corporate organizational hierarchies."
  },
  {
    title: "Employee Compensation Merit Increase Modeling (Employees -> Plans -> Revisions -> Ratings)",
    ind: "HR",
    diff: "Hard",
    table: "StaffEmployees",
    scenario: "Modeling annual salary merit increases by joining employees, compensation salary band plans, historical salary revisions, and annual performance review ratings.",
    businessObjective: "Join Employees to SalaryBands, SalaryRevisions, and PerformanceReviews to compute budget impact of recommended merit raises.",
    schemaSnippet: "`StaffEmployees (emp_id VARCHAR(32) PRIMARY KEY, emp_name VARCHAR(100), job_level VARCHAR(8))` & `SalaryBands (job_level VARCHAR(8) PRIMARY KEY, midpoint_salary DECIMAL(10,2))` & `SalaryRevisions (rev_id BIGINT PRIMARY KEY, emp_id VARCHAR(32), current_salary DECIMAL(10,2))` & `PerformanceReviews (review_id BIGINT PRIMARY KEY, emp_id VARCHAR(32), rating_score INT)`",
    targetQuery: `SELECT e.job_level,\n       COUNT(DISTINCT e.emp_id) AS employee_count,\n       ROUND(AVG(r.current_salary), 2) AS avg_current_salary,\n       b.midpoint_salary,\n       ROUND(AVG(pr.rating_score), 2) AS avg_performance_score\nFROM StaffEmployees e\nINNER JOIN SalaryBands b\n  ON e.job_level = b.job_level\nINNER JOIN SalaryRevisions r\n  ON e.emp_id = r.emp_id\nINNER JOIN PerformanceReviews pr\n  ON e.emp_id = pr.emp_id\nGROUP BY e.job_level, b.midpoint_salary\nORDER BY avg_performance_score DESC;`,
    eli5Story: "Reviewing employee performance scores and current salaries to see which job levels deserve the biggest budget for annual salary raises.",
    commonMistakes: "Using a raw join on revisions and reviews without ensuring 1 revision and 1 review per employee per cycle, causing row multiplication.",
    learningOutcomes: "Model corporate compensation and merit increase budgets across 4-tier HR schemas."
  },
  {
    title: "Applicant Tracking and Talent Acquisition Pipeline (Requisitions -> Candidates -> Interviews -> Offers)",
    ind: "HR",
    diff: "Medium",
    table: "OpenJobRequisitions",
    scenario: "Tracking recruitment funnel throughput by joining job requisitions, applying candidates, completed technical interview rounds, and extended employment job offers.",
    businessObjective: "Join Requisitions to Candidates, Interviews, and JobOffers to calculate interview-to-offer conversion rates per department.",
    schemaSnippet: "`OpenJobRequisitions (req_id VARCHAR(32) PRIMARY KEY, department VARCHAR(32))` & `JobCandidates (candidate_id VARCHAR(32) PRIMARY KEY, req_id VARCHAR(32))` & `InterviewRounds (round_id BIGINT PRIMARY KEY, candidate_id VARCHAR(32), passed_round BOOLEAN)` & `ExtendedOffers (offer_id VARCHAR(32) PRIMARY KEY, candidate_id VARCHAR(32), is_accepted BOOLEAN)`",
    targetQuery: `SELECT r.department,\n       COUNT(DISTINCT c.candidate_id) AS total_applicants,\n       COUNT(DISTINCT o.offer_id) AS offers_extended,\n       SUM(CASE WHEN o.is_accepted = TRUE THEN 1 ELSE 0 END) AS offers_accepted\nFROM OpenJobRequisitions r\nINNER JOIN JobCandidates c\n  ON r.req_id = c.req_id\nINNER JOIN InterviewRounds ir\n  ON c.candidate_id = ir.candidate_id\nLEFT JOIN ExtendedOffers o\n  ON c.candidate_id = o.candidate_id\nWHERE ir.passed_round = TRUE\nGROUP BY r.department\nORDER BY total_applicants DESC;`,
    eli5Story: "Checking our hiring funnel: seeing how many people applied, passed the technical coding interview, received a job offer, and accepted the job.",
    commonMistakes: "Using an INNER JOIN on ExtendedOffers which drops candidates who completed interviews but did not receive an offer.",
    learningOutcomes: "Measure recruitment conversion velocity across 4-stage talent acquisition pipelines."
  },
  {
    title: "Total Rewards Benefit Administration Pipeline (Employees -> Plans -> Dependents -> PayrollDeductions)",
    ind: "HR",
    diff: "Easy",
    table: "BenefitEmployees",
    scenario: "Reconciling corporate health insurance premium payroll deductions by joining employees, enrolled healthcare plans, covered family dependents, and payroll ledger deductions.",
    businessObjective: "Join Employees to HealthPlans, Dependents, and PayrollDeductions to verify deduction accuracy.",
    schemaSnippet: "`BenefitEmployees (emp_id VARCHAR(32) PRIMARY KEY, emp_name VARCHAR(100))` & `EnrolledHealthPlans (plan_enrollment_id VARCHAR(32) PRIMARY KEY, emp_id VARCHAR(32), plan_type VARCHAR(16))` & `EnrolledDependents (dep_id BIGINT PRIMARY KEY, emp_id VARCHAR(32))` & `DeductionLedger (deduction_id BIGINT PRIMARY KEY, emp_id VARCHAR(32), employee_contribution_usd DECIMAL(8,2))`",
    targetQuery: `SELECT p.plan_type,\n       COUNT(DISTINCT e.emp_id) AS enrolled_employees,\n       COUNT(DISTINCT d.dep_id) AS covered_dependents,\n       SUM(dl.employee_contribution_usd) AS total_employee_contributions_usd\nFROM BenefitEmployees e\nINNER JOIN EnrolledHealthPlans p\n  ON e.emp_id = p.emp_id\nLEFT JOIN EnrolledDependents d\n  ON e.emp_id = d.emp_id\nINNER JOIN DeductionLedger dl\n  ON e.emp_id = dl.emp_id\nGROUP BY p.plan_type\nORDER BY total_employee_contributions_usd DESC;`,
    eli5Story: "Adding up how much employees and the company paid for health and dental insurance, including coverage for kids and spouses.",
    commonMistakes: "Using an INNER JOIN on dependents which excludes single employees without children from the report.",
    learningOutcomes: "Reconcile corporate benefits and payroll deductions across 4 normalized HR tables."
  },

  // --- PLATFORMS ---
  {
    title: "Ride-Share Marketplace Economic Clearing Pipeline (Riders -> Trips -> Drivers -> Payouts)",
    ind: "Platforms",
    diff: "Medium",
    table: "PlatformRiders",
    scenario: "Auditing two-sided ride-share marketplace economics by joining passenger riders, completed taxi trips, assigned gig drivers, and driver weekly payout deposit batches.",
    businessObjective: "Join Riders to Trips, Drivers, and PayoutBatches to compute platform net revenue retention per metropolitan market.",
    schemaSnippet: "`PlatformRiders (rider_id VARCHAR(32) PRIMARY KEY, home_city VARCHAR(32))` & `PlatformTrips (trip_id VARCHAR(32) PRIMARY KEY, rider_id VARCHAR(32), driver_id VARCHAR(32), passenger_fare_usd DECIMAL(8,2))` & `GigDriversPipeline (driver_id VARCHAR(32) PRIMARY KEY, payout_batch_id VARCHAR(32))` & `WeeklyPayoutBatches (batch_id VARCHAR(32) PRIMARY KEY, net_driver_pay_usd DECIMAL(12,2))`",
    targetQuery: `SELECT r.home_city,\n       COUNT(t.trip_id) AS completed_trips,\n       SUM(t.passenger_fare_usd) AS gross_passenger_bookings_usd\nFROM PlatformRiders r\nINNER JOIN PlatformTrips t\n  ON r.rider_id = t.rider_id\nINNER JOIN GigDriversPipeline d\n  ON t.driver_id = d.driver_id\nINNER JOIN WeeklyPayoutBatches b\n  ON d.payout_batch_id = b.batch_id\nGROUP BY r.home_city\nORDER BY gross_passenger_bookings_usd DESC;`,
    eli5Story: "Tracking ride-share money flow: linking the passenger who ordered the ride, the trip fare, the driver who picked them up, and the bank deposit batch.",
    commonMistakes: "Joining payout batches directly to trips when batches are grouped by driver.",
    learningOutcomes: "Analyze two-sided transportation marketplace economics across 4 relational entities."
  },
  {
    title: "Two-Sided Marketplace Escrow Clearing Pipeline (Buyers -> Orders -> Sellers -> Escrow)",
    ind: "Platforms",
    diff: "Hard",
    table: "MarketplaceBuyers",
    scenario: "Reconciling e-commerce escrow cash accounts by joining registered buyers, marketplace purchase orders, third-party merchants, and bank escrow disbursements.",
    businessObjective: "Join Buyers to Orders, Sellers, and EscrowDisbursements to report completed escrow releases per seller country.",
    schemaSnippet: "`MarketplaceBuyers (buyer_id VARCHAR(32) PRIMARY KEY, buyer_country VARCHAR(2))` & `MarketplaceOrdersPipeline (order_id VARCHAR(32) PRIMARY KEY, buyer_id VARCHAR(32), seller_id VARCHAR(32), order_amount_usd DECIMAL(10,2))` & `MarketplaceSellersPipeline (seller_id VARCHAR(32) PRIMARY KEY, seller_country VARCHAR(2))` & `EscrowDisbursements (disbursement_id VARCHAR(32) PRIMARY KEY, order_id VARCHAR(32), released_usd DECIMAL(10,2))`",
    targetQuery: `SELECT s.seller_country,\n       COUNT(o.order_id) AS orders_cleared,\n       SUM(o.order_amount_usd) AS gross_sales_usd,\n       SUM(e.released_usd) AS net_escrow_released_usd,\n       ROUND(SUM(o.order_amount_usd) - SUM(e.released_usd), 2) AS platform_commission_retained_usd\nFROM MarketplaceBuyers b\nINNER JOIN MarketplaceOrdersPipeline o\n  ON b.buyer_id = o.buyer_id\nINNER JOIN MarketplaceSellersPipeline s\n  ON o.seller_id = s.seller_id\nINNER JOIN EscrowDisbursements e\n  ON o.order_id = e.order_id\nGROUP BY s.seller_country\nORDER BY gross_sales_usd DESC;`,
    eli5Story: "Reconciling international marketplace money: tracking purchases between American buyers and French/Japanese sellers, keeping our platform commission cut.",
    commonMistakes: "Subtracting without SUM() when aggregating multiple orders.",
    learningOutcomes: "Reconcile two-sided commercial escrow settlement pipelines across 4 normalized tables."
  },
  {
    title: "Three-Sided Food Delivery Platform Settlement Pipeline (Customers -> Orders -> Restaurants -> Couriers)",
    ind: "Platforms",
    diff: "Hard",
    table: "FoodDeliveryCustomers",
    scenario: "Reconciling three-sided on-demand food delivery platform transactions by joining eaters, delivery food orders, restaurant partners, and bicycle delivery couriers.",
    businessObjective: "Join Customers to MealOrders, Restaurants, and Couriers to compute commission splits across the three-sided ecosystem.",
    schemaSnippet: "`FoodDeliveryCustomers (customer_id VARCHAR(32) PRIMARY KEY, customer_name VARCHAR(100))` & `DeliveryMealOrders (order_id VARCHAR(32) PRIMARY KEY, customer_id VARCHAR(32), restaurant_id VARCHAR(32), courier_id VARCHAR(32), subtotal_usd DECIMAL(8,2), delivery_fee_usd DECIMAL(6,2))` & `PartnerRestaurants (restaurant_id VARCHAR(32) PRIMARY KEY, restaurant_name VARCHAR(64), commission_pct DECIMAL(4,2))` & `DeliveryCouriersPipeline (courier_id VARCHAR(32) PRIMARY KEY, courier_name VARCHAR(100))`",
    targetQuery: `SELECT r.restaurant_name,\n       COUNT(o.order_id) AS total_orders,\n       SUM(o.subtotal_usd) AS gross_food_spend_usd,\n       ROUND(SUM(o.subtotal_usd * (r.commission_pct / 100.0)), 2) AS restaurant_commission_collected,\n       ROUND(SUM(o.delivery_fee_usd), 2) AS courier_delivery_fees_paid\nFROM FoodDeliveryCustomers c\nINNER JOIN DeliveryMealOrders o\n  ON c.customer_id = o.customer_id\nINNER JOIN PartnerRestaurants r\n  ON o.restaurant_id = r.restaurant_id\nINNER JOIN DeliveryCouriersPipeline cr\n  ON o.courier_id = cr.courier_id\nGROUP BY r.restaurant_id, r.restaurant_name\nORDER BY gross_food_spend_usd DESC;`,
    eli5Story: "Tracking the 3-sided DoorDash triangle: the customer who paid, the restaurant that cooked the pizza, and the delivery driver who biked it to the house.",
    commonMistakes: "Applying the restaurant commission percentage to the delivery fee; delivery fees belong to the courier, not the restaurant.",
    learningOutcomes: "Model multi-party marketplace revenue distribution across 4 interconnected participants."
  },
  {
    title: "App Store Digital Ecosystem Distribution Pipeline (Developers -> Apps -> InAppPurchases -> Commissions)",
    ind: "Platforms",
    diff: "Easy",
    table: "AppDevelopers",
    scenario: "Auditing mobile app store revenue distributions by joining registered software developers, published mobile apps, customer in-app purchases, and store commissions.",
    businessObjective: "Join Developers to Apps, InAppPurchases, and CommissionTiers to calculate net payouts owed to mobile software developers.",
    schemaSnippet: "`AppDevelopers (developer_id VARCHAR(32) PRIMARY KEY, developer_name VARCHAR(100))` & `MobileApps (app_id VARCHAR(32) PRIMARY KEY, developer_id VARCHAR(32), category VARCHAR(32))` & `AppStorePurchases (purchase_id BIGINT PRIMARY KEY, app_id VARCHAR(32), gross_price_usd DECIMAL(8,2))` & `DeveloperRevenueLedger (purchase_id BIGINT PRIMARY KEY, developer_payout_usd DECIMAL(8,2), store_fee_usd DECIMAL(8,2))`",
    targetQuery: `SELECT d.developer_name, a.category,\n       COUNT(p.purchase_id) AS total_sales_count,\n       SUM(p.gross_price_usd) AS gross_store_sales_usd,\n       SUM(l.developer_payout_usd) AS net_developer_payout_usd,\n       SUM(l.store_fee_usd) AS platform_revenue_usd\nFROM AppDevelopers d\nINNER JOIN MobileApps a\n  ON d.developer_id = a.developer_id\nINNER JOIN AppStorePurchases p\n  ON a.app_id = p.app_id\nINNER JOIN DeveloperRevenueLedger l\n  ON p.purchase_id = l.purchase_id\nGROUP BY d.developer_name, a.category\nORDER BY gross_store_sales_usd DESC;`,
    eli5Story: "Splitting mobile app purchases (like buying game coins or subscriptions): calculating the 70% or 85% developer payout vs the 15% or 30% Apple/Google store fee.",
    commonMistakes: "Omitting the app category in the GROUP BY clause.",
    learningOutcomes: "Calculate digital app store developer payouts and commission revenues across 4 normalized entities."
  }
];
