// =============================================================================
// PART 1: INNER JOIN (40 DISTINCT CASES: 13 Easy, 14 Medium, 13 Hard)
// Exact Relational Intersections Across 10 Industries
// =============================================================================

module.exports = [
  // --- FINTECH ---
  {
    title: "Card Swipes to Merchant Risk Profiles (Auth Code Match)",
    ind: "Fintech",
    diff: "Easy",
    table: "CardSwipes",
    scenario: "Matching raw POS card authorization swipes with verified merchant risk profiles to ensure no transactions are processed for blocked merchant category codes (MCC).",
    businessObjective: "Perform an INNER JOIN between CardSwipes and MerchantProfiles on merchant_id, filtering for verified active merchants.",
    schemaSnippet: "`CardSwipes (swipe_id VARCHAR(32) PRIMARY KEY, card_token VARCHAR(64), merchant_id VARCHAR(32), amount_usd DECIMAL(10,2), swipe_time TIMESTAMP)` & `MerchantProfiles (merchant_id VARCHAR(32) PRIMARY KEY, legal_name VARCHAR(100), mcc_code INT, risk_tier VARCHAR(16), is_active BOOLEAN)`",
    targetQuery: `SELECT s.swipe_id, s.card_token, m.legal_name, s.amount_usd, m.mcc_code\nFROM CardSwipes s\nINNER JOIN MerchantProfiles m\n  ON s.merchant_id = m.merchant_id\nWHERE m.is_active = TRUE\nORDER BY s.swipe_time DESC;`,
    eli5Story: "Imagine matching store receipts to our verified vendor directory. Only receipts where the store exists and is marked active are kept for settlement.",
    commonMistakes: "Using a LEFT JOIN when the business explicitly requires only valid, active merchant records.",
    learningOutcomes: "Master basic foreign key equality join syntax and secondary boolean filtering in the WHERE clause."
  },
  {
    title: "Wire Transfers to OFAC Sanctions Clearance Register",
    ind: "Fintech",
    diff: "Medium",
    table: "WireTransfers",
    scenario: "Reconciling cross-border SWIFT wire transfers with the OFAC compliance screening audit logs to calculate total cleared wire volume by currency.",
    businessObjective: "Join WireTransfers to OfacClearances on wire_reference, aggregate total amount, and calculate cleared transaction counts.",
    schemaSnippet: "`WireTransfers (wire_ref VARCHAR(36) PRIMARY KEY, sender_iban VARCHAR(34), receiver_iban VARCHAR(34), currency VARCHAR(3), amount DECIMAL(14,2), submit_date DATE)` & `OfacClearances (wire_ref VARCHAR(36) PRIMARY KEY, clearance_status VARCHAR(20), screened_at TIMESTAMP, compliance_officer VARCHAR(64))`",
    targetQuery: `SELECT w.currency,\n       COUNT(w.wire_ref) AS cleared_wire_count,\n       SUM(w.amount) AS total_cleared_volume,\n       ROUND(AVG(w.amount), 2) AS avg_cleared_wire_size\nFROM WireTransfers w\nINNER JOIN OfacClearances c\n  ON w.wire_ref = c.wire_ref\nWHERE c.clearance_status = 'CLEARED'\nGROUP BY w.currency\nHAVING SUM(w.amount) >= 1000000.00\nORDER BY total_cleared_volume DESC;`,
    eli5Story: "Cross-referencing international bank wires with the federal security screening log. If a wire was officially cleared, include its money in the currency volume total.",
    commonMistakes: "Grouping by wire_ref instead of the reporting dimension (currency); forgetting HAVING for threshold filtering.",
    learningOutcomes: "Combine multi-column financial aggregations with exact 1-to-1 compliance clearance matching."
  },
  {
    title: "Margin Loan Originations to Pledged Collateral Vault",
    ind: "Fintech",
    diff: "Hard",
    table: "MarginLoans",
    scenario: "Auditing margin trading portfolios by calculating loan-to-value (LTV) ratios across multi-asset collateral pledges.",
    businessObjective: "Join margin accounts to collateral assets and exchange pricing feeds to compute aggregate portfolio loan-to-value (LTV) ratios and flag accounts exceeding the 65% maintenance margin requirement.",
    schemaSnippet: "`MarginLoans (loan_id VARCHAR(32) PRIMARY KEY, trader_id VARCHAR(32), borrowed_usd DECIMAL(12,2), loan_date DATE)` & `CollateralVault (vault_id VARCHAR(32) PRIMARY KEY, trader_id VARCHAR(32), asset_ticker VARCHAR(10), quantity DECIMAL(12,4), current_unit_price DECIMAL(10,2))`",
    targetQuery: `SELECT m.trader_id,\n       m.borrowed_usd,\n       ROUND(SUM(c.quantity * c.current_unit_price), 2) AS total_collateral_value,\n       ROUND((m.borrowed_usd / SUM(c.quantity * c.current_unit_price)) * 100, 2) AS ltv_percentage\nFROM MarginLoans m\nINNER JOIN CollateralVault c\n  ON m.trader_id = c.trader_id\nGROUP BY m.trader_id, m.borrowed_usd\nHAVING (m.borrowed_usd / SUM(c.quantity * c.current_unit_price)) * 100 > 65.00\nORDER BY ltv_percentage DESC;`,
    eli5Story: "Comparing how much money an investor borrowed against the real-time market value of the stocks they put up as collateral. If borrowed money exceeds 65% of collateral value, sound the margin call alarm.",
    commonMistakes: "Computing LTV row-by-row before summing collateral assets, which divides the loan by each individual asset instead of total portfolio collateral.",
    learningOutcomes: "Perform compound mathematical ratios combining driving loan balances with aggregated multi-asset collateral valuations."
  },
  {
    title: "ACH Settlement Batches to Fedwire Routing Directory",
    ind: "Fintech",
    diff: "Easy",
    table: "AchBatches",
    scenario: "Validating outbound overnight Automated Clearing House (ACH) direct deposits against the Federal Reserve Fedwire routing transit directory.",
    businessObjective: "Inner join ACH batches to Fedwire directory on 9-digit ABA routing number to retrieve the official Fed district clearing house name.",
    schemaSnippet: "`AchBatches (batch_id VARCHAR(32) PRIMARY KEY, routing_aba VARCHAR(9), total_amount DECIMAL(14,2), entry_count INT, settlement_date DATE)` & `FedDirectory (aba_number VARCHAR(9) PRIMARY KEY, institution_name VARCHAR(100), fed_district INT, phone VARCHAR(16))`",
    targetQuery: `SELECT a.batch_id, a.routing_aba, f.institution_name, a.total_amount, a.entry_count\nFROM AchBatches a\nINNER JOIN FedDirectory f\n  ON a.routing_aba = f.aba_number\nWHERE a.settlement_date = '2026-09-15'\nORDER BY a.total_amount DESC;`,
    eli5Story: "Making sure every bank routing code on our payment file actually exists in the Federal Reserve directory before sending the wire.",
    commonMistakes: "Storing routing numbers as integers leading to dropped leading zeros (e.g. 021000021 becomes 21000021) and failed join equality.",
    learningOutcomes: "Understand string-based banking transit code matching and exact date filtering."
  },

  // --- SAAS ---
  {
    title: "Subscription Invoices to Account Master Records",
    ind: "SaaS",
    diff: "Easy",
    table: "Invoices",
    scenario: "Joining recurring subscription invoices with account master records to report active ARR per billing geography.",
    businessObjective: "Inner join Invoices to Accounts on account_id to list paid invoices with customer corporate names and billing country.",
    schemaSnippet: "`Invoices (invoice_id VARCHAR(32) PRIMARY KEY, account_id VARCHAR(32), amount_usd DECIMAL(10,2), status VARCHAR(20), paid_at TIMESTAMP)` & `Accounts (account_id VARCHAR(32) PRIMARY KEY, company_name VARCHAR(100), billing_country VARCHAR(2), plan_type VARCHAR(20))`",
    targetQuery: `SELECT i.invoice_id, a.company_name, a.billing_country, i.amount_usd, i.paid_at\nFROM Invoices i\nINNER JOIN Accounts a\n  ON i.account_id = a.account_id\nWHERE i.status = 'PAID'\nORDER BY i.amount_usd DESC;`,
    eli5Story: "Attaching the company profile to each billing receipt so accounting knows which enterprise paid each invoice.",
    commonMistakes: "Omitting the invoice status check, which would include draft and failed payment attempts in revenue reports.",
    learningOutcomes: "Master 1-to-many relationship navigation between enterprise accounts and transaction invoices."
  },
  {
    title: "API Metered Overages to Subscription Quota Tiers",
    ind: "SaaS",
    diff: "Medium",
    table: "MeteredUsage",
    scenario: "Calculating billable overage fees for cloud API customers who exceeded their monthly provisioned request limits.",
    businessObjective: "Join monthly tenant API usage logs with tier entitlements, calculate excess requests above quota, and multiply by per-thousand rate.",
    schemaSnippet: "`MeteredUsage (tenant_id VARCHAR(32) PRIMARY KEY, requests_used BIGINT, billing_month VARCHAR(7))` & `TierEntitlements (tenant_id VARCHAR(32) PRIMARY KEY, tier_name VARCHAR(32), quota_requests BIGINT, rate_per_1k_usd DECIMAL(6,3))`",
    targetQuery: `SELECT m.tenant_id, t.tier_name,\n       m.requests_used,\n       t.quota_requests,\n       (m.requests_used - t.quota_requests) AS overage_requests,\n       ROUND(((m.requests_used - t.quota_requests) / 1000.0) * t.rate_per_1k_usd, 2) AS overage_fee_usd\nFROM MeteredUsage m\nINNER JOIN TierEntitlements t\n  ON m.tenant_id = t.tenant_id\nWHERE m.requests_used > t.quota_requests\nORDER BY overage_fee_usd DESC;`,
    eli5Story: "Checking who used more cloud requests than their plan allowed, subtracting their included quota, and calculating their overage bill.",
    commonMistakes: "Integer division when dividing overage requests by 1000 (e.g. 500 / 1000 = 0 instead of 0.5 in standard SQL).",
    learningOutcomes: "Apply arithmetic operations on joined attributes to generate dynamic billing line items."
  },
  {
    title: "Enterprise SSO SAML Assertions to Identity Provider (IdP) Directory",
    ind: "SaaS",
    diff: "Medium",
    table: "SamlAssertions",
    scenario: "Auditing single sign-on enterprise logins against corporate Okta/Azure identity directories to detect cross-domain login mismatches.",
    businessObjective: "Inner join SAML authentication logs with enterprise workspace configurations to identify successful corporate logins.",
    schemaSnippet: "`SamlAssertions (assertion_id VARCHAR(64) PRIMARY KEY, workspace_id VARCHAR(32), user_email VARCHAR(120), idp_issuer VARCHAR(128), auth_time TIMESTAMP)` & `WorkspaceIdpConfig (workspace_id VARCHAR(32) PRIMARY KEY, org_domain VARCHAR(64), allowed_idp_entity_id VARCHAR(128), sso_enforced BOOLEAN)`",
    targetQuery: `SELECT s.workspace_id, c.org_domain, COUNT(s.assertion_id) AS total_sso_logins,\n       MIN(s.auth_time) AS first_login_today,\n       MAX(s.auth_time) AS last_login_today\nFROM SamlAssertions s\nINNER JOIN WorkspaceIdpConfig c\n  ON s.workspace_id = c.workspace_id\nWHERE s.idp_issuer = c.allowed_idp_entity_id\n  AND c.sso_enforced = TRUE\nGROUP BY s.workspace_id, c.org_domain\nORDER BY total_sso_logins DESC;`,
    eli5Story: "Verifying that every single employee login came through their company's approved Okta portal before recording their login volume.",
    commonMistakes: "Filtering on allowed_idp_entity_id without verifying sso_enforced, leading to partial security reports.",
    learningOutcomes: "Perform compliance aggregation across identity log streams and security configuration tables."
  },
  {
    title: "SLA Incident Tickets to Tier-1 Support Escalation Rotas",
    ind: "SaaS",
    diff: "Hard",
    table: "SupportTickets",
    scenario: "Computing first-response time compliance percentages by matching urgent customer tickets with engineering on-call escalation schedules.",
    businessObjective: "Join incident tickets with on-call shifts, calculate minutes elapsed to first response, and report breach rate per engineering rota.",
    schemaSnippet: "`SupportTickets (ticket_id VARCHAR(32) PRIMARY KEY, rota_id VARCHAR(32), severity VARCHAR(8), created_at TIMESTAMP, first_response_at TIMESTAMP)` & `EscalationRotas (rota_id VARCHAR(32) PRIMARY KEY, team_name VARCHAR(64), target_minutes INT)`",
    targetQuery: `SELECT r.team_name,\n       COUNT(t.ticket_id) AS total_p1_tickets,\n       SUM(CASE WHEN TIMESTAMPDIFF(MINUTE, t.created_at, t.first_response_at) <= r.target_minutes THEN 1 ELSE 0 END) AS met_sla_tickets,\n       ROUND(SUM(CASE WHEN TIMESTAMPDIFF(MINUTE, t.created_at, t.first_response_at) <= r.target_minutes THEN 1 ELSE 0 END) * 100.0 / COUNT(t.ticket_id), 2) AS sla_compliance_pct\nFROM SupportTickets t\nINNER JOIN EscalationRotas r\n  ON t.rota_id = r.rota_id\nWHERE t.severity = 'P1'\nGROUP BY r.team_name\nHAVING COUNT(t.ticket_id) >= 5\nORDER BY sla_compliance_pct ASC;`,
    eli5Story: "Timing how fast engineers replied to emergency tickets compared to their promised contract speed, calculating their SLA compliance score.",
    commonMistakes: "Failing to convert counts to decimals before computing percentages, causing integer division truncations.",
    learningOutcomes: "Combine conditional CASE aggregation with timestamp duration evaluation across joined SLA schedules."
  },

  // --- RETAIL ---
  {
    title: "E-Commerce Order Items to Warehouse Bin Stock",
    ind: "Retail",
    diff: "Easy",
    table: "OrderItems",
    scenario: "Locating warehouse bin pick paths for items ordered in online customer shopping carts.",
    businessObjective: "Join OrderItems to WarehouseBins on sku to display item quantities alongside aisle, bay, and shelf locations for warehouse pickers.",
    schemaSnippet: "`OrderItems (order_item_id VARCHAR(32) PRIMARY KEY, order_id VARCHAR(32), sku VARCHAR(32), quantity INT)` & `WarehouseBins (sku VARCHAR(32) PRIMARY KEY, bin_code VARCHAR(16), aisle_number INT, stock_on_hand INT)`",
    targetQuery: `SELECT oi.order_id, oi.sku, oi.quantity, wb.bin_code, wb.aisle_number\nFROM OrderItems oi\nINNER JOIN WarehouseBins wb\n  ON oi.sku = wb.sku\nWHERE wb.stock_on_hand >= oi.quantity\nORDER BY wb.aisle_number ASC, wb.bin_code ASC;`,
    eli5Story: "Telling the warehouse worker exactly which aisle and shelf to walk to so they can grab the right shoes a customer just bought online.",
    commonMistakes: "Not checking stock_on_hand, creating pick routes for items that are currently out of stock.",
    learningOutcomes: "Optimize physical picking sequence queries using joined shelf location keys."
  },
  {
    title: "Supplier Purchase Orders to Dock Manifests (3-Way Match)",
    ind: "Retail",
    diff: "Medium",
    table: "PurchaseOrders",
    scenario: "Reconciling supplier invoices with physical delivery dock receiving manifests before authorizing cash disbursements.",
    businessObjective: "Join PurchaseOrders to ReceivingDockLogs on po_number to compare ordered quantity vs received quantity and calculate short-shipment quantities.",
    schemaSnippet: "`PurchaseOrders (po_number VARCHAR(32) PRIMARY KEY, supplier_id VARCHAR(32), ordered_qty INT, unit_price DECIMAL(10,2))` & `ReceivingDockLogs (po_number VARCHAR(32) PRIMARY KEY, received_qty INT, damaged_qty INT, received_date DATE)`",
    targetQuery: `SELECT po.po_number, po.supplier_id,\n       po.ordered_qty,\n       dock.received_qty,\n       (po.ordered_qty - dock.received_qty) AS short_shipment_units,\n       ROUND((dock.received_qty - dock.damaged_qty) * po.unit_price, 2) AS payable_amount_usd\nFROM PurchaseOrders po\nINNER JOIN ReceivingDockLogs dock\n  ON po.po_number = dock.po_number\nWHERE po.ordered_qty <> dock.received_qty\nORDER BY short_shipment_units DESC;`,
    eli5Story: "Comparing what we ordered on paper with what actually arrived on the delivery truck to make sure we only pay for undamaged goods.",
    commonMistakes: "Paying the full invoice amount instead of multiplying approved undamaged units by unit price.",
    learningOutcomes: "Execute standard accounting 3-way match reconciliation via multi-column variance queries."
  },
  {
    title: "Customer Loyalty Points Redemptions to Promotional Ledger",
    ind: "Retail",
    diff: "Easy",
    table: "PointsRedemptions",
    scenario: "Connecting customer loyalty reward point burns at point of sale to promotional campaign cost centers.",
    businessObjective: "Inner join PointsRedemptions with PromoCampaigns on campaign_id to audit discount credits given to reward members.",
    schemaSnippet: "`PointsRedemptions (redemption_id VARCHAR(32) PRIMARY KEY, member_id VARCHAR(32), campaign_id VARCHAR(32), points_burned INT, discount_value_usd DECIMAL(8,2))` & `PromoCampaigns (campaign_id VARCHAR(32) PRIMARY KEY, campaign_name VARCHAR(64), budget_cap_usd DECIMAL(12,2), department VARCHAR(32))`",
    targetQuery: `SELECT r.redemption_id, r.member_id, c.campaign_name, r.points_burned, r.discount_value_usd\nFROM PointsRedemptions r\nINNER JOIN PromoCampaigns c\n  ON r.campaign_id = c.campaign_id\nWHERE c.department = 'Apparel'\nORDER BY r.discount_value_usd DESC;`,
    eli5Story: "Checking which marketing campaign sponsored the $10 discount coupon a shopper redeemed at the cash register.",
    commonMistakes: "Joining on member_id instead of campaign_id when reporting on marketing departmental spend.",
    learningOutcomes: "Link operational retail transaction logs with financial marketing attribution tables."
  },
  {
    title: "Point-of-Sale Register Z-Reports to Armored Courier Deposit Slips",
    ind: "Retail",
    diff: "Hard",
    table: "RegisterZReports",
    scenario: "Reconciling daily end-of-shift store cash drawer closing tapes against armored car courier physical deposit pickup manifests.",
    businessObjective: "Inner join register closeout reports to armored car pickup logs on store_id and date to identify cash drawer over/short discrepancies.",
    schemaSnippet: "`RegisterZReports (z_id VARCHAR(32) PRIMARY KEY, store_id VARCHAR(16), report_date DATE, register_cash_total DECIMAL(10,2))` & `CourierPickups (pickup_id VARCHAR(32) PRIMARY KEY, store_id VARCHAR(16), pickup_date DATE, vault_bag_cash DECIMAL(10,2), guard_badge VARCHAR(32))`",
    targetQuery: `SELECT z.store_id, z.report_date,\n       z.register_cash_total,\n       c.vault_bag_cash,\n       (c.vault_bag_cash - z.register_cash_total) AS cash_variance_usd,\n       CASE\n         WHEN c.vault_bag_cash - z.register_cash_total < -20.00 THEN 'SHORT_INVESTIGATION_REQUIRED'\n         WHEN c.vault_bag_cash - z.register_cash_total > 20.00 THEN 'OVER_RECHECK_TILL'\n         ELSE 'BALANCED'\n       END AS audit_status\nFROM RegisterZReports z\nINNER JOIN CourierPickups c\n  ON z.store_id = c.store_id\n AND z.report_date = c.pickup_date\nWHERE ABS(c.vault_bag_cash - z.register_cash_total) > 5.00\nORDER BY ABS(c.vault_bag_cash - z.register_cash_total) DESC;`,
    eli5Story: "Comparing the cash register tape with the armored truck deposit bag count to catch cash drawer theft or cashier counting errors.",
    commonMistakes: "Joining on store_id alone without including pickup_date, producing a massive Cartesian explosion across all historical days.",
    learningOutcomes: "Master composite ON predicates combining foreign key IDs with exact calendar date keys."
  },

  // --- HEALTHCARE ---
  {
    title: "Inpatient Encounters to Attending Physician Registry",
    ind: "Healthcare",
    diff: "Easy",
    table: "InpatientEncounters",
    scenario: "Associating admitted hospital patient stays with the registered attending physician specialty credential.",
    businessObjective: "Join InpatientEncounters to Physicians on doctor_npi to display patient admission dates with primary physician specialty.",
    schemaSnippet: "`InpatientEncounters (encounter_id VARCHAR(32) PRIMARY KEY, patient_id VARCHAR(32), doctor_npi VARCHAR(10), room_number VARCHAR(8), admit_date DATE)` & `Physicians (doctor_npi VARCHAR(10) PRIMARY KEY, full_name VARCHAR(100), specialty VARCHAR(64), department VARCHAR(32))`",
    targetQuery: `SELECT e.encounter_id, e.patient_id, p.full_name AS attending_doctor, p.specialty, e.admit_date\nFROM InpatientEncounters e\nINNER JOIN Physicians p\n  ON e.doctor_npi = p.doctor_npi\nWHERE p.department = 'Cardiology'\nORDER BY e.admit_date DESC;`,
    eli5Story: "Connecting every hospital room stay with the official doctor assigned to the patient, filtered for heart specialists.",
    commonMistakes: "Joining on an unindexed physician name string rather than the National Provider Identifier (NPI).",
    learningOutcomes: "Practice joining on industry-standard healthcare provider identifiers (NPI)."
  },
  {
    title: "Prescription Dispensations to Pharmacy Formulation NDC Master",
    ind: "Healthcare",
    diff: "Medium",
    table: "PrescriptionDispensations",
    scenario: "Matching outpatient drug dispensations with the FDA National Drug Code (NDC) master directory to report dispensed dosage volumes.",
    businessObjective: "Join Dispensations to NdcMaster on ndc_code to calculate total metric units dispensed per therapeutic drug class.",
    schemaSnippet: "`PrescriptionDispensations (rx_id VARCHAR(32) PRIMARY KEY, ndc_code VARCHAR(11), patient_id VARCHAR(32), quantity_dispensed INT, fill_date DATE)` & `NdcMaster (ndc_code VARCHAR(11) PRIMARY KEY, brand_name VARCHAR(64), generic_name VARCHAR(64), therapeutic_class VARCHAR(64), is_controlled BOOLEAN)`",
    targetQuery: `SELECT n.therapeutic_class,\n       COUNT(d.rx_id) AS total_prescriptions_filled,\n       SUM(d.quantity_dispensed) AS total_pills_dispensed,\n       SUM(CASE WHEN n.is_controlled = TRUE THEN 1 ELSE 0 END) AS controlled_substance_count\nFROM PrescriptionDispensations d\nINNER JOIN NdcMaster n\n  ON d.ndc_code = n.ndc_code\nGROUP BY n.therapeutic_class\nORDER BY total_prescriptions_filled DESC;`,
    eli5Story: "Connecting patient pill bottles with the FDA drug catalog to count how many pain medications and antibiotics were handed out.",
    commonMistakes: "Treating 11-digit NDC codes as numbers, which strips leading zeros and breaks string matches.",
    learningOutcomes: "Aggregate clinical drug metrics across standardized pharmaceutical taxonomy classifications."
  },
  {
    title: "Electronic Health Record Vitals to ICU Alert Thresholds",
    ind: "Healthcare",
    diff: "Hard",
    table: "PatientVitals",
    scenario: "Monitoring real-time patient bedside monitor telemetry against clinical early-warning scoring (MEWS) threshold tables.",
    businessObjective: "Join PatientVitals to VitalAlertThresholds on vital_type to detect severe tachycardia or respiratory failure readings in the ICU.",
    schemaSnippet: "`PatientVitals (reading_id VARCHAR(32) PRIMARY KEY, patient_id VARCHAR(32), vital_type VARCHAR(24), recorded_value DECIMAL(6,2), recorded_at TIMESTAMP)` & `VitalAlertThresholds (vital_type VARCHAR(24) PRIMARY KEY, normal_min DECIMAL(6,2), critical_high DECIMAL(6,2), emergency_response_code VARCHAR(16))`",
    targetQuery: `SELECT v.patient_id, v.vital_type, v.recorded_value, t.critical_high,\n       (v.recorded_value - t.critical_high) AS excess_over_critical,\n       t.emergency_response_code, v.recorded_at\nFROM PatientVitals v\nINNER JOIN VitalAlertThresholds t\n  ON v.vital_type = t.vital_type\nWHERE v.recorded_value >= t.critical_high\n  AND v.recorded_at >= NOW() - INTERVAL 1 HOUR\nORDER BY v.recorded_at DESC;`,
    eli5Story: "Checking heart rate and blood pressure numbers from bedside hospital monitors against danger limits to sound the code blue alarm.",
    commonMistakes: "Joining on both vital_type and patient_id when threshold tables are generic guidelines keyed solely by vital_type.",
    learningOutcomes: "Perform threshold violation filtering using joined clinical boundary criteria."
  },
  {
    title: "Medical Insurance Claims to ICD-10 Procedure Guidelines",
    ind: "Healthcare",
    diff: "Medium",
    table: "InsuranceClaims",
    scenario: "Validating medical billing reimbursement submissions against CMS ICD-10 allowable fee schedules.",
    businessObjective: "Join InsuranceClaims with Icd10FeeSchedule on icd_code to compare billed practitioner charges against approved insurance payout caps.",
    schemaSnippet: "`InsuranceClaims (claim_id VARCHAR(32) PRIMARY KEY, icd_code VARCHAR(10), billed_amount DECIMAL(10,2), service_date DATE)` & `Icd10FeeSchedule (icd_code VARCHAR(10) PRIMARY KEY, procedure_desc VARCHAR(128), max_allowable_usd DECIMAL(10,2))`",
    targetQuery: `SELECT c.claim_id, c.icd_code, s.procedure_desc,\n       c.billed_amount,\n       s.max_allowable_usd,\n       ROUND(LEAST(c.billed_amount, s.max_allowable_usd), 2) AS approved_reimbursement,\n       ROUND(GREATEST(0.00, c.billed_amount - s.max_allowable_usd), 2) AS patient_co_responsibility\nFROM InsuranceClaims c\nINNER JOIN Icd10FeeSchedule s\n  ON c.icd_code = s.icd_code\nORDER BY patient_co_responsibility DESC;`,
    eli5Story: "Matching a doctor's bill to the official medical code book to see what portion the health insurance pays and what portion the patient must pay.",
    commonMistakes: "Using simple subtraction without LEAST/GREATEST, resulting in negative copays when billed amount is less than cap.",
    learningOutcomes: "Utilize SQL boundary functions (LEAST/GREATEST) on joined pricing schedules."
  },

  // --- LOGISTICS ---
  {
    title: "Parcel Dispatches to Smart Locker Compartment Registry",
    ind: "Logistics",
    diff: "Easy",
    table: "ParcelDispatches",
    scenario: "Directing delivery van couriers to matching automated parcel locker terminals based on package dimensions.",
    businessObjective: "Join ParcelDispatches to LockerCompartments on compartment_id to print delivery drop-off manifest sheets.",
    schemaSnippet: "`ParcelDispatches (parcel_id VARCHAR(32) PRIMARY KEY, tracking_number VARCHAR(32), compartment_id VARCHAR(32), recipient_phone VARCHAR(16))` & `LockerCompartments (compartment_id VARCHAR(32) PRIMARY KEY, locker_location_name VARCHAR(64), bay_number INT, door_size VARCHAR(12))`",
    targetQuery: `SELECT p.tracking_number, l.locker_location_name, l.bay_number, l.door_size\nFROM ParcelDispatches p\nINNER JOIN LockerCompartments l\n  ON p.compartment_id = l.compartment_id\nORDER BY l.locker_location_name ASC, l.bay_number ASC;`,
    eli5Story: "Telling the delivery driver which electronic locker door in the apartment lobby opens up for each delivery box.",
    commonMistakes: "Failing to order by location and bay number, forcing the courier to walk back and forth inefficiently.",
    learningOutcomes: "Create organized delivery routing manifests with multi-column sorting."
  },
  {
    title: "Ocean Freight Container Bookings to Vessel Stowage Plans",
    ind: "Logistics",
    diff: "Hard",
    table: "ContainerBookings",
    scenario: "Verifying cargo weight distributions on mega-container ships by joining container bookings with vessel bay-row-tier cell slots.",
    businessObjective: "Join ContainerBookings to VesselStowageCells on cell_id to calculate aggregate cargo tonnage per vessel hull cargo hold section.",
    schemaSnippet: "`ContainerBookings (booking_id VARCHAR(32) PRIMARY KEY, cell_id VARCHAR(32), container_teu INT, gross_weight_metric_tons DECIMAL(8,2), hazmat_class VARCHAR(8))` & `VesselStowageCells (cell_id VARCHAR(32) PRIMARY KEY, vessel_imo VARCHAR(10), hold_section VARCHAR(16), max_tonnage DECIMAL(8,2))`",
    targetQuery: `SELECT s.vessel_imo, s.hold_section,\n       COUNT(b.booking_id) AS total_containers_stowed,\n       SUM(b.gross_weight_metric_tons) AS total_hold_weight_tons,\n       s.max_tonnage,\n       ROUND((SUM(b.gross_weight_metric_tons) / s.max_tonnage) * 100.0, 2) AS hold_capacity_pct\nFROM ContainerBookings b\nINNER JOIN VesselStowageCells s\n  ON b.cell_id = s.cell_id\nGROUP BY s.vessel_imo, s.hold_section, s.max_tonnage\nHAVING SUM(b.gross_weight_metric_tons) > s.max_tonnage * 0.90\nORDER BY hold_capacity_pct DESC;`,
    eli5Story: "Making sure container shipping cranes don't put too much heavy steel in one part of the ship so the vessel doesn't capsize at sea.",
    commonMistakes: "Forgetting to include max_tonnage in the GROUP BY clause in engines enforcing strict ANSI SQL.",
    learningOutcomes: "Handle structural engineering constraints and safety capacity calculations via grouped joins."
  },
  {
    title: "Cold-Chain Temperature Sensor Telemetry to Reefer Manifests",
    ind: "Logistics",
    diff: "Medium",
    table: "SensorPings",
    scenario: "Auditing refrigerated pharmaceutical vaccine shipments by matching live IoT temperature pings to transit temperature contracts.",
    businessObjective: "Join SensorPings to ReeferContracts on shipment_id to find any temperature excursions exceeding contractual limits.",
    schemaSnippet: "`SensorPings (ping_id VARCHAR(32) PRIMARY KEY, shipment_id VARCHAR(32), temp_celsius DECIMAL(5,2), ping_time TIMESTAMP)` & `ReeferContracts (shipment_id VARCHAR(32) PRIMARY KEY, client_name VARCHAR(64), min_temp_c DECIMAL(5,2), max_temp_c DECIMAL(5,2))`",
    targetQuery: `SELECT p.shipment_id, c.client_name, p.temp_celsius, c.max_temp_c, p.ping_time\nFROM SensorPings p\nINNER JOIN ReeferContracts c\n  ON p.shipment_id = c.shipment_id\nWHERE p.temp_celsius > c.max_temp_c\n   OR p.temp_celsius < c.min_temp_c\nORDER BY p.ping_time DESC;`,
    eli5Story: "Checking thermometer readings from refrigerated vaccine trucks to flag if the ice cream or medicine got too warm during the drive.",
    commonMistakes: "Using AND instead of OR for bounding condition violations (temperature cannot be both above max AND below min simultaneously).",
    learningOutcomes: "Audit IoT sensor streams against contractual compliance boundary ranges."
  },
  {
    title: "Cross-Dock Pallet Transfers to Automated Guided Vehicle (AGV) Routes",
    ind: "Logistics",
    diff: "Easy",
    table: "PalletTransfers",
    scenario: "Assigning robotic transport vehicles to inbound warehouse dock pallets destined for immediate outbound staging lanes.",
    businessObjective: "Inner join PalletTransfers to AgvFleet on agv_id to track automated pallet movement across distribution facility zones.",
    schemaSnippet: "`PalletTransfers (transfer_id VARCHAR(32) PRIMARY KEY, pallet_rfid VARCHAR(32), agv_id VARCHAR(16), source_dock VARCHAR(8), target_dock VARCHAR(8))` & `AgvFleet (agv_id VARCHAR(16) PRIMARY KEY, battery_pct INT, current_zone VARCHAR(16), status VARCHAR(16))`",
    targetQuery: `SELECT t.transfer_id, t.pallet_rfid, a.agv_id, a.battery_pct, t.source_dock, t.target_dock\nFROM PalletTransfers t\nINNER JOIN AgvFleet a\n  ON t.agv_id = a.agv_id\nWHERE a.battery_pct >= 20\n  AND a.status = 'ACTIVE'\nORDER BY t.transfer_id ASC;`,
    eli5Story: "Matching heavy shipping pallets with the robotic forklift assigned to carry them across the warehouse floor.",
    commonMistakes: "Allowing assignments to robots with critical low battery (< 20%), which strands pallets mid-transit.",
    learningOutcomes: "Implement operational robotics scheduling queries using joined status filters."
  },

  // --- MEDIA ---
  {
    title: "Streaming Audio Plays to PRO Publishing Royalty Catalog",
    ind: "Media",
    diff: "Medium",
    table: "AudioStreams",
    scenario: "Calculating monthly performance rights royalties by joining song stream counts with BMI/ASCAP publisher splits.",
    businessObjective: "Join AudioStreams with SongRoyalties on isrc_code to calculate total royalties payable per song publisher.",
    schemaSnippet: "`AudioStreams (stream_id VARCHAR(32) PRIMARY KEY, isrc_code VARCHAR(12), stream_count BIGINT, country_code VARCHAR(2))` & `SongRoyalties (isrc_code VARCHAR(12) PRIMARY KEY, song_title VARCHAR(100), publisher_name VARCHAR(64), royalty_per_stream_usd DECIMAL(7,5))`",
    targetQuery: `SELECT r.publisher_name,\n       COUNT(DISTINCT s.isrc_code) AS unique_songs_streamed,\n       SUM(s.stream_count) AS total_streams,\n       ROUND(SUM(s.stream_count * r.royalty_per_stream_usd), 2) AS total_royalty_payable_usd\nFROM AudioStreams s\nINNER JOIN SongRoyalties r\n  ON s.isrc_code = r.isrc_code\nGROUP BY r.publisher_name\nHAVING SUM(s.stream_count * r.royalty_per_stream_usd) >= 5000.00\nORDER BY total_royalty_payable_usd DESC;`,
    eli5Story: "Multiplying how many times a song was played on Spotify by the fraction of a cent owed to the music songwriter's publishing company.",
    commonMistakes: "Using COUNT(s.isrc_code) instead of COUNT(DISTINCT s.isrc_code) which confuses stream row count with unique catalog titles.",
    learningOutcomes: "Master fractional unit pricing multiplication and distinct key aggregation in digital media streaming."
  },
  {
    title: "Programmatic Ad Impressions to RTB Win Bid Logs",
    ind: "Media",
    diff: "Hard",
    table: "ServedImpressions",
    scenario: "Reconciling digital ad server impression delivery logs with real-time bidding (RTB) exchange winning bid clearing prices.",
    businessObjective: "Inner join ServedImpressions to RtbBids on auction_id to calculate effective CPM (eCPM) and publisher publisher net margin.",
    schemaSnippet: "`ServedImpressions (impression_id VARCHAR(32) PRIMARY KEY, auction_id VARCHAR(64), ad_unit_id VARCHAR(32), viewable_time_sec INT)` & `RtbBids (auction_id VARCHAR(64) PRIMARY KEY, winning_buyer VARCHAR(64), clearing_cpm_usd DECIMAL(8,4), rev_share_pct DECIMAL(5,2))`",
    targetQuery: `SELECT b.winning_buyer,\n       COUNT(i.impression_id) AS total_impressions_served,\n       ROUND(SUM(b.clearing_cpm_usd / 1000.0), 2) AS gross_ad_spend_usd,\n       ROUND(SUM((b.clearing_cpm_usd / 1000.0) * (b.rev_share_pct / 100.0)), 2) AS publisher_net_earnings_usd\nFROM ServedImpressions i\nINNER JOIN RtbBids b\n  ON i.auction_id = b.auction_id\nWHERE i.viewable_time_sec >= 2\nGROUP BY b.winning_buyer\nORDER BY gross_ad_spend_usd DESC;`,
    eli5Story: "Checking which advertiser won the 0.05-second automated auction to show a banner ad, and calculating how much the website publisher earned.",
    commonMistakes: "Forgetting to divide CPM (Cost Per Mille / Thousand) by 1000 before multiplying by impression volume.",
    learningOutcomes: "Perform programmatic advertising unit conversions (CPM to individual impression dollars) via joined financial feeds."
  },
  {
    title: "Video-on-Demand (VOD) Purchases to Studio Licensing Distribution Terms",
    ind: "Media",
    diff: "Easy",
    table: "VodPurchases",
    scenario: "Attaching movie studio licensing contracts to digital transactional video-on-demand (TVOD) rental transactions.",
    businessObjective: "Join VodPurchases to StudioContracts on title_id to display user rental payments alongside licensing studio rights.",
    schemaSnippet: "`VodPurchases (purchase_id VARCHAR(32) PRIMARY KEY, title_id VARCHAR(32), rental_price_usd DECIMAL(6,2), rented_at TIMESTAMP)` & `StudioContracts (title_id VARCHAR(32) PRIMARY KEY, movie_title VARCHAR(128), studio_name VARCHAR(64), territory VARCHAR(8))`",
    targetQuery: `SELECT v.purchase_id, s.movie_title, s.studio_name, v.rental_price_usd, v.rented_at\nFROM VodPurchases v\nINNER JOIN StudioContracts s\n  ON v.title_id = s.title_id\nWHERE s.territory = 'US'\nORDER BY v.rented_at DESC;`,
    eli5Story: "Matching each movie rental on Apple TV or Amazon Prime to the Hollywood studio that owns the rights to that film.",
    commonMistakes: "Neglecting international licensing territory filters, resulting in mixed territory settlement errors.",
    learningOutcomes: "Link content sales registers with intellectual property licensing metadata."
  },
  {
    title: "Podcast Episode Sponsorship Reads to Dynamic Ad Insertion Markers",
    ind: "Media",
    diff: "Medium",
    table: "AdInsertionLogs",
    scenario: "Verifying sponsor commercial audio playback within episodic podcast streams against contracted minimum audio listen times.",
    businessObjective: "Join AdInsertionLogs with SponsorAgreements on sponsor_id to audit verified ad completions.",
    schemaSnippet: "`AdInsertionLogs (log_id VARCHAR(32) PRIMARY KEY, episode_id VARCHAR(32), sponsor_id VARCHAR(32), seconds_streamed INT)` & `SponsorAgreements (sponsor_id VARCHAR(32) PRIMARY KEY, sponsor_name VARCHAR(64), required_duration_sec INT, cost_per_spot_usd DECIMAL(8,2))`",
    targetQuery: `SELECT a.sponsor_name,\n       COUNT(l.log_id) AS total_spots_played,\n       SUM(CASE WHEN l.seconds_streamed >= a.required_duration_sec THEN 1 ELSE 0 END) AS qualified_completions,\n       ROUND(SUM(CASE WHEN l.seconds_streamed >= a.required_duration_sec THEN a.cost_per_spot_usd ELSE 0.00 END), 2) AS total_billable_usd\nFROM AdInsertionLogs l\nINNER JOIN SponsorAgreements a\n  ON l.sponsor_id = a.sponsor_id\nGROUP BY a.sponsor_name\nORDER BY total_billable_usd DESC;`,
    eli5Story: "Checking if a podcast listener actually listened to the entire 30-second sponsor shoutout before charging the sponsor for the commercial.",
    commonMistakes: "Billing sponsors for aborted audio plays where listener skipped or paused before the required duration.",
    learningOutcomes: "Combine duration threshold logic with billable conditional aggregation on joined sponsor schedules."
  },

  // --- SECURITY ---
  {
    title: "Zero-Trust Access Gateway Requests to Device Health Scores",
    ind: "Security",
    diff: "Easy",
    table: "AccessRequests",
    scenario: "Enforcing zero-trust endpoint network access by joining inbound employee login attempts with real-time MDM security health postures.",
    businessObjective: "Join AccessRequests to DeviceHealth on device_uuid to grant access only to managed laptops with encrypted hard drives.",
    schemaSnippet: "`AccessRequests (request_id VARCHAR(32) PRIMARY KEY, user_id VARCHAR(32), device_uuid VARCHAR(64), requested_resource VARCHAR(64))` & `DeviceHealth (device_uuid VARCHAR(64) PRIMARY KEY, os_version VARCHAR(32), is_disk_encrypted BOOLEAN, edr_active BOOLEAN)`",
    targetQuery: `SELECT r.request_id, r.user_id, r.requested_resource, d.os_version\nFROM AccessRequests r\nINNER JOIN DeviceHealth d\n  ON r.device_uuid = d.device_uuid\nWHERE d.is_disk_encrypted = TRUE\n  AND d.edr_active = TRUE\nORDER BY r.request_id ASC;`,
    eli5Story: "Only allowing an employee onto the corporate VPN if their laptop's security scan shows full disk encryption and active anti-virus.",
    commonMistakes: "Using OR instead of AND between security conditions, allowing unencrypted laptops through if anti-virus was active.",
    learningOutcomes: "Enforce zero-trust authorization criteria via joined device telemetry attributes."
  },
  {
    title: "Next-Gen Firewall Block Events to Threat Intelligence Indicators",
    ind: "Security",
    diff: "Medium",
    table: "FirewallBlocks",
    scenario: "Correlating perimeter firewall packet drop logs with external threat intelligence feeds to identify coordinated botnet attacks.",
    businessObjective: "Join FirewallBlocks with ThreatIntelFeeds on src_ip to group dropped connection events by threat actor syndicate.",
    schemaSnippet: "`FirewallBlocks (block_id VARCHAR(32) PRIMARY KEY, src_ip VARCHAR(45), dest_port INT, packet_count INT, block_time TIMESTAMP)` & `ThreatIntelFeeds (ip_address VARCHAR(45) PRIMARY KEY, actor_name VARCHAR(64), threat_category VARCHAR(32), confidence_score INT)`",
    targetQuery: `SELECT t.actor_name, t.threat_category,\n       COUNT(f.block_id) AS total_probes_blocked,\n       SUM(f.packet_count) AS total_malicious_packets,\n       MAX(f.block_time) AS most_recent_probe\nFROM FirewallBlocks f\nINNER JOIN ThreatIntelFeeds t\n  ON f.src_ip = t.ip_address\nWHERE t.confidence_score >= 80\nGROUP BY t.actor_name, t.threat_category\nORDER BY total_probes_blocked DESC;`,
    eli5Story: "Matching blocked IP addresses against the FBI/Interpol cyber-crime database to see which hacker syndicate is attacking our servers.",
    commonMistakes: "Failing to filter on threat confidence score, alerting security analysts to false positives.",
    learningOutcomes: "Correlate high-volume network telemetry with cyber threat intelligence metadata."
  },
  {
    title: "Cloud IAM Role Assumes to Multi-Factor Auth Sessions",
    ind: "Security",
    diff: "Hard",
    table: "RoleAssumes",
    scenario: "Validating production AWS/GCP administrative cloud role assumptions against hardware token multi-factor authentication (MFA) challenges.",
    businessObjective: "Join CloudTrail role assume logs with MFA challenge vaults to identify administrative privilege escalations that bypassed MFA.",
    schemaSnippet: "`RoleAssumes (event_id VARCHAR(32) PRIMARY KEY, role_arn VARCHAR(128), session_token VARCHAR(64), assumed_at TIMESTAMP)` & `MfaSessions (session_token VARCHAR(64) PRIMARY KEY, user_arn VARCHAR(128), mfa_auth_type VARCHAR(20), mfa_verified_at TIMESTAMP)`",
    targetQuery: `SELECT r.event_id, r.role_arn, m.user_arn, m.mfa_auth_type,\n       TIMESTAMPDIFF(SECOND, m.mfa_verified_at, r.assumed_at) AS seconds_since_mfa\nFROM RoleAssumes r\nINNER JOIN MfaSessions m\n  ON r.session_token = m.session_token\nWHERE r.role_arn LIKE '%Administrator%'\n  AND TIMESTAMPDIFF(SECOND, m.mfa_verified_at, r.assumed_at) > 3600\nORDER BY seconds_since_mfa DESC;`,
    eli5Story: "Checking if someone who logged into the main company cloud with super-admin powers used a hardware security key within the last hour.",
    commonMistakes: "Not checking the time gap between MFA verification and role assumption, allowing stale reused tokens.",
    learningOutcomes: "Detect privilege escalation security risks using timestamp differences across joined session logs."
  },
  {
    title: "Vulnerability Scanner CVE Detections to Host Asset Registry",
    ind: "Security",
    diff: "Medium",
    table: "VulnerabilityDetections",
    scenario: "Matching automated security scanner CVE findings with server asset directories to prioritize patch deployments on internet-facing hosts.",
    businessObjective: "Join VulnerabilityDetections to ServerAssets on asset_tag to calculate critical vulnerability exposure counts per environment tier.",
    schemaSnippet: "`VulnerabilityDetections (finding_id VARCHAR(32) PRIMARY KEY, asset_tag VARCHAR(32), cve_id VARCHAR(16), cvss_score DECIMAL(3,1))` & `ServerAssets (asset_tag VARCHAR(32) PRIMARY KEY, hostname VARCHAR(64), env_tier VARCHAR(16), is_public_facing BOOLEAN)`",
    targetQuery: `SELECT a.env_tier,\n       COUNT(v.finding_id) AS total_cve_count,\n       SUM(CASE WHEN v.cvss_score >= 9.0 THEN 1 ELSE 0 END) AS critical_severity_cves,\n       ROUND(AVG(v.cvss_score), 2) AS avg_host_cvss_score\nFROM VulnerabilityDetections v\nINNER JOIN ServerAssets a\n  ON v.asset_tag = a.asset_tag\nWHERE a.is_public_facing = TRUE\nGROUP BY a.env_tier\nORDER BY critical_severity_cves DESC;`,
    eli5Story: "Checking which of our public-facing internet websites have dangerous software bugs that hackers could exploit.",
    commonMistakes: "Treating internal development servers with the same priority as public internet-facing production boxes.",
    learningOutcomes: "Generate asset risk summaries by combining vulnerability severity metrics with environment infrastructure tags."
  },

  // --- HARDWARE ---
  {
    title: "Semiconductor Photolithography Stepper Runs to Silicon Wafer Lots",
    ind: "Hardware",
    diff: "Medium",
    table: "StepperRuns",
    scenario: "Tracking semiconductor cleanroom fabrication equipment runs against raw silicon wafer batches to detect machine focus calibration drift.",
    businessObjective: "Join StepperRuns to WaferLots on lot_id to compute average optical overlay error per fabrication exposure tool.",
    schemaSnippet: "`StepperRuns (run_id VARCHAR(32) PRIMARY KEY, lot_id VARCHAR(32), tool_id VARCHAR(16), overlay_error_nm DECIMAL(6,2), run_timestamp TIMESTAMP)` & `WaferLots (lot_id VARCHAR(32) PRIMARY KEY, substrate_type VARCHAR(32), wafer_count INT, fab_recipe VARCHAR(32))`",
    targetQuery: `SELECT s.tool_id,\n       COUNT(s.run_id) AS total_lots_processed,\n       ROUND(AVG(s.overlay_error_nm), 2) AS avg_overlay_error_nm,\n       MAX(s.overlay_error_nm) AS max_overlay_error_nm\nFROM StepperRuns s\nINNER JOIN WaferLots w\n  ON s.lot_id = w.lot_id\nWHERE w.fab_recipe = 'N3_EUV_LOGIC'\nGROUP BY s.tool_id\nHAVING AVG(s.overlay_error_nm) > 2.50\nORDER BY avg_overlay_error_nm DESC;`,
    eli5Story: "Checking microchip manufacturing laser machines to see which tool is misaligned by more than 2.5 nanometers while printing 3nm computer chips.",
    commonMistakes: "Averaging error values without filtering for a consistent fabrication recipe, mixing mature and experimental processes.",
    learningOutcomes: "Perform precision engineering quality control aggregations across equipment runs and manufacturing lots."
  },
  {
    title: "Surface Mount Technology (SMT) Pick-and-Place Feeder to Reel Barcodes",
    ind: "Hardware",
    diff: "Easy",
    table: "FeederSetup",
    scenario: "Verifying that electronics factory automated circuit board assembly machines have the correct capacitor and resistor reels loaded.",
    businessObjective: "Inner join FeederSetup to ComponentReels on reel_barcode to confirm part numbers match the circuit board Bill of Materials (BOM).",
    schemaSnippet: "`FeederSetup (slot_number INT, machine_id VARCHAR(16), reel_barcode VARCHAR(32), PRIMARY KEY(machine_id, slot_number))` & `ComponentReels (reel_barcode VARCHAR(32) PRIMARY KEY, manufacturer_part_no VARCHAR(48), value_spec VARCHAR(32), quantity_remaining INT)`",
    targetQuery: `SELECT f.machine_id, f.slot_number, c.manufacturer_part_no, c.value_spec, c.quantity_remaining\nFROM FeederSetup f\nINNER JOIN ComponentReels c\n  ON f.reel_barcode = c.reel_barcode\nWHERE c.quantity_remaining > 500\nORDER BY f.machine_id ASC, f.slot_number ASC;`,
    eli5Story: "Making sure the robot building computer motherboards has the right micro-chips loaded into slot 1 and slot 2 before turning on the assembly line.",
    commonMistakes: "Using a single-column primary key on FeederSetup when slot numbers repeat across different assembly machines.",
    learningOutcomes: "Join composite-keyed machine setup configurations with inventory tracking components."
  },
  {
    title: "Finished Device Burn-In Chamber Telemetry to Quality Acceptance Gates",
    ind: "Hardware",
    diff: "Hard",
    table: "BurnInReadings",
    scenario: "Testing newly assembled laptops and gaming consoles in thermal stress chambers to evaluate infant mortality failure rates.",
    businessObjective: "Join BurnInReadings to DeviceAcceptanceCriteria on model_code to flag units that exceeded allowable junction temperature limits during 48-hour burn-in.",
    schemaSnippet: "`BurnInReadings (reading_id VARCHAR(32) PRIMARY KEY, serial_number VARCHAR(32), model_code VARCHAR(16), max_temp_celsius DECIMAL(5,2), hours_tested INT)` & `DeviceAcceptanceCriteria (model_code VARCHAR(16) PRIMARY KEY, max_allowed_temp DECIMAL(5,2), min_burn_in_hours INT)`",
    targetQuery: `SELECT b.serial_number, b.model_code, b.max_temp_celsius, a.max_allowed_temp,\n       (b.max_temp_celsius - a.max_allowed_temp) AS thermal_overage_celsius\nFROM BurnInReadings b\nINNER JOIN DeviceAcceptanceCriteria a\n  ON b.model_code = a.model_code\nWHERE b.hours_tested >= a.min_burn_in_hours\n  AND b.max_temp_celsius > a.max_allowed_temp\nORDER BY thermal_overage_celsius DESC;`,
    eli5Story: "Running gaming laptops at 100% power in a hot test room for 48 hours to weed out the ones that overheat before shipping to stores.",
    commonMistakes: "Flagging overheating on units that had not yet reached min_burn_in_hours, misinterpreting warm-up anomalies.",
    learningOutcomes: "Evaluate environmental stress testing data against quality acceptance criteria."
  },
  {
    title: "Motherboard Flying Probe In-Circuit Tests to Engineering CAD Revisions",
    ind: "Hardware",
    diff: "Easy",
    table: "ProbeTestLogs",
    scenario: "Matching flying probe electrical continuity test points on printed circuit boards with engineering revision netlists.",
    businessObjective: "Join ProbeTestLogs to CadNetlists on test_point_id to identify electrical short circuits and open traces.",
    schemaSnippet: "`ProbeTestLogs (test_id VARCHAR(32) PRIMARY KEY, pcb_serial VARCHAR(32), test_point_id VARCHAR(16), measured_resistance_ohms DECIMAL(8,3))` & `CadNetlists (test_point_id VARCHAR(16) PRIMARY KEY, net_name VARCHAR(32), expected_resistance_ohms DECIMAL(8,3))`",
    targetQuery: `SELECT p.pcb_serial, p.test_point_id, c.net_name, p.measured_resistance_ohms, c.expected_resistance_ohms\nFROM ProbeTestLogs p\nINNER JOIN CadNetlists c\n  ON p.test_point_id = c.test_point_id\nWHERE ABS(p.measured_resistance_ohms - c.expected_resistance_ohms) > 1.000\nORDER BY p.pcb_serial ASC;`,
    eli5Story: "Using tiny robotic electrical needles to touch circuit boards and verify electricity flows through the exact wires designed in CAD.",
    commonMistakes: "Checking exact equality on resistance instead of using an allowable delta or tolerance threshold.",
    learningOutcomes: "Perform automated circuit board continuity test validation using engineering netlist joins."
  },

  // --- HR ---
  {
    title: "Payroll Gross Pay to Department Cost Center Allocations",
    ind: "HR",
    diff: "Easy",
    table: "PayrollRuns",
    scenario: "Allocating bi-weekly employee salary, tax, and bonus expenses to corporate cost centers for general ledger posting.",
    businessObjective: "Join PayrollRuns to CostCenters on cost_center_id to report gross payroll expenditure per business division.",
    schemaSnippet: "`PayrollRuns (payroll_id VARCHAR(32) PRIMARY KEY, employee_id VARCHAR(32), cost_center_id VARCHAR(16), gross_pay_usd DECIMAL(10,2), pay_date DATE)` & `CostCenters (cost_center_id VARCHAR(16) PRIMARY KEY, dept_name VARCHAR(64), division VARCHAR(32))`",
    targetQuery: `SELECT c.division, c.dept_name,\n       COUNT(p.employee_id) AS paid_headcount,\n       SUM(p.gross_pay_usd) AS total_payroll_usd,\n       ROUND(AVG(p.gross_pay_usd), 2) AS avg_gross_salary_usd\nFROM PayrollRuns p\nINNER JOIN CostCenters c\n  ON p.cost_center_id = c.cost_center_id\nWHERE p.pay_date = '2026-09-30'\nGROUP BY c.division, c.dept_name\nORDER BY total_payroll_usd DESC;`,
    eli5Story: "Summing up how much money was paid to workers in each company department on payday for financial accounting.",
    commonMistakes: "Omitting the pay_date filter, which sums payroll across all pay periods in company history.",
    learningOutcomes: "Roll up corporate payroll expenses to departmental organizational hierarchies."
  },
  {
    title: "Employee FSA Claims to Approved IRS Contribution Limits",
    ind: "HR",
    diff: "Medium",
    table: "FsaClaims",
    scenario: "Auditing flexible spending healthcare account reimbursement requests against annual IRS contribution ceilings.",
    businessObjective: "Join FsaClaims to FsaEnrollments on employee_id to ensure cumulative reimbursed claims do not exceed election amounts.",
    schemaSnippet: "`FsaClaims (claim_id VARCHAR(32) PRIMARY KEY, employee_id VARCHAR(32), claim_amount DECIMAL(8,2), claim_status VARCHAR(16))` & `FsaEnrollments (employee_id VARCHAR(32) PRIMARY KEY, annual_elected_usd DECIMAL(8,2), plan_year INT)`",
    targetQuery: `SELECT e.employee_id, e.annual_elected_usd,\n       SUM(c.claim_amount) AS total_claimed_usd,\n       (e.annual_elected_usd - SUM(c.claim_amount)) AS remaining_fsa_funds\nFROM FsaClaims c\nINNER JOIN FsaEnrollments e\n  ON c.employee_id = e.employee_id\nWHERE c.claim_status = 'APPROVED'\n  AND e.plan_year = 2026\nGROUP BY e.employee_id, e.annual_elected_usd\nHAVING SUM(c.claim_amount) > e.annual_elected_usd\nORDER BY remaining_fsa_funds ASC;`,
    eli5Story: "Checking if an employee asked for more tax-free health money reimbursement than they elected to put in their health savings pot this year.",
    commonMistakes: "Summing claims without checking claim_status = 'APPROVED', accidentally including rejected or pending claims.",
    learningOutcomes: "Identify financial compliance overages using grouped aggregations on joined election limits."
  },
  {
    title: "Annual Equity RSU Vesting Tranches to Stock Administration Vault",
    ind: "HR",
    diff: "Hard",
    table: "EquityGrants",
    scenario: "Reconciling quarterly restricted stock unit (RSU) vesting schedules with transfer agent share distribution pools.",
    businessObjective: "Join EquityGrants to VestingSchedules on grant_id to calculate upcoming quarterly shares vesting and required tax withholdings.",
    schemaSnippet: "`EquityGrants (grant_id VARCHAR(32) PRIMARY KEY, employee_id VARCHAR(32), total_shares_granted INT, grant_date DATE)` & `VestingSchedules (tranche_id VARCHAR(32) PRIMARY KEY, grant_id VARCHAR(32), vest_date DATE, shares_to_vest INT, is_released BOOLEAN)`",
    targetQuery: `SELECT g.employee_id, g.grant_id,\n       SUM(v.shares_to_vest) AS quarterly_vesting_shares,\n       ROUND(SUM(v.shares_to_vest) * 142.50, 2) AS estimated_taxable_value_usd,\n       ROUND(SUM(v.shares_to_vest) * 142.50 * 0.37, 2) AS statutory_tax_withholding_usd\nFROM EquityGrants g\nINNER JOIN VestingSchedules v\n  ON g.grant_id = v.grant_id\nWHERE v.vest_date BETWEEN '2026-10-01' AND '2026-12-31'\n  AND v.is_released = FALSE\nGROUP BY g.employee_id, g.grant_id\nORDER BY quarterly_vesting_shares DESC;`,
    eli5Story: "Calculating how many company shares unlock for employees this quarter and how much cash must be withheld for the IRS.",
    commonMistakes: "Forgetting to filter out already released tranches (is_released = FALSE), re-vesting historical shares.",
    learningOutcomes: "Project equity compensation liabilities and tax withholdings over upcoming quarterly calendar windows."
  },
  {
    title: "New Hire Background Checks to Form I-9 Employment Verification",
    ind: "HR",
    diff: "Easy",
    table: "BackgroundChecks",
    scenario: "Ensuring newly hired workers complete both third-party criminal background clearance and federal Form I-9 legal right-to-work verification.",
    businessObjective: "Inner join BackgroundChecks to FormI9Records on candidate_id to output cleared employees ready for Day-1 payroll onboarding.",
    schemaSnippet: "`BackgroundChecks (check_id VARCHAR(32) PRIMARY KEY, candidate_id VARCHAR(32), background_status VARCHAR(16), cleared_date DATE)` & `FormI9Records (i9_id VARCHAR(32) PRIMARY KEY, candidate_id VARCHAR(32), doc_verification_status VARCHAR(16), e_verify_case_no VARCHAR(20))`",
    targetQuery: `SELECT b.candidate_id, b.cleared_date, i.e_verify_case_no\nFROM BackgroundChecks b\nINNER JOIN FormI9Records i\n  ON b.candidate_id = i.candidate_id\nWHERE b.background_status = 'CLEARED'\n  AND i.doc_verification_status = 'VERIFIED'\nORDER BY b.cleared_date DESC;`,
    eli5Story: "Checking that a new hire passed their background check AND showed their passport/work visa before letting them start on day one.",
    commonMistakes: "Using a LEFT JOIN which would allow employees with missing I-9 verifications to appear on the cleared Day-1 roster.",
    learningOutcomes: "Filter multi-table onboarding compliance requirements using strict intersection joins."
  },

  // --- PLATFORMS ---
  {
    title: "Ride-Share Completed Trips to Driver Surge Earnings Ledger",
    ind: "Platforms",
    diff: "Easy",
    table: "RideTrips",
    scenario: "Joining completed passenger taxi trips with driver earnings registers to audit base fares and dynamic surge bonus payouts.",
    businessObjective: "Join RideTrips to DriverEarnings on trip_id to report driver earnings breakdown per city market.",
    schemaSnippet: "`RideTrips (trip_id VARCHAR(32) PRIMARY KEY, driver_id VARCHAR(32), city_code VARCHAR(8), trip_miles DECIMAL(6,2))` & `DriverEarnings (trip_id VARCHAR(32) PRIMARY KEY, base_fare_usd DECIMAL(8,2), surge_multiplier DECIMAL(4,2), tip_usd DECIMAL(6,2))`",
    targetQuery: `SELECT r.city_code,\n       COUNT(r.trip_id) AS total_trips,\n       ROUND(AVG(e.base_fare_usd * e.surge_multiplier + e.tip_usd), 2) AS avg_driver_payout_usd,\n       ROUND(SUM(e.base_fare_usd * (e.surge_multiplier - 1.0)), 2) AS total_surge_subsidies_usd\nFROM RideTrips r\nINNER JOIN DriverEarnings e\n  ON r.trip_id = e.trip_id\nGROUP BY r.city_code\nORDER BY total_surge_subsidies_usd DESC;`,
    eli5Story: "Calculating how much extra cash drivers earned during heavy rain or rush hour surge pricing across different cities.",
    commonMistakes: "Adding tips before multiplying by surge multiplier; surge only applies to the base fare.",
    learningOutcomes: "Calculate platform marketplace earnings using complex multi-variable payout formulas."
  },
  {
    title: "Peer-to-Peer Marketplace Orders to Escrow Release Authorizations",
    ind: "Platforms",
    diff: "Medium",
    table: "MarketplaceOrders",
    scenario: "Releasing buyer funds held in escrow to third-party seller bank accounts once buyer confirms receipt of merchandise.",
    businessObjective: "Join MarketplaceOrders to EscrowHolds on order_id to process cleared payouts minus platform marketplace commission fees.",
    schemaSnippet: "`MarketplaceOrders (order_id VARCHAR(32) PRIMARY KEY, seller_id VARCHAR(32), item_amount_usd DECIMAL(10,2), status VARCHAR(20))` & `EscrowHolds (order_id VARCHAR(32) PRIMARY KEY, hold_id VARCHAR(32), buyer_confirmed_at TIMESTAMP, release_authorized BOOLEAN)`",
    targetQuery: `SELECT o.seller_id,\n       COUNT(o.order_id) AS released_orders_count,\n       SUM(o.item_amount_usd) AS gross_sales_usd,\n       ROUND(SUM(o.item_amount_usd * 0.12), 2) AS platform_take_rate_12pct,\n       ROUND(SUM(o.item_amount_usd * 0.88), 2) AS net_seller_disbursement_usd\nFROM MarketplaceOrders o\nINNER JOIN EscrowHolds h\n  ON o.order_id = h.order_id\nWHERE o.status = 'DELIVERED'\n  AND h.release_authorized = TRUE\nGROUP BY o.seller_id\nORDER BY net_seller_disbursement_usd DESC;`,
    eli5Story: "Releasing the buyer's money to the seller once the package arrives in good condition, keeping our 12% marketplace fee.",
    commonMistakes: "Releasing funds when status is 'SHIPPED' instead of 'DELIVERED', violating escrow security terms.",
    learningOutcomes: "Model two-sided marketplace take-rates and seller escrow disbursements."
  },
  {
    title: "Food Delivery Courier Handoffs to Ghost Kitchen Workstations",
    ind: "Platforms",
    diff: "Hard",
    table: "CourierPickups",
    scenario: "Measuring kitchen prep lag time by joining kitchen ticket bump bar timestamps with delivery courier bag scan timestamps.",
    businessObjective: "Join CourierPickups to KitchenTickets on order_id to compute kitchen food-ready wait time and identify bottleneck restaurant brands.",
    schemaSnippet: "`CourierPickups (pickup_id VARCHAR(32) PRIMARY KEY, order_id VARCHAR(32), courier_id VARCHAR(32), courier_arrived_at TIMESTAMP, order_scanned_at TIMESTAMP)` & `KitchenTickets (order_id VARCHAR(32) PRIMARY KEY, brand_name VARCHAR(64), kitchen_ready_at TIMESTAMP)`",
    targetQuery: `SELECT k.brand_name,\n       COUNT(c.pickup_id) AS total_orders_fulfilled,\n       ROUND(AVG(TIMESTAMPDIFF(MINUTE, c.courier_arrived_at, c.order_scanned_at)), 1) AS avg_courier_wait_min,\n       SUM(CASE WHEN TIMESTAMPDIFF(MINUTE, c.courier_arrived_at, c.order_scanned_at) > 10 THEN 1 ELSE 0 END) AS excessive_wait_incidents\nFROM CourierPickups c\nINNER JOIN KitchenTickets k\n  ON c.order_id = k.order_id\nGROUP BY k.brand_name\nHAVING COUNT(c.pickup_id) >= 20\nORDER BY avg_courier_wait_min DESC;`,
    eli5Story: "Measuring how many minutes delivery drivers had to stand outside in the cold waiting for the restaurant kitchen to finish bagging the burgers.",
    commonMistakes: "Inverting TIMESTAMPDIFF arguments, leading to negative wait durations.",
    learningOutcomes: "Measure multi-party logistics handoff friction across shared commercial platforms."
  },
  {
    title: "App Store In-App Purchases to Mobile Developer Revenue Wallets",
    ind: "Platforms",
    diff: "Easy",
    table: "InAppPurchases",
    scenario: "Reconciling digital in-app microtransactions with registered mobile app developer developer payout accounts.",
    businessObjective: "Inner join InAppPurchases to DeveloperAccounts on app_id to calculate 85/15 revenue share splits for qualified small businesses.",
    schemaSnippet: "`InAppPurchases (purchase_id VARCHAR(32) PRIMARY KEY, app_id VARCHAR(32), gross_amount_usd DECIMAL(8,2), transaction_time TIMESTAMP)` & `DeveloperAccounts (app_id VARCHAR(32) PRIMARY KEY, developer_name VARCHAR(100), tier_program VARCHAR(20))`",
    targetQuery: `SELECT d.developer_name,\n       COUNT(p.purchase_id) AS total_purchases,\n       SUM(p.gross_amount_usd) AS gross_sales_usd,\n       ROUND(SUM(p.gross_amount_usd * 0.85), 2) AS developer_net_85pct_usd,\n       ROUND(SUM(p.gross_amount_usd * 0.15), 2) AS app_store_commission_15pct_usd\nFROM InAppPurchases p\nINNER JOIN DeveloperAccounts d\n  ON p.app_id = d.app_id\nWHERE d.tier_program = 'SMALL_BUSINESS_15'\nGROUP BY d.developer_name\nORDER BY gross_sales_usd DESC;`,
    eli5Story: "Splitting in-app game coin purchases: 85% goes directly to the indie game developer, and 15% stays with the app store.",
    commonMistakes: "Applying the 30% enterprise commission rate to developers who enrolled in the 15% small business program.",
    learningOutcomes: "Calculate tiered digital ecosystem commission distributions using joined developer tier metadata."
  }
];
