// =============================================================================
// PART 2: LEFT JOIN & ZERO-PRESERVATION (40 DISTINCT CASES: 13 Easy, 14 Medium, 13 Hard)
// Preserving 100% of Driving Table + COALESCE Default Handling Across 10 Industries
// =============================================================================

module.exports = [
  // --- FINTECH ---
  {
    title: "Checking Accounts to Monthly Wire Volumes (Zero-Activity Account Retention)",
    ind: "Fintech",
    diff: "Easy",
    table: "CheckingAccounts",
    scenario: "Listing all retail checking accounts on the monthly portfolio review, preserving accounts that had zero outbound wires during the statement period.",
    businessObjective: "Left join CheckingAccounts to MonthlyWires on account_id, replacing null wire totals with $0.00 using COALESCE.",
    schemaSnippet: "`CheckingAccounts (account_id VARCHAR(32) PRIMARY KEY, holder_name VARCHAR(100), opened_date DATE, current_balance DECIMAL(12,2))` & `MonthlyWires (wire_id VARCHAR(32) PRIMARY KEY, account_id VARCHAR(32), wire_amount DECIMAL(10,2))`",
    targetQuery: `SELECT a.account_id, a.holder_name, a.current_balance,\n       COALESCE(SUM(w.wire_amount), 0.00) AS total_wire_spend_usd\nFROM CheckingAccounts a\nLEFT JOIN MonthlyWires w\n  ON a.account_id = w.account_id\nGROUP BY a.account_id, a.holder_name, a.current_balance\nORDER BY total_wire_spend_usd ASC;`,
    eli5Story: "We want a list of every single bank account. If someone sent zero wires this month, they must still show up with $0 wire spend instead of disappearing.",
    commonMistakes: "Using an INNER JOIN which silently discards every customer who didn't send a wire.",
    learningOutcomes: "Master basic driving table preservation and COALESCE zero-padding on aggregate functions."
  },
  {
    title: "Active Credit Cards to Disputed Chargebacks (Flagging Zero-Dispute Clean Cards)",
    ind: "Fintech",
    diff: "Medium",
    table: "CreditCards",
    scenario: "Computing dispute rate percentages across cardholder portfolios, ensuring accounts with zero fraud disputes are flagged as pristine clean.",
    businessObjective: "Left join CreditCards to Chargebacks on card_number, count disputes, and conditionally label cards as ZERO_DISPUTES or ACTIVE_DISPUTES.",
    schemaSnippet: "`CreditCards (card_number VARCHAR(16) PRIMARY KEY, cardholder_id VARCHAR(32), credit_limit DECIMAL(10,2), issue_year INT)` & `Chargebacks (dispute_id VARCHAR(32) PRIMARY KEY, card_number VARCHAR(16), disputed_usd DECIMAL(10,2), status VARCHAR(16))`",
    targetQuery: `SELECT c.card_number, c.cardholder_id,\n       COUNT(b.dispute_id) AS total_disputes,\n       COALESCE(SUM(b.disputed_usd), 0.00) AS total_disputed_usd,\n       CASE\n         WHEN COUNT(b.dispute_id) = 0 THEN 'PRISTINE_ZERO_DISPUTES'\n         ELSE 'INVESTIGATION_FLAGGED'\n       END AS card_risk_status\nFROM CreditCards c\nLEFT JOIN Chargebacks b\n  ON c.card_number = b.card_number\nWHERE c.issue_year >= 2024\nGROUP BY c.card_number, c.cardholder_id\nORDER BY total_disputed_usd DESC;`,
    eli5Story: "Checking who has filed credit card fraud complaints. If a card has zero complaints, praise them as pristine rather than dropping them from the report.",
    commonMistakes: "Using COUNT(*) instead of COUNT(b.dispute_id), which mistakenly counts 1 row for cards with zero chargebacks due to the NULL-padded row.",
    learningOutcomes: "Understand the critical difference between COUNT(*) and COUNT(column) when aggregating outer joins."
  },
  {
    title: "Wealth Management Clients to Quarterly Advisory Fees (Fee-Exempt VIP Roster)",
    ind: "Fintech",
    diff: "Hard",
    table: "WealthClients",
    scenario: "Auditing quarterly fee debits across private banking ultra-high-net-worth accounts to identify foundation or non-profit fee-exempt trusts.",
    businessObjective: "Left join WealthClients to AdvisoryFeeDebits on client_id to calculate net portfolio yields, preserving clients paying $0 in fees.",
    schemaSnippet: "`WealthClients (client_id VARCHAR(32) PRIMARY KEY, portfolio_name VARCHAR(100), aum_usd DECIMAL(14,2), tier_level VARCHAR(16))` & `AdvisoryFeeDebits (debit_id VARCHAR(32) PRIMARY KEY, client_id VARCHAR(32), fee_amount_usd DECIMAL(10,2), debit_quarter VARCHAR(6))`",
    targetQuery: `SELECT c.client_id, c.portfolio_name, c.aum_usd,\n       COALESCE(SUM(d.fee_amount_usd), 0.00) AS q3_fees_paid_usd,\n       ROUND((COALESCE(SUM(d.fee_amount_usd), 0.00) / c.aum_usd) * 10000.0, 1) AS effective_fee_bps,\n       CASE\n         WHEN SUM(d.fee_amount_usd) IS NULL THEN 'FEE_EXEMPT_OR_PENDING'\n         ELSE 'BILLED'\n       END AS billing_audit_flag\nFROM WealthClients c\nLEFT JOIN AdvisoryFeeDebits d\n  ON c.client_id = d.client_id\n AND d.debit_quarter = '2026Q3'\nGROUP BY c.client_id, c.portfolio_name, c.aum_usd\nORDER BY c.aum_usd DESC;`,
    eli5Story: "Calculating management fees in basis points for multi-million dollar portfolios. If an account has zero fees, calculate 0 basis points and label them fee-exempt.",
    commonMistakes: "Putting the filter 'd.debit_quarter = 2026Q3' in the WHERE clause, which turns the LEFT JOIN into an INNER JOIN and drops all zero-fee clients.",
    learningOutcomes: "Master placing right-table filters in the ON clause vs the WHERE clause to preserve outer join driving rows."
  },
  {
    title: "Merchant POS Terminals to Daily Batch Settlements (Dormant Hardware Tracking)",
    ind: "Fintech",
    diff: "Easy",
    table: "PosTerminals",
    scenario: "Monitoring active vs dormant credit card swiper terminals deployed at retail merchants across metropolitan districts.",
    businessObjective: "Left join PosTerminals to BatchSettlements on terminal_id to report settlement counts per terminal, highlighting terminals with 0 swipes.",
    schemaSnippet: "`PosTerminals (terminal_id VARCHAR(16) PRIMARY KEY, merchant_name VARCHAR(64), district VARCHAR(32), deployed_date DATE)` & `BatchSettlements (batch_id VARCHAR(32) PRIMARY KEY, terminal_id VARCHAR(16), settled_usd DECIMAL(10,2))`",
    targetQuery: `SELECT t.terminal_id, t.merchant_name, t.district,\n       COUNT(s.batch_id) AS settled_batches_count,\n       COALESCE(SUM(s.settled_usd), 0.00) AS total_settled_usd\nFROM PosTerminals t\nLEFT JOIN BatchSettlements s\n  ON t.terminal_id = s.terminal_id\nGROUP BY t.terminal_id, t.merchant_name, t.district\nORDER BY settled_batches_count ASC;`,
    eli5Story: "Checking how much money each card reader swiped today. If a terminal swiped zero dollars, show $0 so technicians know it might be unplugged.",
    commonMistakes: "Omitting the terminal_id in the GROUP BY clause or failing to use COALESCE.",
    learningOutcomes: "Detect zero-activity hardware devices using aggregate left join patterns."
  },

  // --- SAAS ---
  {
    title: "Workspace Tenants to Monthly Active User Seat Utilizations",
    ind: "SaaS",
    diff: "Easy",
    table: "WorkspaceTenants",
    scenario: "Auditing enterprise workspace licenses to calculate seat utilization percentages, including workspaces where zero invited users logged in.",
    businessObjective: "Left join WorkspaceTenants to UserLogins on workspace_id to count active users vs provisioned seats.",
    schemaSnippet: "`WorkspaceTenants (workspace_id VARCHAR(32) PRIMARY KEY, org_name VARCHAR(100), provisioned_seats INT)` & `UserLogins (login_id VARCHAR(32) PRIMARY KEY, workspace_id VARCHAR(32), user_email VARCHAR(100), last_login_date DATE)`",
    targetQuery: `SELECT w.workspace_id, w.org_name, w.provisioned_seats,\n       COUNT(DISTINCT u.user_email) AS active_users_count,\n       ROUND((COUNT(DISTINCT u.user_email) * 100.0) / w.provisioned_seats, 1) AS seat_utilization_pct\nFROM WorkspaceTenants w\nLEFT JOIN UserLogins u\n  ON w.workspace_id = u.workspace_id\nGROUP BY w.workspace_id, w.org_name, w.provisioned_seats\nORDER BY seat_utilization_pct ASC;`,
    eli5Story: "Seeing how many company accounts bought 50 seats but have 0 people actually logging in, so our customer success team can offer help.",
    commonMistakes: "Using COUNT(u.workspace_id) without DISTINCT when users log in multiple times, inflating utilization beyond 100%.",
    learningOutcomes: "Calculate adoption percentages on outer joins using COUNT(DISTINCT right_table_user)."
  },
  {
    title: "Developer API Tokens to Monthly Request Spikes (Dormant Token Hygiene)",
    ind: "SaaS",
    diff: "Medium",
    table: "ApiTokens",
    scenario: "Identifying unused or stale developer API tokens generated by customers that have never registered an API request.",
    businessObjective: "Left join ApiTokens to RequestLogs on token_id to track total API calls, flagging tokens with 0 calls for automated deprecation.",
    schemaSnippet: "`ApiTokens (token_id VARCHAR(32) PRIMARY KEY, developer_id VARCHAR(32), created_at DATE, environment VARCHAR(16))` & `RequestLogs (log_id BIGINT PRIMARY KEY, token_id VARCHAR(32), http_status INT)`",
    targetQuery: `SELECT t.token_id, t.developer_id, t.environment,\n       COUNT(r.log_id) AS total_requests_served,\n       CASE\n         WHEN COUNT(r.log_id) = 0 THEN 'DORMANT_TOKEN_NEEDS_REVOCATION'\n         ELSE 'ACTIVE_IN_USE'\n       END AS token_lifecycle_status\nFROM ApiTokens t\nLEFT JOIN RequestLogs r\n  ON t.token_id = r.token_id\nGROUP BY t.token_id, t.developer_id, t.environment\nORDER BY total_requests_served ASC;`,
    eli5Story: "Finding secret developer API keys that were created months ago but never touched, so we can turn them off for security.",
    commonMistakes: "Using `WHERE r.log_id IS NULL` when the requirement is to report ALL tokens with their active/dormant status.",
    learningOutcomes: "Perform lifecycle classification across outer-joined usage feeds."
  },
  {
    title: "Customer Success Enterprise Accounts to Quarterly Business Reviews (QBRs)",
    ind: "SaaS",
    diff: "Medium",
    table: "EnterpriseAccounts",
    scenario: "Tracking CS team touchpoints by joining high-touch customer accounts to completed Executive QBR meetings.",
    businessObjective: "Left join EnterpriseAccounts to QbrMeetings on account_id to report QBR completion status and identify unserviced accounts.",
    schemaSnippet: "`EnterpriseAccounts (account_id VARCHAR(32) PRIMARY KEY, account_name VARCHAR(100), arr_usd DECIMAL(12,2), csm_owner VARCHAR(64))` & `QbrMeetings (qbr_id VARCHAR(32) PRIMARY KEY, account_id VARCHAR(32), completed_date DATE, satisfaction_score INT)`",
    targetQuery: `SELECT e.account_id, e.account_name, e.arr_usd, e.csm_owner,\n       COUNT(q.qbr_id) AS completed_qbr_count,\n       COALESCE(MAX(q.satisfaction_score), 0) AS latest_csat_score,\n       CASE\n         WHEN COUNT(q.qbr_id) = 0 THEN 'HIGH_CHURN_RISK_NO_QBR'\n         ELSE 'ENGAGED'\n       END AS account_engagement_status\nFROM EnterpriseAccounts e\nLEFT JOIN QbrMeetings q\n  ON e.account_id = q.account_id\nWHERE e.arr_usd >= 100000.00\nGROUP BY e.account_id, e.account_name, e.arr_usd, e.csm_owner\nORDER BY completed_qbr_count ASC, e.arr_usd DESC;`,
    eli5Story: "Checking which big six-figure customers haven't had a check-in meeting with their account manager, so they don't cancel their contract.",
    commonMistakes: "Filtering out accounts where completed_qbr_count = 0 instead of prioritizing them as churn risks.",
    learningOutcomes: "Generate executive customer health scorecards combining contract ARR with outer-joined meeting metrics."
  },
  {
    title: "Cloud Infrastructure Clusters to Billed Spot Instance Hours (Idle Standby Pods)",
    ind: "SaaS",
    diff: "Hard",
    table: "KubernetesClusters",
    scenario: "Auditing multi-cloud Kubernetes compute clusters to calculate cloud provider compute costs, preserving idle zero-usage failover clusters.",
    businessObjective: "Left join KubernetesClusters to SpotInstanceUsage on cluster_id to compute total cluster infrastructure spend with zero-preservation.",
    schemaSnippet: "`KubernetesClusters (cluster_id VARCHAR(32) PRIMARY KEY, region VARCHAR(16), node_pool VARCHAR(32), cluster_role VARCHAR(16))` & `SpotInstanceUsage (usage_id VARCHAR(32) PRIMARY KEY, cluster_id VARCHAR(32), billed_hours DECIMAL(8,2), hourly_rate_usd DECIMAL(6,3))`",
    targetQuery: `SELECT k.cluster_id, k.region, k.cluster_role,\n       COALESCE(SUM(s.billed_hours), 0.0) AS total_spot_hours,\n       COALESCE(ROUND(SUM(s.billed_hours * s.hourly_rate_usd), 2), 0.00) AS total_compute_cost_usd,\n       CASE\n         WHEN SUM(s.billed_hours) IS NULL AND k.cluster_role = 'DISASTER_RECOVERY' THEN 'VALID_COLD_STANDBY'\n         WHEN SUM(s.billed_hours) IS NULL AND k.cluster_role = 'PRODUCTION' THEN 'CRITICAL_OFFLINE_ANOMALY'\n         ELSE 'NORMAL_OPERATIONS'\n       END AS infra_health_check\nFROM KubernetesClusters k\nLEFT JOIN SpotInstanceUsage s\n  ON k.cluster_id = s.cluster_id\nGROUP BY k.cluster_id, k.region, k.cluster_role\nORDER BY total_compute_cost_usd DESC;`,
    eli5Story: "Calculating cloud server bills for every Kubernetes server cluster. If a backup disaster recovery cluster used $0, keep it on the report and verify it's standing by.",
    commonMistakes: "Returning NULL for compute cost instead of wrapping the entire expression in COALESCE(..., 0.00).",
    learningOutcomes: "Handle zero-spend infrastructure clusters and perform multi-branch conditional operational tagging."
  },

  // --- RETAIL ---
  {
    title: "Retail Store Locations to Seasonal Clearance Sale Revenues",
    ind: "Retail",
    diff: "Easy",
    table: "StoreLocations",
    scenario: "Reviewing seasonal clearance sale performance across brick-and-mortar stores, ensuring stores with zero clearance sales remain on the report.",
    businessObjective: "Left join StoreLocations to ClearanceSales on store_id to summarize clearance revenue by retail store.",
    schemaSnippet: "`StoreLocations (store_id VARCHAR(16) PRIMARY KEY, city VARCHAR(64), state VARCHAR(2), square_footage INT)` & `ClearanceSales (sale_id VARCHAR(32) PRIMARY KEY, store_id VARCHAR(16), net_amount_usd DECIMAL(10,2))`",
    targetQuery: `SELECT l.store_id, l.city, l.state,\n       COALESCE(SUM(s.net_amount_usd), 0.00) AS total_clearance_revenue_usd\nFROM StoreLocations l\nLEFT JOIN ClearanceSales s\n  ON l.store_id = s.store_id\nGROUP BY l.store_id, l.city, l.state\nORDER BY total_clearance_revenue_usd ASC;`,
    eli5Story: "Checking how much discount clothing each retail store sold. If a store sold zero clearance clothes, show $0.00 so executives see who is holding onto old stock.",
    commonMistakes: "Using `SUM(COALESCE(s.net_amount_usd, 0.00))` which is valid, but failing to handle when the entire group is empty (returning NULL without outer COALESCE in some engines).",
    learningOutcomes: "Preserve non-selling store entities in regional sales distribution analyses."
  },
  {
    title: "Master Product Catalog SKUs to Customer Return RMA Claims",
    ind: "Retail",
    diff: "Medium",
    table: "ProductCatalog",
    scenario: "Computing product return rates by joining master product SKUs with return merchandise authorization (RMA) claims.",
    businessObjective: "Left join ProductCatalog to ReturnClaims on sku to compute return counts and claim dollars, highlighting items with 0 returns.",
    schemaSnippet: "`ProductCatalog (sku VARCHAR(32) PRIMARY KEY, product_name VARCHAR(100), category VARCHAR(32), units_sold INT)` & `ReturnClaims (rma_id VARCHAR(32) PRIMARY KEY, sku VARCHAR(32), refund_usd DECIMAL(8,2))`",
    targetQuery: `SELECT p.sku, p.product_name, p.category, p.units_sold,\n       COUNT(r.rma_id) AS units_returned,\n       COALESCE(SUM(r.refund_usd), 0.00) AS total_refunded_usd,\n       ROUND((COUNT(r.rma_id) * 100.0) / NULLIF(p.units_sold, 0), 2) AS return_rate_pct\nFROM ProductCatalog p\nLEFT JOIN ReturnClaims r\n  ON p.sku = r.sku\nWHERE p.units_sold > 50\nGROUP BY p.sku, p.product_name, p.category, p.units_sold\nORDER BY return_rate_pct ASC;`,
    eli5Story: "Finding the best quality products that customers loved so much they never returned a single one (0% return rate).",
    commonMistakes: "Division by zero if units_sold is 0; NULLIF(units_sold, 0) prevents SQL runtime exceptions.",
    learningOutcomes: "Safely calculate percentage ratios combining driving table denominators with outer-joined numerators."
  },
  {
    title: "Registered Loyalty Club Members to Current Quarter Purchases",
    ind: "Retail",
    diff: "Easy",
    table: "LoyaltyMembers",
    scenario: "Auditing member retention by checking which loyalty cardholders have made zero purchases during the current promotional quarter.",
    businessObjective: "Left join LoyaltyMembers to MemberPurchases on member_id to report quarterly member purchase frequency.",
    schemaSnippet: "`LoyaltyMembers (member_id VARCHAR(32) PRIMARY KEY, full_name VARCHAR(100), tier_status VARCHAR(16), enrolled_date DATE)` & `MemberPurchases (purchase_id VARCHAR(32) PRIMARY KEY, member_id VARCHAR(32), amount_usd DECIMAL(8,2), purchase_date DATE)`",
    targetQuery: `SELECT m.member_id, m.full_name, m.tier_status,\n       COUNT(p.purchase_id) AS purchases_this_quarter,\n       COALESCE(SUM(p.amount_usd), 0.00) AS total_spend_this_quarter\nFROM LoyaltyMembers m\nLEFT JOIN MemberPurchases p\n  ON m.member_id = p.member_id\n AND p.purchase_date >= '2026-07-01'\nGROUP BY m.member_id, m.full_name, m.tier_status\nORDER BY purchases_this_quarter ASC;`,
    eli5Story: "Seeing which loyalty club members haven't visited our stores lately, showing 0 visits and $0 spent so we can email them a $5 coupon.",
    commonMistakes: "Putting the date filter in the WHERE clause, which drops all members who had no purchases.",
    learningOutcomes: "Understand how ON-clause date filtering maintains all customer profiles in customer churn analysis."
  },
  {
    title: "Vendor Supplier Master to Warranty Quality Defect Claims",
    ind: "Retail",
    diff: "Hard",
    table: "SupplierMaster",
    scenario: "Rating suppliers for annual vendor contract renewals by calculating warranty defect rates and defect liability chargebacks.",
    businessObjective: "Left join SupplierMaster to WarrantyDefects on supplier_id to calculate total defect claims per supplier with zero-preservation.",
    schemaSnippet: "`SupplierMaster (supplier_id VARCHAR(32) PRIMARY KEY, supplier_name VARCHAR(100), total_po_volume_usd DECIMAL(14,2))` & `WarrantyDefects (defect_id VARCHAR(32) PRIMARY KEY, supplier_id VARCHAR(32), claim_cost_usd DECIMAL(10,2), defect_type VARCHAR(32))`",
    targetQuery: `SELECT s.supplier_id, s.supplier_name, s.total_po_volume_usd,\n       COUNT(w.defect_id) AS total_defect_claims,\n       COALESCE(SUM(w.claim_cost_usd), 0.00) AS total_claim_liability_usd,\n       ROUND((COALESCE(SUM(w.claim_cost_usd), 0.00) / s.total_po_volume_usd) * 100.0, 3) AS defect_cost_pct,\n       CASE\n         WHEN COUNT(w.defect_id) = 0 THEN 'EXCELLENT_ZERO_DEFECT_TIER'\n         WHEN (COALESCE(SUM(w.claim_cost_usd), 0.00) / s.total_po_volume_usd) * 100.0 <= 1.0 THEN 'ACCEPTABLE_TIER'\n         ELSE 'DEFECT_PENALTY_TIER'\n       END AS vendor_quality_rating\nFROM SupplierMaster s\nLEFT JOIN WarrantyDefects w\n  ON s.supplier_id = w.supplier_id\nGROUP BY s.supplier_id, s.supplier_name, s.total_po_volume_usd\nORDER BY defect_cost_pct ASC;`,
    eli5Story: "Grading our manufacturing suppliers. If a supplier delivered thousands of items with zero defect claims, award them our Gold Quality Trophy.",
    commonMistakes: "Calculating defect cost percentage before applying COALESCE to total_claim_liability_usd, producing NULL percentages.",
    learningOutcomes: "Perform multi-tier vendor scorecard ratings using zero-padded defect calculations."
  },

  // --- HEALTHCARE ---
  {
    title: "Enrolled Outpatient Cohorts to Missed Appointment No-Shows",
    ind: "Healthcare",
    diff: "Medium",
    table: "OutpatientCohorts",
    scenario: "Monitoring outpatient appointment compliance across chronic disease management clinics to measure patient adherence.",
    businessObjective: "Left join OutpatientCohorts to ClinicAppointments on patient_id, computing total booked visits and missed no-show counts.",
    schemaSnippet: "`OutpatientCohorts (patient_id VARCHAR(32) PRIMARY KEY, clinic_id VARCHAR(16), primary_condition VARCHAR(48), enrollment_date DATE)` & `ClinicAppointments (appt_id VARCHAR(32) PRIMARY KEY, patient_id VARCHAR(32), status VARCHAR(16))`",
    targetQuery: `SELECT c.clinic_id, c.primary_condition,\n       COUNT(DISTINCT c.patient_id) AS total_enrolled_patients,\n       COUNT(a.appt_id) AS total_scheduled_appointments,\n       SUM(CASE WHEN a.status = 'NO_SHOW' THEN 1 ELSE 0 END) AS total_no_shows,\n       ROUND((SUM(CASE WHEN a.status = 'NO_SHOW' THEN 1 ELSE 0 END) * 100.0) / NULLIF(COUNT(a.appt_id), 0), 1) AS no_show_rate_pct\nFROM OutpatientCohorts c\nLEFT JOIN ClinicAppointments a\n  ON c.patient_id = a.patient_id\nGROUP BY c.clinic_id, c.primary_condition\nORDER BY no_show_rate_pct DESC;`,
    eli5Story: "Checking which diabetes and asthma clinics have patients who consistently show up vs clinics where patients frequently skip appointments.",
    commonMistakes: "Using an INNER JOIN which leaves out newly enrolled patients who have not yet had their first appointment.",
    learningOutcomes: "Calculate medical appointment adherence rates across clinical outpatient registries."
  },
  {
    title: "Licensed Registered Nurses to Assigned Patient Acuity Ratios",
    ind: "Healthcare",
    diff: "Hard",
    table: "RegisteredNurses",
    scenario: "Auditing state-mandated nurse-to-patient staffing ratios in emergency departments and intensive care units.",
    businessObjective: "Left join RegisteredNurses to BedAssignments on nurse_license_no to calculate active patient load per registered nurse.",
    schemaSnippet: "`RegisteredNurses (nurse_license_no VARCHAR(16) PRIMARY KEY, nurse_name VARCHAR(100), unit_ward VARCHAR(32), shift VARCHAR(8))` & `BedAssignments (assignment_id VARCHAR(32) PRIMARY KEY, nurse_license_no VARCHAR(16), bed_id VARCHAR(16), acuity_score INT)`",
    targetQuery: `SELECT n.nurse_license_no, n.nurse_name, n.unit_ward, n.shift,\n       COUNT(b.assignment_id) AS active_patient_count,\n       COALESCE(SUM(b.acuity_score), 0) AS total_acuity_workload,\n       CASE\n         WHEN COUNT(b.assignment_id) = 0 THEN 'STANDBY_OR_BREAK'\n         WHEN COUNT(b.assignment_id) > 4 AND n.unit_ward = 'ICU' THEN 'RATIO_BREACH_OVERLOADED'\n         ELSE 'COMPLIANT'\n       END AS staffing_ratio_status\nFROM RegisteredNurses n\nLEFT JOIN BedAssignments b\n  ON n.nurse_license_no = b.nurse_license_no\nGROUP BY n.nurse_license_no, n.nurse_name, n.unit_ward, n.shift\nORDER BY total_acuity_workload DESC;`,
    eli5Story: "Making sure no ICU nurse has more than 4 critically ill patients assigned to them, and identifying floating nurses currently on break.",
    commonMistakes: "Failing to account for ward-specific legal limits (ICU vs General Ward) in the conditional status classification.",
    learningOutcomes: "Implement statutory healthcare staffing compliance checks via conditional outer join aggregations."
  },
  {
    title: "Clinical Trial Subjects to Adverse Event (AE) Safety Logs",
    ind: "Healthcare",
    diff: "Easy",
    table: "TrialSubjects",
    scenario: "Compiling FDA Phase-III oncology drug trial safety summaries, ensuring subjects with zero adverse events are fully accounted for.",
    businessObjective: "Left join TrialSubjects to AdverseEvents on subject_id to report adverse event frequencies across test dosage arms.",
    schemaSnippet: "`TrialSubjects (subject_id VARCHAR(32) PRIMARY KEY, trial_arm VARCHAR(16), age INT, enrolled_date DATE)` & `AdverseEvents (ae_id VARCHAR(32) PRIMARY KEY, subject_id VARCHAR(32), severity_grade INT, ae_term VARCHAR(64))`",
    targetQuery: `SELECT s.trial_arm,\n       COUNT(DISTINCT s.subject_id) AS total_subjects,\n       COUNT(e.ae_id) AS total_reported_adverse_events,\n       SUM(CASE WHEN e.severity_grade >= 3 THEN 1 ELSE 0 END) AS serious_adverse_events\nFROM TrialSubjects s\nLEFT JOIN AdverseEvents e\n  ON s.subject_id = e.subject_id\nGROUP BY s.trial_arm\nORDER BY serious_adverse_events DESC;`,
    eli5Story: "Counting drug side-effects in a clinical medical study. If half the patients had zero side effects, keep them in the subject count so safety percentages are accurate.",
    commonMistakes: "Using an INNER JOIN which makes the experimental drug look far more dangerous by discarding all healthy subjects with zero side effects.",
    learningOutcomes: "Preserve safety denominators in clinical pharmaceutical trial reporting."
  },
  {
    title: "Medical Diagnostic Equipment to Scheduled Preventive Maintenance Logs",
    ind: "Healthcare",
    diff: "Medium",
    table: "MedicalDevices",
    scenario: "Verifying hospital radiology equipment (MRI, CT, Ultrasound) maintenance compliance to prevent unexpected equipment downtime.",
    businessObjective: "Left join MedicalDevices to MaintenanceLogs on device_serial to audit service frequency and flag unserviced equipment.",
    schemaSnippet: "`MedicalDevices (device_serial VARCHAR(32) PRIMARY KEY, device_type VARCHAR(32), hospital_dept VARCHAR(32), install_year INT)` & `MaintenanceLogs (log_id VARCHAR(32) PRIMARY KEY, device_serial VARCHAR(32), service_date DATE, technician_id VARCHAR(16))`",
    targetQuery: `SELECT d.device_serial, d.device_type, d.hospital_dept,\n       COUNT(m.log_id) AS service_records_count,\n       MAX(m.service_date) AS last_service_date,\n       CASE\n         WHEN COUNT(m.log_id) = 0 THEN 'CRITICAL_NEVER_SERVICED'\n         ELSE 'SERVICED'\n       END AS maintenance_status\nFROM MedicalDevices d\nLEFT JOIN MaintenanceLogs m\n  ON d.device_serial = m.device_serial\nGROUP BY d.device_serial, d.device_type, d.hospital_dept\nORDER BY service_records_count ASC, d.install_year ASC;`,
    eli5Story: "Checking when the hospital MRI machines were last inspected by a certified technician to make sure none were forgotten.",
    commonMistakes: "Assuming `MAX(m.service_date)` will default to today's date instead of returning NULL for unserviced machines.",
    learningOutcomes: "Track equipment maintenance frequency and identify unserviced assets using outer join timestamps."
  },

  // --- LOGISTICS ---
  {
    title: "Regional Distribution Hubs to Outbound Hazmat Shipment Volumes",
    ind: "Logistics",
    diff: "Easy",
    table: "DistributionHubs",
    scenario: "Tracking hazardous material dispatches across regional warehouses, including logistics hubs that handle zero hazardous goods.",
    businessObjective: "Left join DistributionHubs to HazmatShipments on hub_id to summarize chemical transport volumes per hub.",
    schemaSnippet: "`DistributionHubs (hub_id VARCHAR(16) PRIMARY KEY, hub_name VARCHAR(64), state VARCHAR(2))` & `HazmatShipments (shipment_id VARCHAR(32) PRIMARY KEY, hub_id VARCHAR(16), weight_kg DECIMAL(10,2))`",
    targetQuery: `SELECT h.hub_id, h.hub_name, h.state,\n       COUNT(s.shipment_id) AS hazmat_shipment_count,\n       COALESCE(SUM(s.weight_kg), 0.00) AS total_hazmat_weight_kg\nFROM DistributionHubs h\nLEFT JOIN HazmatShipments s\n  ON h.hub_id = s.hub_id\nGROUP BY h.hub_id, h.hub_name, h.state\nORDER BY total_hazmat_weight_kg ASC;`,
    eli5Story: "Listing all shipping hubs and adding up how many tons of hazardous chemicals each shipped, showing 0 for hubs that only ship regular boxes.",
    commonMistakes: "Using an INNER JOIN which omits general merchandise distribution hubs from network-wide safety audits.",
    learningOutcomes: "Preserve zero-volume operational nodes in logistics network reporting."
  },
  {
    title: "Freight Tractor Fleet to Unplanned Roadside Breakdown Dispatches",
    ind: "Logistics",
    diff: "Medium",
    table: "FreightTractors",
    scenario: "Evaluating semi-truck fleet reliability by comparing odometer mileage against emergency roadside repair calls.",
    businessObjective: "Left join FreightTractors to RoadsideBreakdowns on truck_vin to calculate breakdowns per thousand miles.",
    schemaSnippet: "`FreightTractors (truck_vin VARCHAR(17) PRIMARY KEY, model_year INT, odometer_miles INT, fleet_division VARCHAR(16))` & `RoadsideBreakdowns (call_id VARCHAR(32) PRIMARY KEY, truck_vin VARCHAR(17), repair_cost_usd DECIMAL(8,2))`",
    targetQuery: `SELECT t.truck_vin, t.model_year, t.odometer_miles,\n       COUNT(b.call_id) AS breakdown_incident_count,\n       COALESCE(SUM(b.repair_cost_usd), 0.00) AS total_repair_cost_usd,\n       ROUND((COUNT(b.call_id) * 10000.0) / NULLIF(t.odometer_miles, 0), 2) AS incidents_per_10k_miles\nFROM FreightTractors t\nLEFT JOIN RoadsideBreakdowns b\n  ON t.truck_vin = b.truck_vin\nWHERE t.odometer_miles > 10000\nGROUP BY t.truck_vin, t.model_year, t.odometer_miles\nORDER BY breakdown_incident_count ASC;`,
    eli5Story: "Celebrating the toughest diesel trucks in our fleet that drove over 100,000 miles with zero breakdown calls.",
    commonMistakes: "Failing to check for trucks with 0 breakdowns, misidentifying zero breakdowns as missing data.",
    learningOutcomes: "Calculate reliability metrics on outer joins with zero-preservation."
  },
  {
    title: "Airport Cargo Terminals to Customs Hold Inspection Delay Hours",
    ind: "Logistics",
    diff: "Hard",
    table: "CargoTerminals",
    scenario: "Measuring international air cargo throughput bottlenecks by joining airport customs clearing terminals to inspection hold logs.",
    businessObjective: "Left join CargoTerminals to CustomsHolds on terminal_id to report average clearance delay hours across freight airports.",
    schemaSnippet: "`CargoTerminals (terminal_id VARCHAR(16) PRIMARY KEY, airport_iata VARCHAR(3), operator_name VARCHAR(64))` & `CustomsHolds (hold_id VARCHAR(32) PRIMARY KEY, terminal_id VARCHAR(16), delay_hours DECIMAL(6,2), is_seized BOOLEAN)`",
    targetQuery: `SELECT t.airport_iata, t.operator_name,\n       COUNT(h.hold_id) AS total_inspections,\n       COALESCE(ROUND(AVG(h.delay_hours), 2), 0.00) AS avg_hold_delay_hours,\n       COALESCE(SUM(CASE WHEN h.is_seized = TRUE THEN 1 ELSE 0 END), 0) AS total_seizures\nFROM CargoTerminals t\nLEFT JOIN CustomsHolds h\n  ON t.terminal_id = h.terminal_id\nGROUP BY t.airport_iata, t.operator_name\nORDER BY avg_hold_delay_hours DESC;`,
    eli5Story: "Seeing how many hours international air shipments get stuck in customs at JFK, LAX, and Chicago O'Hare airports.",
    commonMistakes: "Using `AVG(h.delay_hours)` without COALESCE, returning NULL for terminals that had zero customs holds.",
    learningOutcomes: "Aggregate operational hold delays with zero-default handling across transport hubs."
  },
  {
    title: "Delivery Couriers to Customer Five-Star Rating Tips",
    ind: "Logistics",
    diff: "Easy",
    table: "DeliveryCouriers",
    scenario: "Calculating weekly courier tip payouts, ensuring newly onboarded couriers who haven't received tips yet are recorded with $0.00.",
    businessObjective: "Left join DeliveryCouriers to CustomerTips on courier_id to compute total weekly tips earned.",
    schemaSnippet: "`DeliveryCouriers (courier_id VARCHAR(32) PRIMARY KEY, full_name VARCHAR(100), vehicle_type VARCHAR(16))` & `CustomerTips (tip_id VARCHAR(32) PRIMARY KEY, courier_id VARCHAR(32), tip_amount DECIMAL(6,2), rating INT)`",
    targetQuery: `SELECT c.courier_id, c.full_name, c.vehicle_type,\n       COUNT(t.tip_id) AS tipped_delivery_count,\n       COALESCE(SUM(t.tip_amount), 0.00) AS total_tips_earned_usd\nFROM DeliveryCouriers c\nLEFT JOIN CustomerTips t\n  ON c.courier_id = t.courier_id\nGROUP BY c.courier_id, c.full_name, c.vehicle_type\nORDER BY total_tips_earned_usd DESC;`,
    eli5Story: "Adding up tips given to bike and car delivery workers, making sure workers with no tips show $0.00 on their paycheck stub.",
    commonMistakes: "Using an INNER JOIN which leaves couriers with $0 tips off the payroll run completely.",
    learningOutcomes: "Safely calculate optional customer gratuities on driver payroll sheets."
  },

  // --- MEDIA ---
  {
    title: "Licensed Streaming Series to Nielsen Weekly Viewership Minutes",
    ind: "Media",
    diff: "Medium",
    table: "StreamingSeries",
    scenario: "Evaluating streaming TV catalog performance by joining licensed shows with Nielsen panel streaming meter minutes.",
    businessObjective: "Left join StreamingSeries to NielsenMetrics on show_id to identify dead catalog titles with zero recorded watch minutes.",
    schemaSnippet: "`StreamingSeries (show_id VARCHAR(32) PRIMARY KEY, series_title VARCHAR(100), licensing_cost_usd DECIMAL(12,2), genre VARCHAR(32))` & `NielsenMetrics (metric_id VARCHAR(32) PRIMARY KEY, show_id VARCHAR(32), stream_minutes_millions DECIMAL(8,2))`",
    targetQuery: `SELECT s.series_title, s.genre, s.licensing_cost_usd,\n       COALESCE(SUM(m.stream_minutes_millions), 0.0) AS total_watch_minutes_millions,\n       CASE\n         WHEN SUM(m.stream_minutes_millions) IS NULL THEN 'ZERO_ENGAGEMENT_SUNSET_CANDIDATE'\n         ELSE 'ACTIVE_VIEWERSHIP'\n       END AS catalog_lifecycle_flag\nFROM StreamingSeries s\nLEFT JOIN NielsenMetrics m\n  ON s.show_id = m.show_id\nGROUP BY s.series_title, s.genre, s.licensing_cost_usd\nORDER BY total_watch_minutes_millions ASC;`,
    eli5Story: "Checking which licensed TV shows on Netflix nobody watched this month so we can decide whether to cancel the expensive license.",
    commonMistakes: "Filtering out titles where minutes are NULL instead of flagging them for catalog removal.",
    learningOutcomes: "Identify underperforming media assets using outer-joined viewership engagement metrics."
  },
  {
    title: "Registered Gaming Subscribers to Cloud Multiplayer Session Hours",
    ind: "Media",
    diff: "Hard",
    table: "GamerProfiles",
    scenario: "Analyzing gaming subscription engagement by joining premium subscribers to cloud gaming server session durations.",
    businessObjective: "Left join GamerProfiles to GameSessions on gamer_id to calculate gameplay hours, identifying dormant subscribers.",
    schemaSnippet: "`GamerProfiles (gamer_id VARCHAR(32) PRIMARY KEY, handle VARCHAR(32), subscription_tier VARCHAR(16), joined_date DATE)` & `GameSessions (session_id VARCHAR(32) PRIMARY KEY, gamer_id VARCHAR(32), duration_hours DECIMAL(6,2))`",
    targetQuery: `SELECT g.subscription_tier,\n       COUNT(DISTINCT g.gamer_id) AS total_subscribers,\n       COUNT(s.session_id) AS total_sessions_played,\n       COALESCE(ROUND(SUM(s.duration_hours), 1), 0.0) AS total_hours_played,\n       ROUND(COALESCE(SUM(s.duration_hours), 0.0) / COUNT(DISTINCT g.gamer_id), 1) AS avg_hours_per_subscriber\nFROM GamerProfiles g\nLEFT JOIN GameSessions s\n  ON g.gamer_id = s.gamer_id\nGROUP BY g.subscription_tier\nORDER BY avg_hours_per_subscriber DESC;`,
    eli5Story: "Averaging how many hours gamers played on Xbox Cloud. Keeping players who played 0 hours in the count so subscription averages are accurate.",
    commonMistakes: "Dividing by COUNT(g.gamer_id) after joining, which counts joined session rows rather than distinct subscribers.",
    learningOutcomes: "Compute true per-user engagement benchmarks across outer-joined digital platform usage."
  },
  {
    title: "Journalism Columnists to Syndicated Article Reprint Royalties",
    ind: "Media",
    diff: "Easy",
    table: "StaffColumnists",
    scenario: "Computing monthly author syndication bonuses for newspaper and magazine writers whose articles were reprinted in partner outlets.",
    businessObjective: "Left join StaffColumnists to SyndicatedReprints on author_id to tally reprint bonus earnings per writer.",
    schemaSnippet: "`StaffColumnists (author_id VARCHAR(16) PRIMARY KEY, author_name VARCHAR(100), bureau VARCHAR(32))` & `SyndicatedReprints (reprint_id VARCHAR(32) PRIMARY KEY, author_id VARCHAR(16), royalty_fee_usd DECIMAL(8,2))`",
    targetQuery: `SELECT c.author_id, c.author_name, c.bureau,\n       COUNT(r.reprint_id) AS total_reprints,\n       COALESCE(SUM(r.royalty_fee_usd), 0.00) AS total_syndication_bonus_usd\nFROM StaffColumnists c\nLEFT JOIN SyndicatedReprints r\n  ON c.author_id = r.author_id\nGROUP BY c.author_id, c.author_name, c.bureau\nORDER BY total_syndication_bonus_usd DESC;`,
    eli5Story: "Checking how many times our journalists' news articles were republished in other papers and calculating their bonus check.",
    commonMistakes: "Excluding staff journalists who had zero syndicated reprints from the monthly roster.",
    learningOutcomes: "Maintain full employee directories when joining optional bonus commission tables."
  },
  {
    title: "Broadcast Radio Stations to Emergency Alert System (EAS) Test Logs",
    ind: "Media",
    diff: "Medium",
    table: "RadioStations",
    scenario: "Auditing FCC regulatory compliance for FM/AM radio broadcast towers to verify monthly Emergency Alert System test tone broadcasts.",
    businessObjective: "Left join RadioStations to EasTestLogs on call_sign to identify broadcast stations that failed to broadcast mandatory EAS test tones.",
    schemaSnippet: "`RadioStations (call_sign VARCHAR(8) PRIMARY KEY, frequency_mhz DECIMAL(5,1), broadcast_market VARCHAR(32))` & `EasTestLogs (test_id VARCHAR(32) PRIMARY KEY, call_sign VARCHAR(8), test_timestamp TIMESTAMP, tone_passed BOOLEAN)`",
    targetQuery: `SELECT r.call_sign, r.broadcast_market, r.frequency_mhz,\n       COUNT(e.test_id) AS total_tests_logged,\n       COALESCE(SUM(CASE WHEN e.tone_passed = TRUE THEN 1 ELSE 0 END), 0) AS successful_tests,\n       CASE\n         WHEN COUNT(e.test_id) = 0 THEN 'FCC_VIOLATION_ZERO_TESTS'\n         ELSE 'COMPLIANT'\n       END AS fcc_audit_status\nFROM RadioStations r\nLEFT JOIN EasTestLogs e\n  ON r.call_sign = e.call_sign\nGROUP BY r.call_sign, r.broadcast_market, r.frequency_mhz\nORDER BY total_tests_logged ASC;`,
    eli5Story: "Making sure every radio station tested the screeching emergency alert tone on the radio this month as required by federal law.",
    commonMistakes: "Using `SUM(e.tone_passed)` which returns NULL when no rows match, rather than wrapping in COALESCE.",
    learningOutcomes: "Enforce federal communications regulatory compliance via outer-joined audit registers."
  },

  // --- SECURITY ---
  {
    title: "Cloud VPC Security Groups to Attached Network Interfaces (ENIs)",
    ind: "Security",
    diff: "Easy",
    table: "SecurityGroups",
    scenario: "Identifying unused, orphan AWS/GCP firewall security groups that have zero attached network interfaces.",
    businessObjective: "Left join SecurityGroups to NetworkInterfaces on group_id to find unattached firewall rules for automated cleanup.",
    schemaSnippet: "`SecurityGroups (group_id VARCHAR(32) PRIMARY KEY, group_name VARCHAR(64), vpc_id VARCHAR(32))` & `NetworkInterfaces (eni_id VARCHAR(32) PRIMARY KEY, group_id VARCHAR(32), ip_address VARCHAR(45))`",
    targetQuery: `SELECT g.group_id, g.group_name, g.vpc_id,\n       COUNT(n.eni_id) AS attached_interface_count\nFROM SecurityGroups g\nLEFT JOIN NetworkInterfaces n\n  ON g.group_id = n.group_id\nGROUP BY g.group_id, g.group_name, g.vpc_id\nORDER BY attached_interface_count ASC;`,
    eli5Story: "Finding security firewall rules that aren't protecting any computers, so we can delete the clutter from our cloud dashboard.",
    commonMistakes: "Using an INNER JOIN which only returns security groups that are currently in use.",
    learningOutcomes: "Audit unused cloud security infrastructure assets using count aggregation on outer joins."
  },
  {
    title: "Production Kubernetes Nodes to Quarantine Containment Events",
    ind: "Security",
    diff: "Medium",
    table: "KubernetesNodes",
    scenario: "Evaluating server fleet stability by joining cloud worker nodes to automated malware quarantine isolation events.",
    businessObjective: "Left join KubernetesNodes to QuarantineEvents on node_name to measure node security health and isolate compromised servers.",
    schemaSnippet: "`KubernetesNodes (node_name VARCHAR(64) PRIMARY KEY, cluster_name VARCHAR(32), os_image VARCHAR(64), uptime_days INT)` & `QuarantineEvents (event_id VARCHAR(32) PRIMARY KEY, node_name VARCHAR(64), reason VARCHAR(64), quarantined_at TIMESTAMP)`",
    targetQuery: `SELECT k.cluster_name,\n       COUNT(DISTINCT k.node_name) AS total_nodes,\n       COUNT(q.event_id) AS total_quarantine_events,\n       ROUND((COUNT(q.event_id) * 100.0) / COUNT(DISTINCT k.node_name), 1) AS quarantine_rate_pct\nFROM KubernetesNodes k\nLEFT JOIN QuarantineEvents q\n  ON k.node_name = q.node_name\nGROUP BY k.cluster_name\nORDER BY quarantine_rate_pct DESC;`,
    eli5Story: "Checking how many server computers in each cluster were locked down because our anti-malware system thought they were hacked.",
    commonMistakes: "Counting k.node_name instead of DISTINCT k.node_name, which overcounts nodes that were quarantined multiple times.",
    learningOutcomes: "Calculate node incident rates across containerized cluster infrastructure."
  },
  {
    title: "Privileged Admin Accounts to SOC Security Alert Incidents",
    ind: "Security",
    diff: "Hard",
    table: "AdminAccounts",
    scenario: "Monitoring corporate super-admin accounts for suspicious activity by joining administrator profiles to SOC alert tickets.",
    businessObjective: "Left join AdminAccounts to SocAlerts on admin_id to rank admins by security alert frequency while retaining clean admins.",
    schemaSnippet: "`AdminAccounts (admin_id VARCHAR(32) PRIMARY KEY, email VARCHAR(100), privilege_role VARCHAR(32), department VARCHAR(32))` & `SocAlerts (alert_id VARCHAR(32) PRIMARY KEY, admin_id VARCHAR(32), severity VARCHAR(16), rule_triggered VARCHAR(64))`",
    targetQuery: `SELECT a.admin_id, a.email, a.privilege_role,\n       COUNT(s.alert_id) AS total_soc_alerts,\n       SUM(CASE WHEN s.severity = 'HIGH' THEN 1 ELSE 0 END) AS high_severity_alerts,\n       CASE\n         WHEN COUNT(s.alert_id) = 0 THEN 'PRISTINE_NO_ANOMALIES'\n         WHEN SUM(CASE WHEN s.severity = 'HIGH' THEN 1 ELSE 0 END) > 0 THEN 'IMMEDIATE_REVOCATION_REVIEW'\n         ELSE 'ROUTINE_AUDIT'\n       END AS admin_risk_disposition\nFROM AdminAccounts a\nLEFT JOIN SocAlerts s\n  ON a.admin_id = s.admin_id\nGROUP BY a.admin_id, a.email, a.privilege_role\nORDER BY high_severity_alerts DESC, total_soc_alerts DESC;`,
    eli5Story: "Watching our company super-users who have access to all user data to see if their passwords got stolen or triggered any red flags.",
    commonMistakes: "Using INNER JOIN which hides all well-behaved administrators with zero security alerts.",
    learningOutcomes: "Implement continuous administrative privilege monitoring with automated risk tagging."
  },
  {
    title: "Corporate Laptop Assets to EDR Telemetry Heartbeats",
    ind: "Security",
    diff: "Easy",
    table: "LaptopAssets",
    scenario: "Tracking corporate endpoint fleet security by joining laptop hardware serials to CrowdStrike/SentinelOne agent hourly heartbeats.",
    businessObjective: "Left join LaptopAssets to EdrHeartbeats on serial_no to identify offline or missing laptops with zero recent heartbeats.",
    schemaSnippet: "`LaptopAssets (serial_no VARCHAR(32) PRIMARY KEY, assigned_user VARCHAR(100), model VARCHAR(32))` & `EdrHeartbeats (ping_id BIGINT PRIMARY KEY, serial_no VARCHAR(32), ping_time TIMESTAMP)`",
    targetQuery: `SELECT l.serial_no, l.assigned_user, l.model,\n       COUNT(h.ping_id) AS heartbeats_today,\n       MAX(h.ping_time) AS last_seen_time\nFROM LaptopAssets l\nLEFT JOIN EdrHeartbeats h\n  ON l.serial_no = h.serial_no\n AND h.ping_time >= NOW() - INTERVAL 24 HOUR\nGROUP BY l.serial_no, l.assigned_user, l.model\nORDER BY heartbeats_today ASC;`,
    eli5Story: "Making sure every company MacBook and Dell laptop is checking in with our security headquarters every hour.",
    commonMistakes: "Putting the 24-hour interval in the WHERE clause, which turns the LEFT JOIN into an INNER JOIN and hides missing laptops.",
    learningOutcomes: "Identify missing corporate IT hardware by maintaining outer join driving assets."
  },

  // --- HARDWARE ---
  {
    title: "Automated Assembly Workcells to Emergency E-Stop Downtime Minutes",
    ind: "Hardware",
    diff: "Easy",
    table: "AssemblyWorkcells",
    scenario: "Reviewing factory floor productivity by joining automated robotic assembly cells to logged emergency stop downtime incidents.",
    businessObjective: "Left join AssemblyWorkcells to EStopIncidents on workcell_id to report downtime minutes per cell, preserving 100% uptime cells.",
    schemaSnippet: "`AssemblyWorkcells (workcell_id VARCHAR(16) PRIMARY KEY, cell_name VARCHAR(64), building VARCHAR(16))` & `EStopIncidents (incident_id VARCHAR(32) PRIMARY KEY, workcell_id VARCHAR(16), downtime_minutes INT)`",
    targetQuery: `SELECT w.workcell_id, w.cell_name, w.building,\n       COUNT(e.incident_id) AS estop_triggers_count,\n       COALESCE(SUM(e.downtime_minutes), 0) AS total_downtime_minutes\nFROM AssemblyWorkcells w\nLEFT JOIN EStopIncidents e\n  ON w.workcell_id = e.workcell_id\nGROUP BY w.workcell_id, w.cell_name, w.building\nORDER BY total_downtime_minutes ASC;`,
    eli5Story: "Checking how many minutes robot arms stopped working because someone hit the big red emergency stop button.",
    commonMistakes: "Using an INNER JOIN which leaves out the best, most reliable robot stations that ran all day without stopping.",
    learningOutcomes: "Report manufacturing downtime variance while preserving flawless zero-downtime workcells."
  },
  {
    title: "Printed Circuit Board Fabrication Panels to Optical Inspection Scrap",
    ind: "Hardware",
    diff: "Medium",
    table: "PcbPanels",
    scenario: "Computing printed circuit board (PCB) fabrication yield rates by joining production mother-panels to automated optical inspection (AOI) scrap logs.",
    businessObjective: "Left join PcbPanels to AoiScraplogs on panel_id to calculate board yield percentages across production shifts.",
    schemaSnippet: "`PcbPanels (panel_id VARCHAR(32) PRIMARY KEY, layer_count INT, boards_per_panel INT, production_shift VARCHAR(8))` & `AoiScrapLogs (scrap_id VARCHAR(32) PRIMARY KEY, panel_id VARCHAR(32), scrapped_units INT)`",
    targetQuery: `SELECT p.production_shift,\n       COUNT(p.panel_id) AS total_panels_run,\n       SUM(p.boards_per_panel) AS gross_boards_manufactured,\n       COALESCE(SUM(s.scrapped_units), 0) AS total_boards_scrapped,\n       ROUND(((SUM(p.boards_per_panel) - COALESCE(SUM(s.scrapped_units), 0)) * 100.0) / SUM(p.boards_per_panel), 2) AS net_yield_pct\nFROM PcbPanels p\nLEFT JOIN AoiScrapLogs s\n  ON p.panel_id = s.panel_id\nGROUP BY p.production_shift\nORDER BY net_yield_pct DESC;`,
    eli5Story: "Calculating what percentage of manufactured circuit boards were perfect and didn't need to be thrown in the trash bin.",
    commonMistakes: "Subtracting scrapped units without COALESCE, turning the entire net boards calculation to NULL for perfect zero-scrap panels.",
    learningOutcomes: "Calculate manufacturing yield percentages on outer joins with zero-preservation."
  },
  {
    title: "Lithium-Ion Battery Cells to Thermal Runaway Chamber Stress Failures",
    ind: "Hardware",
    diff: "Hard",
    table: "BatteryCellBatches",
    scenario: "Auditing EV battery pack safety testing by joining manufacturing cell batches to high-temperature thermal runaway destruction tests.",
    businessObjective: "Left join BatteryCellBatches to ThermalFailures on batch_id to calculate failure rates and certify flawless battery lots for vehicle installation.",
    schemaSnippet: "`BatteryCellBatches (batch_id VARCHAR(32) PRIMARY KEY, chemistry VARCHAR(16), cell_count INT, cathode_supplier VARCHAR(64))` & `ThermalFailures (failure_id VARCHAR(32) PRIMARY KEY, batch_id VARCHAR(32), vent_temp_celsius DECIMAL(5,1))`",
    targetQuery: `SELECT b.batch_id, b.chemistry, b.cathode_supplier,\n       COUNT(f.failure_id) AS test_failures_count,\n       CASE\n         WHEN COUNT(f.failure_id) = 0 THEN 'CERTIFIED_AUTOMOTIVE_GRADE'\n         ELSE 'REJECT_QUARANTINE_LOT'\n       END AS safety_certification_status\nFROM BatteryCellBatches b\nLEFT JOIN ThermalFailures f\n  ON b.batch_id = f.batch_id\nGROUP BY b.batch_id, b.chemistry, b.cathode_supplier\nORDER BY test_failures_count ASC;`,
    eli5Story: "Testing electric car battery cells in an oven to certify batches that passed with zero fire or venting failures.",
    commonMistakes: "Filtering out zero-failure batches when zero failures is the exact criterion required for automotive certification.",
    learningOutcomes: "Implement zero-defect certification workflows using left join aggregations."
  },
  {
    title: "CNC Milling Machines to Spindle Bearing Replacement Work Orders",
    ind: "Hardware",
    diff: "Medium",
    table: "CncMachines",
    scenario: "Tracking precision machine tool wear-and-tear by joining CNC 5-axis mills to bearing overhaul maintenance work orders.",
    businessObjective: "Left join CncMachines to SpindleWorkOrders on machine_id to report machine maintenance history and flag overhauls.",
    schemaSnippet: "`CncMachines (machine_id VARCHAR(16) PRIMARY KEY, model_name VARCHAR(32), factory_floor VARCHAR(16))` & `SpindleWorkOrders (order_id VARCHAR(32) PRIMARY KEY, machine_id VARCHAR(16), cost_usd DECIMAL(8,2))`",
    targetQuery: `SELECT m.machine_id, m.model_name, m.factory_floor,\n       COUNT(w.order_id) AS bearing_replacement_count,\n       COALESCE(SUM(w.cost_usd), 0.00) AS total_maintenance_spend_usd\nFROM CncMachines m\nLEFT JOIN SpindleWorkOrders w\n  ON m.machine_id = w.machine_id\nGROUP BY m.machine_id, m.model_name, m.factory_floor\nORDER BY bearing_replacement_count DESC;`,
    eli5Story: "Tracking which giant metal-cutting CNC machines needed expensive new spindle bearings and which machines ran smooth with $0 in repairs.",
    commonMistakes: "Using an INNER JOIN which omits machines with zero work orders from factory asset registers.",
    learningOutcomes: "Track equipment overhaul maintenance expenses across factory machining assets."
  },

  // --- HR ---
  {
    title: "Department Cost Centers to Tuition Assistance Reimbursements",
    ind: "HR",
    diff: "Easy",
    table: "DepartmentCostCenters",
    scenario: "Reviewing corporate education benefits across company departments, including departments where zero employees applied for tuition aid.",
    businessObjective: "Left join DepartmentCostCenters to TuitionReimbursements on dept_id to report tuition expenditures per department.",
    schemaSnippet: "`DepartmentCostCenters (dept_id VARCHAR(16) PRIMARY KEY, dept_name VARCHAR(64), budget_cap_usd DECIMAL(12,2))` & `TuitionReimbursements (claim_id VARCHAR(32) PRIMARY KEY, dept_id VARCHAR(16), reimbursed_usd DECIMAL(8,2))`",
    targetQuery: `SELECT d.dept_id, d.dept_name,\n       COUNT(r.claim_id) AS student_employees_count,\n       COALESCE(SUM(r.reimbursed_usd), 0.00) AS total_tuition_aid_paid_usd\nFROM DepartmentCostCenters d\nLEFT JOIN TuitionReimbursements r\n  ON d.dept_id = r.dept_id\nGROUP BY d.dept_id, d.dept_name\nORDER BY total_tuition_aid_paid_usd DESC;`,
    eli5Story: "Seeing how much college tuition reimbursement each department paid out to employees who are taking night classes.",
    commonMistakes: "Omitting departments with zero tuition claims, distorting company-wide education benefit participation rates.",
    learningOutcomes: "Maintain complete organizational cost centers in employee benefit expenditure reports."
  },
  {
    title: "Full-Time Employees to Accrued Paid Time Off (PTO) Carryovers",
    ind: "HR",
    diff: "Medium",
    table: "Employees",
    scenario: "Calculating accrued vacation liability balances for corporate payroll accounting, preserving workers who took zero vacation days.",
    businessObjective: "Left join Employees to PtoDaysTaken on employee_id to calculate net remaining PTO days and financial balance sheet liability.",
    schemaSnippet: "`Employees (employee_id VARCHAR(32) PRIMARY KEY, full_name VARCHAR(100), daily_salary_usd DECIMAL(8,2), annual_pto_granted INT)` & `PtoDaysTaken (record_id VARCHAR(32) PRIMARY KEY, employee_id VARCHAR(32), days_used INT)`",
    targetQuery: `SELECT e.employee_id, e.full_name,\n       e.annual_pto_granted,\n       COALESCE(SUM(p.days_used), 0) AS total_pto_taken,\n       (e.annual_pto_granted - COALESCE(SUM(p.days_used), 0)) AS remaining_pto_days,\n       ROUND((e.annual_pto_granted - COALESCE(SUM(p.days_used), 0)) * e.daily_salary_usd, 2) AS pto_liability_usd\nFROM Employees e\nLEFT JOIN PtoDaysTaken p\n  ON e.employee_id = p.employee_id\nGROUP BY e.employee_id, e.full_name, e.annual_pto_granted, e.daily_salary_usd\nORDER BY pto_liability_usd DESC;`,
    eli5Story: "Calculating how much vacation pay the company owes employees who worked all year without taking a single day off.",
    commonMistakes: "Subtracting SUM(p.days_used) without COALESCE, turning remaining vacation into NULL for dedicated workers with zero days taken.",
    learningOutcomes: "Compute payroll balance sheet financial liabilities from outer-joined absence records."
  },
  {
    title: "Corporate Mentorship Mentors to Completed Protégé Coaching Hours",
    ind: "HR",
    diff: "Easy",
    table: "MentorVolunteers",
    scenario: "Tracking leadership development initiatives by joining registered senior mentors to logged one-on-one coaching sessions.",
    businessObjective: "Left join MentorVolunteers to CoachingSessions on mentor_id to report mentoring hours, highlighting unbooked mentors.",
    schemaSnippet: "`MentorVolunteers (mentor_id VARCHAR(32) PRIMARY KEY, mentor_name VARCHAR(100), job_title VARCHAR(64))` & `CoachingSessions (session_id VARCHAR(32) PRIMARY KEY, mentor_id VARCHAR(32), hours_spent DECIMAL(4,1))`",
    targetQuery: `SELECT m.mentor_id, m.mentor_name, m.job_title,\n       COUNT(s.session_id) AS total_sessions,\n       COALESCE(SUM(s.hours_spent), 0.0) AS total_coaching_hours\nFROM MentorVolunteers m\nLEFT JOIN CoachingSessions s\n  ON m.mentor_id = s.mentor_id\nGROUP BY m.mentor_id, m.mentor_name, m.job_title\nORDER BY total_coaching_hours ASC;`,
    eli5Story: "Seeing which senior managers signed up to mentor junior engineers but haven't been booked for any coaching sessions yet.",
    commonMistakes: "Using an INNER JOIN which hides all newly registered mentors waiting for their first mentee match.",
    learningOutcomes: "Monitor corporate talent development program participation using outer join aggregations."
  },
  {
    title: "Global Sales Representatives to Closed Annual Quota Attainments",
    ind: "HR",
    diff: "Hard",
    table: "SalesReps",
    scenario: "Computing sales compensation accelerators by joining account executives to closed enterprise deals, preserving reps with zero closed revenue.",
    businessObjective: "Left join SalesReps to ClosedDeals on rep_id to calculate quota attainment percentages across global sales regions.",
    schemaSnippet: "`SalesReps (rep_id VARCHAR(32) PRIMARY KEY, rep_name VARCHAR(100), annual_quota_usd DECIMAL(12,2), region VARCHAR(16))` & `ClosedDeals (deal_id VARCHAR(32) PRIMARY KEY, rep_id VARCHAR(32), deal_amount_usd DECIMAL(10,2))`",
    targetQuery: `SELECT r.rep_id, r.rep_name, r.region, r.annual_quota_usd,\n       COALESCE(SUM(d.deal_amount_usd), 0.00) AS total_closed_sales_usd,\n       ROUND((COALESCE(SUM(d.deal_amount_usd), 0.00) / r.annual_quota_usd) * 100.0, 1) AS quota_attainment_pct,\n       CASE\n         WHEN COALESCE(SUM(d.deal_amount_usd), 0.00) >= r.annual_quota_usd THEN 'PRESIDENTS_CLUB_QUALIFIED'\n         WHEN COALESCE(SUM(d.deal_amount_usd), 0.00) = 0.00 THEN 'ZERO_CLOSED_PIPELINE_REVIEW'\n         ELSE 'IN_PROGRESS'\n       END AS performance_bracket\nFROM SalesReps r\nLEFT JOIN ClosedDeals d\n  ON r.rep_id = d.rep_id\nGROUP BY r.rep_id, r.rep_name, r.region, r.annual_quota_usd\nORDER BY quota_attainment_pct DESC;`,
    eli5Story: "Comparing how much money each sales rep brought in against their annual target. Showing 0% for reps with zero deals so sales managers can coach them.",
    commonMistakes: "Dropping reps with zero deals by using INNER JOIN, making regional sales quota attainment look artificially high.",
    learningOutcomes: "Perform sales quota performance tiering using outer join calculations."
  },

  // --- PLATFORMS ---
  {
    title: "Gig Delivery Drivers to Completed Weekend Incentive Quests",
    ind: "Platforms",
    diff: "Easy",
    table: "GigDrivers",
    scenario: "Auditing weekend driver incentive bonuses by joining registered gig drivers to completed 20-trip bonus quest milestones.",
    businessObjective: "Left join GigDrivers to QuestCompletions on driver_id to report bonus payouts per city, preserving drivers who did not quest.",
    schemaSnippet: "`GigDrivers (driver_id VARCHAR(32) PRIMARY KEY, driver_name VARCHAR(100), city VARCHAR(32))` & `QuestCompletions (completion_id VARCHAR(32) PRIMARY KEY, driver_id VARCHAR(32), bonus_payout_usd DECIMAL(6,2))`",
    targetQuery: `SELECT d.driver_id, d.driver_name, d.city,\n       COUNT(q.completion_id) AS completed_quests_count,\n       COALESCE(SUM(q.bonus_payout_usd), 0.00) AS total_bonus_earned_usd\nFROM GigDrivers d\nLEFT JOIN QuestCompletions q\n  ON d.driver_id = q.driver_id\nGROUP BY d.driver_id, d.driver_name, d.city\nORDER BY total_bonus_earned_usd DESC;`,
    eli5Story: "Checking which gig drivers completed the 'Deliver 20 meals this weekend for a $100 bonus' challenge and who didn't participate.",
    commonMistakes: "Using an INNER JOIN which hides all drivers who did not complete a bonus quest from the city driver registry.",
    learningOutcomes: "Calculate platform gamification bonus payouts with zero-preservation."
  },
  {
    title: "Marketplace Third-Party Sellers to Verified Copyright DMCA Takedowns",
    ind: "Platforms",
    diff: "Medium",
    table: "MarketplaceSellers",
    scenario: "Maintaining marketplace trust and safety by joining third-party merchants to Digital Millennium Copyright Act (DMCA) infringement notices.",
    businessObjective: "Left join MarketplaceSellers to DmcaNotices on seller_id to flag sellers with zero infringements as trusted clean merchants.",
    schemaSnippet: "`MarketplaceSellers (seller_id VARCHAR(32) PRIMARY KEY, shop_name VARCHAR(64), registered_date DATE)` & `DmcaNotices (notice_id VARCHAR(32) PRIMARY KEY, seller_id VARCHAR(32), is_upheld BOOLEAN)`",
    targetQuery: `SELECT s.seller_id, s.shop_name,\n       COUNT(n.notice_id) AS total_dmca_notices,\n       COALESCE(SUM(CASE WHEN n.is_upheld = TRUE THEN 1 ELSE 0 END), 0) AS confirmed_infringements,\n       CASE\n         WHEN COUNT(n.notice_id) = 0 THEN 'VERIFIED_TRUSTED_SELLER'\n         WHEN SUM(CASE WHEN n.is_upheld = TRUE THEN 1 ELSE 0 END) >= 3 THEN 'ACCOUNT_SUSPENSION_REQUIRED'\n         ELSE 'WATCHLIST'\n       END AS seller_compliance_tier\nFROM MarketplaceSellers s\nLEFT JOIN DmcaNotices n\n  ON s.seller_id = n.seller_id\nGROUP BY s.seller_id, s.shop_name\nORDER BY confirmed_infringements DESC;`,
    eli5Story: "Checking if online merchants received copyright complaints for selling fake goods, awarding trusted status to sellers with zero complaints.",
    commonMistakes: "Dropping clean sellers with zero complaints by mistakenly using an INNER JOIN.",
    learningOutcomes: "Implement online marketplace trust and safety tiering via outer join aggregations."
  },
  {
    title: "Streaming Creator Channels to Brand Sponsorship Payout Withdrawals",
    ind: "Platforms",
    diff: "Hard",
    table: "CreatorChannels",
    scenario: "Auditing creator wallet balances by joining registered video creators to brand sponsorship cashout requests.",
    businessObjective: "Left join CreatorChannels to SponsorshipCashouts on channel_id to compute total payouts, preserving creators who have never cashed out.",
    schemaSnippet: "`CreatorChannels (channel_id VARCHAR(32) PRIMARY KEY, channel_handle VARCHAR(48), subscriber_count INT, lifetime_earnings_usd DECIMAL(12,2))` & `SponsorshipCashouts (cashout_id VARCHAR(32) PRIMARY KEY, channel_id VARCHAR(32), amount_usd DECIMAL(10,2))`",
    targetQuery: `SELECT c.channel_id, c.channel_handle, c.lifetime_earnings_usd,\n       COUNT(s.cashout_id) AS total_cashout_events,\n       COALESCE(SUM(s.amount_usd), 0.00) AS total_withdrawn_usd,\n       (c.lifetime_earnings_usd - COALESCE(SUM(s.amount_usd), 0.00)) AS unwithdrawn_escrow_balance\nFROM CreatorChannels c\nLEFT JOIN SponsorshipCashouts s\n  ON c.channel_id = s.channel_id\nGROUP BY c.channel_id, c.channel_handle, c.lifetime_earnings_usd\nORDER BY unwithdrawn_escrow_balance DESC;`,
    eli5Story: "Calculating how much sponsorship money YouTube and Twitch video makers have earned that is still sitting inside their platform wallet waiting to be withdrawn.",
    commonMistakes: "Subtracting SUM(s.amount_usd) directly without COALESCE, turning unwithdrawn balances into NULL for creators with zero withdrawals.",
    learningOutcomes: "Calculate digital creator escrow balances using outer-joined disbursement totals."
  },
  {
    title: "EV Charging Plugs to Peak Fast-Charging Session Power Draws",
    ind: "Platforms",
    diff: "Medium",
    table: "ChargingPlugs",
    scenario: "Auditing electric vehicle charging network utilization across highway travel plazas by joining charging stalls to session kilowatt draws.",
    businessObjective: "Left join ChargingPlugs to ChargeSessions on plug_id to calculate total kilowatt-hours delivered and identify unused charging stalls.",
    schemaSnippet: "`ChargingPlugs (plug_id VARCHAR(16) PRIMARY KEY, plaza_name VARCHAR(64), max_kw INT, plug_type VARCHAR(16))` & `ChargeSessions (session_id VARCHAR(32) PRIMARY KEY, plug_id VARCHAR(16), kwh_delivered DECIMAL(8,2))`",
    targetQuery: `SELECT p.plaza_name, p.plug_type,\n       COUNT(DISTINCT p.plug_id) AS total_plugs_installed,\n       COUNT(s.session_id) AS total_charging_sessions,\n       COALESCE(ROUND(SUM(s.kwh_delivered), 1), 0.0) AS total_energy_delivered_kwh,\n       COALESCE(ROUND(AVG(s.kwh_delivered), 1), 0.0) AS avg_kwh_per_session\nFROM ChargingPlugs p\nLEFT JOIN ChargeSessions s\n  ON p.plug_id = s.plug_id\nGROUP BY p.plaza_name, p.plug_type\nORDER BY total_energy_delivered_kwh DESC;`,
    eli5Story: "Adding up how much electricity highway EV charging stations delivered to Tesla and Ford cars, keeping unused stalls in the station count.",
    commonMistakes: "Using an INNER JOIN which drops newly installed charging stalls that haven't had their first customer yet.",
    learningOutcomes: "Analyze clean energy infrastructure utilization using outer join summaries."
  }
];
