// =============================================================================
// TRACK 03: AGGREGATIONS & GROUP BY BUCKETING LAB
// =============================================================================

window.AGGREGATIONS_SCHEMA = {
  tableName: 'Employees',
  columns: ['id', 'name', 'department', 'salary', 'bonus', 'hire_year'],
  types: { id: 'INT', name: 'VARCHAR', department: 'VARCHAR', salary: 'INT', bonus: 'INT', hire_year: 'INT' },
  rows: [
    { id: 101, name: 'David Chen', department: 'Engineering', salary: 125000, bonus: 15000, hire_year: 2021 },
    { id: 102, name: 'Samantha Davis', department: 'Engineering', salary: 145000, bonus: 20000, hire_year: 2020 },
    { id: 103, name: 'Lisa White', department: 'Engineering', salary: 105000, bonus: null, hire_year: 2023 },
    { id: 104, name: 'Patrick Wilson', department: 'Sales', salary: 62000, bonus: 25000, hire_year: 2022 },
    { id: 105, name: 'Marcus Vance', department: 'Sales', salary: 80000, bonus: 30000, hire_year: 2021 },
    { id: 106, name: 'Ashley Miller', department: 'Analytics', salary: 115000, bonus: 12000, hire_year: 2022 },
    { id: 107, name: 'Julia Smith', department: 'Analytics', salary: 92000, bonus: null, hire_year: 2023 },
    { id: 108, name: 'Kevin Brown', department: 'Finance', salary: 95000, bonus: 10000, hire_year: 2021 },
    { id: 109, name: 'Rose Taylor', department: 'Finance', salary: 108000, bonus: 14000, hire_year: 2020 }
  ]
};

window.AGGREGATIONS_STEPS = [
  // ---------------------------------------------------------------------------
  // STEP 01: The Big 5 Aggregate Functions
  // ---------------------------------------------------------------------------
  {
    stepIndex: 1,
    id: 'agg_big_5',
    keyword: 'AGGREGATES',
    title: 'Step 01: The Big 5 Aggregate Functions',
    pillClass: 'pill-from',
    conceptHeading: 'Collapsing multiple rows into a single scalar summary',
    conceptText: 'An aggregate function takes multiple values from a column across multiple rows and summarizes them into exactly ONE single mathematical scalar value. ANSI SQL defines 5 universal aggregations: COUNT, SUM, AVG, MIN, and MAX.',
    sqlCode: `SELECT COUNT(*) AS total_staff,\n       SUM(salary) AS total_payroll,\n       AVG(salary) AS avg_salary,\n       MIN(salary) AS lowest_salary,\n       MAX(salary) AS highest_salary\nFROM Employees;`,
    explanationPoints: [
      'COUNT(*) calculates the total number of surviving rows.',
      'SUM(salary) computes the arithmetic sum of all numeric values ($927,000).',
      'AVG(salary) divides the sum by the non-NULL count ($103,000).',
      'MIN(salary) ($62k) and MAX(salary) ($145k) extract boundary values.',
      'Without a GROUP BY clause, these functions collapse the entire table into exactly 1 summary row.'
    ],
    gotcha: 'Never mix raw un-aggregated columns with aggregate functions in the same SELECT unless you use GROUP BY. For example, SELECT name, AVG(salary) FROM Employees will fail in strict ANSI SQL!',
    actionPrompt: 'Below is the single scalar summary row generated by collapsing all 9 records:',
    transform: (rows) => {
      const totalStaff = rows.length;
      const totalPayroll = rows.reduce((acc, r) => acc + r.salary, 0);
      const avgSalary = Math.round(totalPayroll / totalStaff);
      const minSalary = Math.min(...rows.map(r => r.salary));
      const maxSalary = Math.max(...rows.map(r => r.salary));
      return [{
        total_staff: totalStaff,
        total_payroll: `$${totalPayroll.toLocaleString()}`,
        avg_salary: `$${avgSalary.toLocaleString()}`,
        lowest_salary: `$${minSalary.toLocaleString()}`,
        highest_salary: `$${maxSalary.toLocaleString()}`,
        _status: 'passed',
        _label: 'TABLE COLLAPSED (1 ROW)'
      }];
    },
    svg: `
      <svg viewBox="0 0 780 160" width="100%" height="160" xmlns="http://www.w3.org/2000/svg">
        <rect width="780" height="160" fill="#0b0b0e" rx="6" stroke="#232328"/>
        <!-- 9 Input Rows -->
        <g transform="translate(30, 20)">
          <rect width="180" height="120" rx="4" fill="#121216" stroke="#2f333d"/>
          <text x="90" y="20" fill="#a4b7cf" font-family="monospace" font-size="10" font-weight="700" text-anchor="middle">9 INDIVIDUAL ROWS</text>
          <text x="15" y="44" fill="#71717a" font-family="monospace" font-size="9">Row 1: David ($125k)</text>
          <text x="15" y="62" fill="#71717a" font-family="monospace" font-size="9">Row 2: Samantha ($145k)</text>
          <text x="15" y="80" fill="#71717a" font-family="monospace" font-size="9">Row 3: Lisa ($105k)</text>
          <text x="15" y="98" fill="#71717a" font-family="monospace" font-size="9">... (+6 more rows)</text>
        </g>
        <!-- Funnel Converge -->
        <path d="M 220 80 L 320 80" stroke="#9ec5ad" stroke-width="2" stroke-dasharray="4,4"/>
        <g transform="translate(330, 25)">
          <rect width="180" height="110" rx="5" fill="rgba(158, 197, 173, 0.08)" stroke="#9ec5ad" stroke-width="1.5"/>
          <text x="90" y="24" fill="#9ec5ad" font-family="monospace" font-size="10" font-weight="700" text-anchor="middle">AGGREGATE FUNNEL</text>
          <text x="15" y="50" fill="#dfcaa9" font-family="monospace" font-size="9">COUNT(*) &rarr; 9 rows</text>
          <text x="15" y="68" fill="#dfcaa9" font-family="monospace" font-size="9">SUM(salary) &rarr; $927k</text>
          <text x="15" y="86" fill="#dfcaa9" font-family="monospace" font-size="9">AVG(salary) &rarr; $103k</text>
        </g>
        <!-- Output Single Row -->
        <path d="M 520 80 L 590 80" stroke="#9ec5ad" stroke-width="2"/>
        <g transform="translate(600, 35)">
          <rect width="150" height="90" rx="4" fill="#181a20" stroke="#3b4252"/>
          <text x="75" y="22" fill="#9ec5ad" font-family="monospace" font-size="10" font-weight="700" text-anchor="middle">1 OUTPUT ROW</text>
          <text x="15" y="50" fill="#d1d5db" font-family="monospace" font-size="9">Total: 9</text>
          <text x="15" y="68" fill="#d1d5db" font-family="monospace" font-size="9">Avg: $103,000</text>
        </g>
      </svg>
    `
  },

  // ---------------------------------------------------------------------------
  // STEP 02: The Null Trap: COUNT(*) vs COUNT(col)
  // ---------------------------------------------------------------------------
  {
    stepIndex: 2,
    id: 'agg_count_nulls',
    keyword: 'COUNT TRAP',
    title: 'Step 02: The Null Trap: COUNT(*) vs COUNT(column)',
    pillClass: 'pill-where',
    conceptHeading: 'Why COUNT(column) ignores NULLs, while COUNT(*) counts rows',
    conceptText: 'One of the most frequent traps in technical SQL interviews is the difference between COUNT(*) and COUNT(column_name). COUNT(*) counts physical rows regardless of NULL content. COUNT(column) counts ONLY rows where that specific column is NOT NULL. COUNT(DISTINCT column) counts unique non-NULL values.',
    sqlCode: `SELECT COUNT(*) AS total_rows,\n       COUNT(bonus) AS staff_with_bonus,\n       COUNT(DISTINCT department) AS unique_departments\nFROM Employees;`,
    explanationPoints: [
      'COUNT(*) = 9: All 9 physical rows in the table are counted.',
      'COUNT(bonus) = 7: Lisa White and Julia Smith have NULL bonuses, so they are ignored by the counter!',
      'COUNT(DISTINCT department) = 4: Only the 4 unique departments (Engineering, Sales, Analytics, Finance) are counted.',
      'Trap Alert: AVG(bonus) divides by 7, NOT 9! If you want to treat NULL as zero, you must use AVG(COALESCE(bonus, 0)).'
    ],
    gotcha: 'AVG(column) silently skips NULL values! If 2 employees have NULL bonus, AVG(bonus) computes the average among bonus recipients only, skewing executive compensation statistics unless COALESCE is used.',
    actionPrompt: 'Per-row evaluation showing which bonus values are counted vs skipped:',
    transform: (rows) => rows.map(r => {
      const hasBonus = r.bonus !== null;
      return {
        id: r.id,
        name: r.name,
        department: r.department,
        salary: `$${r.salary.toLocaleString()}`,
        bonus: r.bonus !== null ? `$${r.bonus.toLocaleString()}` : 'NULL',
        _status: hasBonus ? 'passed' : 'rejected',
        _label: hasBonus ? 'COUNTED (+1)' : 'SKIPPED (NULL)'
      };
    }),
    svg: `
      <svg viewBox="0 0 780 140" width="100%" height="140" xmlns="http://www.w3.org/2000/svg">
        <rect width="780" height="140" fill="#0b0b0e" rx="6" stroke="#232328"/>
        <g transform="translate(40, 20)">
          <rect width="200" height="100" rx="4" fill="#121216" stroke="#2f333d"/>
          <text x="100" y="24" fill="#a4b7cf" font-family="monospace" font-size="10.5" font-weight="700" text-anchor="middle">COUNT(*)</text>
          <text x="100" y="55" fill="#9ec5ad" font-family="monospace" font-size="14" font-weight="700" text-anchor="middle">= 9 Rows</text>
          <text x="100" y="80" fill="#71717a" font-family="monospace" font-size="8.5" text-anchor="middle">Counts all physical tuples</text>
        </g>
        <g transform="translate(290, 20)">
          <rect width="200" height="100" rx="4" fill="#121216" stroke="#d69d8f"/>
          <text x="100" y="24" fill="#d69d8f" font-family="monospace" font-size="10.5" font-weight="700" text-anchor="middle">COUNT(bonus)</text>
          <text x="100" y="55" fill="#dfcaa9" font-family="monospace" font-size="14" font-weight="700" text-anchor="middle">= 7 Values</text>
          <text x="100" y="80" fill="#d69d8f" font-family="monospace" font-size="8.5" text-anchor="middle">Silently drops 2 NULLs!</text>
        </g>
        <g transform="translate(540, 20)">
          <rect width="200" height="100" rx="4" fill="#121216" stroke="#2f333d"/>
          <text x="100" y="24" fill="#a4b7cf" font-family="monospace" font-size="10.5" font-weight="700" text-anchor="middle">COUNT(DISTINCT dept)</text>
          <text x="100" y="55" fill="#9ec5ad" font-family="monospace" font-size="14" font-weight="700" text-anchor="middle">= 4 Unique</text>
          <text x="100" y="80" fill="#71717a" font-family="monospace" font-size="8.5" text-anchor="middle">Deduplicates department strings</text>
        </g>
      </svg>
    `
  },

  // ---------------------------------------------------------------------------
  // STEP 03: The GROUP BY Bucket Sorter
  // ---------------------------------------------------------------------------
  {
    stepIndex: 3,
    id: 'agg_groupby_buckets',
    keyword: 'GROUP BY',
    title: 'Step 03: The GROUP BY Bucket Sorter',
    pillClass: 'pill-distinct',
    conceptHeading: 'Partitioning rows into discrete aggregation buckets',
    conceptText: 'GROUP BY tells the database engine: "Do not collapse the entire table into a single row. Instead, create a separate summary bucket for each unique value in the grouping column, and run aggregate calculations inside each bucket independently."',
    sqlCode: `SELECT department,\n       COUNT(*) AS headcount,\n       AVG(salary) AS avg_salary,\n       SUM(salary) AS dept_payroll\nFROM Employees\nGROUP BY department;`,
    explanationPoints: [
      'The engine builds an in-memory hash table where keys are unique department values.',
      'As each row is processed, it is routed into its matching department bucket.',
      'Inside each bucket, COUNT, AVG, and SUM accumulate separately.',
      'Surviving output: Exactly 1 row per unique department bucket (4 output rows).'
    ],
    gotcha: 'GROUP BY happens before SELECT! This means you cannot group by a column alias created in SELECT in standard ANSI SQL (though PostgreSQL and MySQL allow it as an extension).',
    actionPrompt: 'Rows partitioned into 4 distinct department buckets with independent aggregates:',
    transform: (rows) => {
      const depts = {};
      rows.forEach(r => {
        if (!depts[r.department]) depts[r.department] = { count: 0, payroll: 0, members: [] };
        depts[r.department].count += 1;
        depts[r.department].payroll += r.salary;
        depts[r.department].members.push(r.name);
      });
      return Object.keys(depts).map(d => ({
        department: d,
        headcount: depts[d].count,
        avg_salary: `$${Math.round(depts[d].payroll / depts[d].count).toLocaleString()}`,
        dept_payroll: `$${depts[d].payroll.toLocaleString()}`,
        _status: 'passed',
        _label: `BUCKET (${depts[d].count} STAFF)`
      }));
    },
    svg: `
      <svg viewBox="0 0 780 150" width="100%" height="150" xmlns="http://www.w3.org/2000/svg">
        <rect width="780" height="150" fill="#0b0b0e" rx="6" stroke="#232328"/>
        <!-- 4 Buckets -->
        <g transform="translate(30, 20)">
          <rect width="160" height="110" rx="4" fill="#121216" stroke="#9ec5ad" stroke-width="1.5"/>
          <text x="80" y="24" fill="#9ec5ad" font-family="monospace" font-size="10" font-weight="700" text-anchor="middle">ENGINEERING</text>
          <text x="15" y="50" fill="#d1d5db" font-family="monospace" font-size="9">Staff: 3</text>
          <text x="15" y="70" fill="#dfcaa9" font-family="monospace" font-size="9">Avg: $125,000</text>
          <text x="15" y="90" fill="#71717a" font-family="monospace" font-size="8.5">Sum: $375,000</text>
        </g>
        <g transform="translate(220, 20)">
          <rect width="160" height="110" rx="4" fill="#121216" stroke="#a4b7cf" stroke-width="1.5"/>
          <text x="80" y="24" fill="#a4b7cf" font-family="monospace" font-size="10" font-weight="700" text-anchor="middle">SALES</text>
          <text x="15" y="50" fill="#d1d5db" font-family="monospace" font-size="9">Staff: 2</text>
          <text x="15" y="70" fill="#dfcaa9" font-family="monospace" font-size="9">Avg: $71,000</text>
          <text x="15" y="90" fill="#71717a" font-family="monospace" font-size="8.5">Sum: $142,000</text>
        </g>
        <g transform="translate(410, 20)">
          <rect width="160" height="110" rx="4" fill="#121216" stroke="#dfcaa9" stroke-width="1.5"/>
          <text x="80" y="24" fill="#dfcaa9" font-family="monospace" font-size="10" font-weight="700" text-anchor="middle">ANALYTICS</text>
          <text x="15" y="50" fill="#d1d5db" font-family="monospace" font-size="9">Staff: 2</text>
          <text x="15" y="70" fill="#dfcaa9" font-family="monospace" font-size="9">Avg: $103,500</text>
          <text x="15" y="90" fill="#71717a" font-family="monospace" font-size="8.5">Sum: $207,000</text>
        </g>
        <g transform="translate(600, 20)">
          <rect width="150" height="110" rx="4" fill="#121216" stroke="#beafcc" stroke-width="1.5"/>
          <text x="75" y="24" fill="#beafcc" font-family="monospace" font-size="10" font-weight="700" text-anchor="middle">FINANCE</text>
          <text x="15" y="50" fill="#d1d5db" font-family="monospace" font-size="9">Staff: 2</text>
          <text x="15" y="70" fill="#dfcaa9" font-family="monospace" font-size="9">Avg: $101,500</text>
          <text x="15" y="90" fill="#71717a" font-family="monospace" font-size="8.5">Sum: $203,000</text>
        </g>
      </svg>
    `
  },

  // ---------------------------------------------------------------------------
  // STEP 04: The Strict Non-Aggregated Column Rule
  // ---------------------------------------------------------------------------
  {
    stepIndex: 4,
    id: 'agg_strict_rule',
    keyword: 'GROUP BY RULE',
    title: 'Step 04: The Strict Non-Aggregated Column Rule',
    pillClass: 'pill-case',
    conceptHeading: 'Why un-aggregated raw columns cause fatal engine errors',
    conceptText: 'The Golden Law of SQL Grouping: Every column listed in the SELECT clause MUST either appear in the GROUP BY clause, OR be enclosed inside an aggregate function (COUNT, SUM, AVG, MIN, MAX).',
    sqlCode: `-- &cross; FATAL ERROR in ANSI SQL:\n-- SELECT department, name, AVG(salary)\n-- FROM Employees\n-- GROUP BY department;\n\n-- &check; VALID ANSI SQL:\nSELECT department,\n       COUNT(name) AS staff_count,\n       AVG(salary) AS avg_salary\nFROM Employees\nGROUP BY department;`,
    explanationPoints: [
      'Why does standard SQL reject raw "name"? Because inside the Engineering bucket, there are 3 names (David, Samantha, Lisa). Which single name should the engine display?',
      'A row cannot hold multiple conflicting scalar values in a single cell.',
      'Therefore, every non-grouping column MUST be aggregated so it resolves to a single value.',
      'Modern production engines (PostgreSQL, BigQuery, Snowflake, MySQL 8+) strictly enforce this rule.'
    ],
    gotcha: 'If you want to view both raw rows AND summary departmental totals in the same result set, you cannot use GROUP BY! You must use Window Functions (OVER PARTITION BY), which we cover in Pillar 4.',
    actionPrompt: 'Comparison showing valid aggregated output vs illegal multi-value column:',
    transform: (rows) => [
      {
        department: 'Engineering',
        staff_count: 3,
        avg_salary: '$125,000',
        engine_verdict: '&check; VALID (3 names aggregated to count)',
        _status: 'passed',
        _label: 'VALID PROJECTION'
      },
      {
        department: 'Sales',
        staff_count: 2,
        avg_salary: '$71,000',
        engine_verdict: '&check; VALID (2 names aggregated to count)',
        _status: 'passed',
        _label: 'VALID PROJECTION'
      },
      {
        department: 'Engineering (Invalid Query)',
        staff_count: 'David, Samantha, Lisa?',
        avg_salary: '$125,000',
        engine_verdict: '&cross; SYNTAX ERROR: Column "name" must appear in GROUP BY',
        _status: 'rejected',
        _label: 'FATAL SYNTAX ERROR'
      }
    ],
    svg: `
      <svg viewBox="0 0 780 140" width="100%" height="140" xmlns="http://www.w3.org/2000/svg">
        <rect width="780" height="140" fill="#0b0b0e" rx="6" stroke="#232328"/>
        <!-- Valid Query Side -->
        <g transform="translate(40, 20)">
          <rect width="320" height="100" rx="4" fill="rgba(158, 197, 173, 0.08)" stroke="#9ec5ad"/>
          <text x="20" y="26" fill="#9ec5ad" font-family="monospace" font-size="10.5" font-weight="700">&check; VALID: GROUP BY department</text>
          <text x="20" y="55" fill="#d1d5db" font-family="monospace" font-size="9.5">SELECT department, COUNT(name), AVG(salary)</text>
          <text x="20" y="80" fill="#71717a" font-family="monospace" font-size="8.5">Every column is in GROUP BY or aggregated &rarr; PASS</text>
        </g>
        <!-- Invalid Query Side -->
        <g transform="translate(410, 20)">
          <rect width="330" height="100" rx="4" fill="rgba(214, 157, 143, 0.08)" stroke="#d69d8f"/>
          <text x="20" y="26" fill="#d69d8f" font-family="monospace" font-size="10.5" font-weight="700">&cross; INVALID: Raw "name" projected</text>
          <text x="20" y="55" fill="#d1d5db" font-family="monospace" font-size="9.5">SELECT department, name, AVG(salary)</text>
          <text x="20" y="80" fill="#d69d8f" font-family="monospace" font-size="8.5">Which name out of 3 should be displayed? &rarr; FAIL</text>
        </g>
      </svg>
    `
  },

  // ---------------------------------------------------------------------------
  // STEP 05: The WHERE vs HAVING Gateway
  // ---------------------------------------------------------------------------
  {
    stepIndex: 5,
    id: 'agg_where_vs_having',
    keyword: 'WHERE vs HAVING',
    title: 'Step 05: The WHERE vs HAVING Gateway',
    pillClass: 'pill-order',
    conceptHeading: 'Pre-aggregation row filtering vs post-aggregation bucket filtering',
    conceptText: 'WHERE and HAVING both filter data, but at completely different moments in the query lifecycle. WHERE filters individual raw rows BEFORE buckets are created. HAVING filters summary buckets AFTER aggregation has computed.',
    sqlCode: `SELECT department,\n       COUNT(*) AS senior_count,\n       AVG(salary) AS avg_senior_salary\nFROM Employees\nWHERE salary >= 100000          -- Gate 1: Filters raw rows (pre-grouping)\nGROUP BY department\nHAVING COUNT(*) >= 2;          -- Gate 2: Filters bucket aggregates (post-grouping)`,
    explanationPoints: [
      'Gate 1 (WHERE salary >= 100,000): Raw rows are scanned. Only employees earning $100k+ survive. Patrick ($62k), Marcus ($80k), Julia ($92k), and Kevin ($95k) are dropped.',
      'Grouping: The remaining 5 employees are partitioned into department buckets.',
      'Gate 2 (HAVING COUNT(*) >= 2): The engine evaluates the summary count per bucket. Engineering has 3 survivors (PASS). Analytics has 1 survivor (DROPPED). Finance has 1 survivor (DROPPED).',
      'Final Output: Only Engineering survives both gates!'
    ],
    gotcha: 'Never use HAVING to filter non-aggregated individual row columns! Writing HAVING salary >= 100000 will cause a syntax error in strict SQL engines. Filter raw rows in WHERE for 10x faster query execution.',
    actionPrompt: 'Step-by-step two-gate execution trace showing survivors vs dropped departments:',
    transform: (rows) => [
      {
        department: 'Engineering',
        raw_candidates: 'David ($125k), Sam ($145k), Lisa ($105k)',
        gate1_where_passed: '3 Rows Passed',
        gate2_having_check: 'COUNT(*) = 3 >= 2 (PASS)',
        _status: 'passed',
        _label: 'SURVIVED BOTH GATES'
      },
      {
        department: 'Analytics',
        raw_candidates: 'Ashley ($115k), Julia ($92k)',
        gate1_where_passed: '1 Row Passed (Ashley)',
        gate2_having_check: 'COUNT(*) = 1 < 2 (DROPPED)',
        _status: 'rejected',
        _label: 'DROPPED BY HAVING'
      },
      {
        department: 'Finance',
        raw_candidates: 'Kevin ($95k), Rose ($108k)',
        gate1_where_passed: '1 Row Passed (Rose)',
        gate2_having_check: 'COUNT(*) = 1 < 2 (DROPPED)',
        _status: 'rejected',
        _label: 'DROPPED BY HAVING'
      },
      {
        department: 'Sales',
        raw_candidates: 'Patrick ($62k), Marcus ($80k)',
        gate1_where_passed: '0 Rows Passed',
        gate2_having_check: 'No bucket formed',
        _status: 'rejected',
        _label: 'DROPPED BY WHERE'
      }
    ],
    svg: `
      <svg viewBox="0 0 780 150" width="100%" height="150" xmlns="http://www.w3.org/2000/svg">
        <rect width="780" height="150" fill="#0b0b0e" rx="6" stroke="#232328"/>
        <!-- Raw Table -->
        <g transform="translate(30, 25)">
          <rect width="140" height="100" rx="4" fill="#121216" stroke="#2f333d"/>
          <text x="70" y="24" fill="#a4b7cf" font-family="monospace" font-size="10" font-weight="700" text-anchor="middle">9 RAW ROWS</text>
          <text x="15" y="55" fill="#71717a" font-family="monospace" font-size="9">All Employees</text>
        </g>
        <!-- Gate 1: WHERE -->
        <path d="M 175 75 L 225 75" stroke="#dfcaa9" stroke-width="2"/>
        <g transform="translate(230, 20)">
          <rect width="160" height="110" rx="4" fill="rgba(223, 202, 169, 0.1)" stroke="#dfcaa9"/>
          <text x="80" y="24" fill="#dfcaa9" font-family="monospace" font-size="10" font-weight="700" text-anchor="middle">GATE 1: WHERE</text>
          <text x="15" y="50" fill="#dfcaa9" font-family="monospace" font-size="8.5">salary >= 100,000</text>
          <text x="15" y="75" fill="#71717a" font-family="monospace" font-size="8.5">Drops 4 raw rows</text>
          <text x="15" y="95" fill="#9ec5ad" font-family="monospace" font-size="8.5">5 rows survive</text>
        </g>
        <!-- Gate 2: GROUP BY + HAVING -->
        <path d="M 395 75 L 445 75" stroke="#9ec5ad" stroke-width="2"/>
        <g transform="translate(450, 20)">
          <rect width="160" height="110" rx="4" fill="rgba(158, 197, 173, 0.1)" stroke="#9ec5ad"/>
          <text x="80" y="24" fill="#9ec5ad" font-family="monospace" font-size="10" font-weight="700" text-anchor="middle">GATE 2: HAVING</text>
          <text x="15" y="50" fill="#9ec5ad" font-family="monospace" font-size="8.5">COUNT(*) >= 2</text>
          <text x="15" y="75" fill="#71717a" font-family="monospace" font-size="8.5">Evaluates buckets</text>
          <text x="15" y="95" fill="#d69d8f" font-family="monospace" font-size="8.5">Drops 2 buckets</text>
        </g>
        <!-- Final Output -->
        <path d="M 615 75 L 655 75" stroke="#9ec5ad" stroke-width="2"/>
        <g transform="translate(660, 35)">
          <rect width="100" height="80" rx="4" fill="#181a20" stroke="#9ec5ad"/>
          <text x="50" y="24" fill="#9ec5ad" font-family="monospace" font-size="9.5" font-weight="700" text-anchor="middle">OUTPUT</text>
          <text x="15" y="50" fill="#d1d5db" font-family="monospace" font-size="8.5">Engineering</text>
          <text x="15" y="68" fill="#71717a" font-family="monospace" font-size="8">(3 Seniors)</text>
        </g>
      </svg>
    `
  },

  // ---------------------------------------------------------------------------
  // STEP 06: Multi-Column Composite Grouping
  // ---------------------------------------------------------------------------
  {
    stepIndex: 6,
    id: 'agg_multi_column',
    keyword: 'MULTI GROUP BY',
    title: 'Step 06: Multi-Column Composite Grouping',
    pillClass: 'pill-limit',
    conceptHeading: 'Grouping by multiple dimensions simultaneously',
    conceptText: 'You can group by multiple columns (e.g. department, hire_year). The database engine forms a bucket for every unique combination of those values.',
    sqlCode: `SELECT department,\n       hire_year,\n       COUNT(*) AS hires_count,\n       AVG(salary) AS avg_salary\nFROM Employees\nGROUP BY department, hire_year\nORDER BY department ASC, hire_year DESC;`,
    explanationPoints: [
      'Each bucket key is a composite tuple: (Engineering, 2021), (Engineering, 2020), (Engineering, 2023), etc.',
      'Rows with the same department but different hire years land in separate buckets.',
      'ORDER BY department ASC, hire_year DESC organizes the resulting multi-dimensional report logically.',
      'This is the exact underlying SQL mechanism powering pivot tables in BI dashboards.'
    ],
    gotcha: 'Adding more columns to GROUP BY increases result granularity (more output rows with smaller bucket counts), moving you closer to raw individual row details.',
    actionPrompt: 'Multi-dimensional breakdown showing department and hiring cohort buckets:',
    transform: (rows) => {
      const composites = {};
      rows.forEach(r => {
        const k = `${r.department}__${r.hire_year}`;
        if (!composites[k]) composites[k] = { dept: r.department, year: r.hire_year, count: 0, payroll: 0 };
        composites[k].count += 1;
        composites[k].payroll += r.salary;
      });
      return Object.values(composites).map(c => ({
        department: c.dept,
        hire_year: c.year,
        hires_count: c.count,
        avg_salary: `$${Math.round(c.payroll / c.count).toLocaleString()}`,
        _status: 'passed',
        _label: `COHORT (${c.count} HIRES)`
      }));
    },
    svg: `
      <svg viewBox="0 0 780 140" width="100%" height="140" xmlns="http://www.w3.org/2000/svg">
        <rect width="780" height="140" fill="#0b0b0e" rx="6" stroke="#232328"/>
        <!-- Composite Key Concept -->
        <g transform="translate(40, 25)">
          <rect width="320" height="90" rx="4" fill="#121216" stroke="#3b4252"/>
          <text x="160" y="24" fill="#a4b7cf" font-family="monospace" font-size="10" font-weight="700" text-anchor="middle">COMPOSITE HASH KEY</text>
          <text x="25" y="52" fill="#dfcaa9" font-family="monospace" font-size="9">hash(department, hire_year)</text>
          <text x="25" y="72" fill="#71717a" font-family="monospace" font-size="8.5">Partitions by department AND cohort year</text>
        </g>
        <path d="M 370 70 L 420 70" stroke="#9ec5ad" stroke-width="2"/>
        <g transform="translate(430, 20)">
          <rect width="310" height="100" rx="4" fill="rgba(158, 197, 173, 0.08)" stroke="#9ec5ad"/>
          <text x="15" y="24" fill="#9ec5ad" font-family="monospace" font-size="9.5" font-weight="700">SUB-BUCKET EXAMPLES:</text>
          <text x="15" y="48" fill="#d1d5db" font-family="monospace" font-size="9">&bull; Engineering &times; 2020: Samantha ($145k)</text>
          <text x="15" y="68" fill="#d1d5db" font-family="monospace" font-size="9">&bull; Engineering &times; 2021: David ($125k)</text>
          <text x="15" y="88" fill="#d1d5db" font-family="monospace" font-size="9">&bull; Engineering &times; 2023: Lisa ($105k)</text>
        </g>
      </svg>
    `
  }
];
