// =============================================================================
// SQL COMPANION BUDDY ENGINE: "BYTE" THE SQL CYBER-BOT 🤖
// Interactive, animated SVG companion with reactive emotions, speech bubbles,
// contextual hints, poke-interactions, and sound FX integration.
// =============================================================================

const SQL_BUDDY = (() => {
  let currentState = 'idle'; // 'idle' | 'happy' | 'thinking' | 'confused' | 'celebrating'
  let bubbleTimeout = null;
  let isMinimized = false;

  // Curated SQL Pro Tips & Wisdom for Poking the Buddy
  const PRO_TIPS = [
    "Psst! Never compare with NULL using '='. Always use 'IS NULL' or 'IS NOT NULL'!",
    "Remember: WHERE filters individual rows BEFORE grouping, HAVING filters summary buckets AFTER!",
    "Row Number gives 1, 2, 3... Rank skips ties like 1, 2, 2, 4... Dense Rank never skips: 1, 2, 2, 3!",
    "Beware the 3VL trap! If your subquery in 'NOT IN' returns even one NULL, the whole query returns 0 rows!",
    "Always default to UNION ALL unless you explicitly need deduplication! UNION incurs a heavy sort/hash memory cost.",
    "Did you know? In standard SQL, aliases created in SELECT cannot be used in WHERE because WHERE runs at Step 2 and SELECT runs at Step 5!",
    "Last_Value() default frame trap: Always specify 'ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING'!",
    "Want to make your queries lightning fast? Avoid wrapping indexed columns in functions like DATE(created_at). Keep it sargable!",
    "In recursive CTEs, always CAST() your anchor string accumulator to prevent overflow on deeper levels!",
    "GROUPING(column) returns 1 if a NULL was generated by ROLLUP/CUBE, and 0 if it's an actual database NULL!"
  ];

  // SVG Face Configurations for Reactive Expressions
  const FACES = {
    idle: `
      <!-- Visor Screen -->
      <rect x="22" y="32" width="56" height="30" rx="8" fill="#0f172a" stroke="#38bdf8" stroke-width="2"/>
      <!-- Glowing Eyes -->
      <ellipse class="buddy-eye left" cx="38" cy="46" rx="5" ry="6" fill="#38bdf8"/>
      <ellipse class="buddy-eye right" cx="62" cy="46" rx="5" ry="6" fill="#38bdf8"/>
      <!-- Soft Smile -->
      <path d="M 44 54 Q 50 58 56 54" stroke="#38bdf8" stroke-width="2.5" fill="none" stroke-linecap="round"/>
    `,
    happy: `
      <rect x="22" y="32" width="56" height="30" rx="8" fill="#0f172a" stroke="#4ade80" stroke-width="2"/>
      <!-- Happy Arch Eyes (^ ^) -->
      <path d="M 33 48 Q 38 42 43 48" stroke="#4ade80" stroke-width="3" fill="none" stroke-linecap="round"/>
      <path d="M 57 48 Q 62 42 67 48" stroke="#4ade80" stroke-width="3" fill="none" stroke-linecap="round"/>
      <!-- Big Smile -->
      <path d="M 43 53 Q 50 60 57 53" stroke="#4ade80" stroke-width="2.5" fill="none" stroke-linecap="round"/>
      <!-- Rosy Cheeks -->
      <circle cx="28" cy="52" r="3" fill="#f43f5e" opacity="0.6"/>
      <circle cx="72" cy="52" r="3" fill="#f43f5e" opacity="0.6"/>
    `,
    celebrating: `
      <rect x="22" y="32" width="56" height="30" rx="8" fill="#0f172a" stroke="#fbbf24" stroke-width="2.5"/>
      <!-- Star Eyes (★ ★) -->
      <text x="38" y="50" font-family="sans-serif" font-size="12" fill="#fbbf24" text-anchor="middle" font-weight="900">★</text>
      <text x="62" y="50" font-family="sans-serif" font-size="12" fill="#fbbf24" text-anchor="middle" font-weight="900">★</text>
      <!-- Cheerful Open Mouth -->
      <path d="M 44 53 Q 50 61 56 53 Z" fill="#fbbf24"/>
    `,
    confused: `
      <rect x="22" y="32" width="56" height="30" rx="8" fill="#0f172a" stroke="#f43f5e" stroke-width="2"/>
      <!-- Asymmetric Puzzled Eyes -->
      <circle cx="37" cy="46" r="6" fill="#f43f5e"/>
      <circle cx="63" cy="46" r="3" fill="#f43f5e"/>
      <!-- Wobbly Mouth -->
      <path d="M 43 56 Q 47 52 51 56 T 57 54" stroke="#f43f5e" stroke-width="2.5" fill="none" stroke-linecap="round"/>
      <!-- Question Mark Bubble -->
      <text x="76" y="30" font-family="monospace" font-size="16" fill="#fbbf24" font-weight="900">?</text>
    `,
    thinking: `
      <rect x="22" y="32" width="56" height="30" rx="8" fill="#0f172a" stroke="#c084fc" stroke-width="2"/>
      <!-- Glancing Upwards Eyes -->
      <ellipse cx="40" cy="42" rx="5" ry="5" fill="#c084fc"/>
      <ellipse cx="64" cy="42" rx="5" ry="5" fill="#c084fc"/>
      <!-- Pensive Flat Mouth -->
      <line x1="45" y1="54" x2="55" y2="54" stroke="#c084fc" stroke-width="2.5" stroke-linecap="round"/>
    `
  };

  // Render the Master SVG Body
  function renderBuddySVG(state) {
    const faceMarkup = FACES[state] || FACES.idle;
    return `
      <svg class="buddy-bot-svg ${state}" viewBox="0 0 100 115" width="100" height="115" xmlns="http://www.w3.org/2000/svg">
        <!-- Floating Shadow -->
        <ellipse class="buddy-shadow" cx="50" cy="110" rx="26" ry="4" fill="rgba(0,0,0,0.3)"/>

        <!-- Main Body Group -->
        <g class="buddy-body-group">
          <!-- Antenna Spark -->
          <line x1="50" y1="18" x2="50" y2="6" stroke="#475569" stroke-width="3" stroke-linecap="round"/>
          <circle class="buddy-antenna-orb" cx="50" cy="5" r="5" fill="#fbbf24" stroke="#000" stroke-width="1.5"/>

          <!-- Robot Head Shell -->
          <rect x="15" y="18" width="70" height="52" rx="16" fill="#1e293b" stroke="#000" stroke-width="3"/>
          <rect x="18" y="21" width="64" height="46" rx="13" fill="#334155"/>

          <!-- Decorative Ear Bolts -->
          <rect x="9" y="36" width="6" height="16" rx="2" fill="#64748b" stroke="#000" stroke-width="2"/>
          <rect x="85" y="36" width="6" height="16" rx="2" fill="#64748b" stroke="#000" stroke-width="2"/>

          <!-- Face & Expression Layer -->
          <g class="buddy-face-layer">
            ${faceMarkup}
          </g>

          <!-- Torso / Base -->
          <path d="M 28 70 L 72 70 L 66 94 L 34 94 Z" fill="#1e293b" stroke="#000" stroke-width="3"/>
          <path d="M 31 73 L 69 73 L 64 91 L 36 91 Z" fill="#334155"/>

          <!-- Mini Chest Heartbeat / SQL Terminal Screen -->
          <rect x="40" y="77" width="20" height="10" rx="3" fill="#0f172a" stroke="#000" stroke-width="1.5"/>
          <text x="50" y="85" font-family="monospace" font-size="6.5" font-weight="900" fill="#38bdf8" text-anchor="middle">SQL</text>

          <!-- Hover Jet Thruster -->
          <ellipse cx="50" cy="95" rx="10" ry="3" fill="#38bdf8" opacity="0.8"/>
          <path class="buddy-thruster-flame" d="M 43 96 Q 50 108 57 96 Z" fill="#38bdf8" opacity="0.7"/>
        </g>
      </svg>
    `;
  }

  // Mount the Buddy Widget into DOM
  function init() {
    let container = document.getElementById('sqlBuddyContainer');
    if (!container) {
      container = document.createElement('div');
      container.id = 'sqlBuddyContainer';
      container.className = 'sql-buddy-container';
      document.body.appendChild(container);
    }

    container.innerHTML = `
      <div id="buddySpeechBubble" class="buddy-speech-bubble" style="display: none;">
        <div class="buddy-bubble-header">
          <span class="buddy-name">🤖 Byte the SQL Bot</span>
          <button class="buddy-close-speech" onclick="SQL_BUDDY.hideSpeech()">&times;</button>
        </div>
        <div id="buddySpeechText" class="buddy-speech-text">Hey there! Ready to write some blazing fast SQL queries?</div>
      </div>

      <div class="buddy-interactive-unit" onclick="SQL_BUDDY.poke()">
        <div id="buddySvgWrapper" class="buddy-svg-wrapper">
          ${renderBuddySVG('idle')}
        </div>
        <button class="buddy-toggle-btn" title="Toggle Buddy Sleep Mode" onclick="event.stopPropagation(); SQL_BUDDY.toggleMinimize();">
          <span id="buddyToggleIcon">💤</span>
        </button>
      </div>
    `;

    // Welcome Greeting after 1.5 seconds
    setTimeout(() => {
      say("👋 Welcome to SQL Mastery! I'm Byte, your companion. Click me anytime for pro-tips!", 6000, 'happy');
    }, 1500);

    // Periodic gentle blinking & tip reminder
    setInterval(() => {
      if (currentState === 'idle' && !isMinimized && Math.random() > 0.65) {
        setExpression('happy');
        setTimeout(() => setExpression('idle'), 1800);
      }
    }, 12000);
  }

  // Change Facial Expression
  function setExpression(state) {
    currentState = state;
    const wrapper = document.getElementById('buddySvgWrapper');
    if (wrapper) {
      wrapper.innerHTML = renderBuddySVG(state);
    }
  }

  // Display speech bubble with message
  function say(message, duration = 5000, expression = 'happy') {
    if (isMinimized) return;
    setExpression(expression);

    const bubble = document.getElementById('buddySpeechBubble');
    const textEl = document.getElementById('buddySpeechText');
    if (!bubble || !textEl) return;

    textEl.innerText = message;
    bubble.style.display = 'block';
    bubble.classList.remove('pop-anim');
    void bubble.offsetWidth; // Trigger reflow for CSS animation
    bubble.classList.add('pop-anim');

    if (bubbleTimeout) clearTimeout(bubbleTimeout);
    if (duration > 0) {
      bubbleTimeout = setTimeout(() => {
        hideSpeech();
        setExpression('idle');
      }, duration);
    }
  }

  function hideSpeech() {
    const bubble = document.getElementById('buddySpeechBubble');
    if (bubble) bubble.style.display = 'none';
  }

  // Poke interaction when user clicks the avatar
  function poke() {
    const randomTip = PRO_TIPS[Math.floor(Math.random() * PRO_TIPS.length)];
    const expressions = ['happy', 'thinking', 'celebrating'];
    const chosenExp = expressions[Math.floor(Math.random() * expressions.length)];
    
    // Play subtle click sound if audio engine exists
    if (window.AUDIO_ENGINE && typeof window.AUDIO_ENGINE.playTone === 'function') {
      window.AUDIO_ENGINE.playTone(587.33, 'sine', 0.15); // D5 note
    }

    say(randomTip, 7000, chosenExp);
  }

  // Reaction Hooks for Platform Events
  function onCorrectAnswer(contextName) {
    const praises = [
      `🎉 BOOM! 100% Correct on ${contextName || 'that question'}! Pure genius!`,
      `⭐ Flawless relational logic! Keep that streak rolling!`,
      `🔥 Outstanding! The database optimizer bows before your query!`,
      `⚡ Verified & Passed! Your SQL skills are leveling up rapidly!`
    ];
    const praise = praises[Math.floor(Math.random() * praises.length)];
    say(praise, 5000, 'celebrating');
  }

  function onIncorrectAnswer(hintText) {
    const msg = hintText ? `🤔 Not quite! Hint: ${hintText}` : `😅 Close one! Review the execution lifecycle order and try again!`;
    say(msg, 6000, 'confused');
  }

  function onQueryRunSuccess(rowCount) {
    say(`🚀 Query executed successfully! Returned ${rowCount} row${rowCount === 1 ? '' : 's'}. Clean execution plan!`, 4500, 'happy');
  }

  function onQueryRunError(errorMsg) {
    const trimmed = (errorMsg || 'Syntax error').substring(0, 65);
    say(`⚠️ Whoops! Engine caught an error: "${trimmed}". Check your aliases and keywords!`, 6000, 'confused');
  }

  function toggleMinimize() {
    isMinimized = !isMinimized;
    const container = document.getElementById('sqlBuddyContainer');
    const icon = document.getElementById('buddyToggleIcon');
    if (container) {
      container.classList.toggle('minimized', isMinimized);
      if (icon) icon.innerText = isMinimized ? '🤖' : '💤';
      if (isMinimized) hideSpeech();
    }
  }

  return {
    init,
    say,
    poke,
    setExpression,
    hideSpeech,
    toggleMinimize,
    onCorrectAnswer,
    onIncorrectAnswer,
    onQueryRunSuccess,
    onQueryRunError
  };
})();

// Auto-initialize when DOM is ready
if (document.readyState === 'loading') {
  document.addEventListener('DOMContentLoaded', SQL_BUDDY.init);
} else {
  SQL_BUDDY.init();
}
