/**
 * SQL MASTERY VISUALIZER - PHYSICAL EXECUTION ORDER TIMELINE (OPTION #2)
 * ----------------------------------------------------------------------
 * Interactive 8-stage relational engine pipeline stepper.
 * Teaches physical storage and relational query processing sequence:
 *   Stage 1: FROM & JOIN (Base Table Memory Ingestion)
 *   Stage 2: WHERE (Row-Level Predicate Evaluation)
 *   Stage 3: GROUP BY (Hash Partition Bucketing)
 *   Stage 4: HAVING (Aggregate Summary Filtering)
 *   Stage 5: SELECT & WINDOW (Projection & Expression Compute)
 *   Stage 6: DISTINCT (Tuple Deduplication)
 *   Stage 7: ORDER BY (Sort Buffer & Spooling)
 *   Stage 8: LIMIT & OFFSET (Output Stream Slicing)
 */

(function(window) {
  'use strict';

  const EXECUTION_STAGES = [
    {
      num: 1,
      key: 'from',
      label: 'FROM / JOIN',
      color: '#38bdf8',
      match: (q) => /\b(FROM|JOIN)\b/i.test(q),
      title: 'Stage 1: FROM & JOIN (Base Table Ingestion)',
      physics: 'The database storage engine locates table files on disk, allocates memory buffer pools, and builds Cartesian/hash join pairs across relational keys.',
      trap: 'Column aliases from SELECT do NOT exist yet. Subqueries in FROM must be aliased.'
    },
    {
      num: 2,
      key: 'where',
      label: 'WHERE',
      color: '#fbbf24',
      match: (q) => /\bWHERE\b/i.test(q),
      title: 'Stage 2: WHERE (Row-Level Predicate Evaluation)',
      physics: 'Scans base table rows from disk before grouping. Discards rows where predicate evaluates to FALSE or NULL (3-Valued Logic).',
      trap: 'Aggregates (COUNT, SUM) and window functions CANNOT be used here because groups have not been formed yet.'
    },
    {
      num: 3,
      key: 'groupby',
      label: 'GROUP BY',
      color: '#ec4899',
      match: (q) => /\bGROUP\s+BY\b/i.test(q),
      title: 'Stage 3: GROUP BY (Hash Partition Bucketing)',
      physics: 'Collapses rows sharing identical key values into aggregate buckets. Non-aggregated individual column values disappear from the working buffer.',
      trap: 'Every column in SELECT must either be listed in GROUP BY or wrapped inside an aggregate function.'
    },
    {
      num: 4,
      key: 'having',
      label: 'HAVING',
      color: '#f43f5e',
      match: (q) => /\bHAVING\b/i.test(q),
      title: 'Stage 4: HAVING (Aggregate Metric Filtering)',
      physics: 'Evaluates predicate conditions against the collapsed aggregate buckets generated by Stage 3 (GROUP BY).',
      trap: 'Do not use HAVING for row-level filters that can run in WHERE—filtering early in WHERE saves massive RAM and CPU.'
    },
    {
      num: 5,
      key: 'select',
      label: 'SELECT',
      color: '#10b981',
      match: (q) => /\bSELECT\b/i.test(q),
      title: 'Stage 5: SELECT & WINDOW (Projection & Expression Compute)',
      physics: 'Computes math expressions, string formatting, column aliases, and window functions (OVER partitions) on preserved rows.',
      trap: 'Aliases declared here CANNOT be referenced in WHERE or HAVING because Step 5 runs AFTER Steps 2, 3, and 4.'
    },
    {
      num: 6,
      key: 'distinct',
      label: 'DISTINCT',
      color: '#06b6d4',
      match: (q) => /\bDISTINCT\b/i.test(q),
      title: 'Stage 6: DISTINCT (Tuple Deduplication)',
      physics: 'Passes projected rows through a hash table or sort-dedup pass to eliminate duplicate rows.',
      trap: 'DISTINCT applies across ALL selected columns simultaneously, not just the column next to it.'
    },
    {
      num: 7,
      key: 'orderby',
      label: 'ORDER BY',
      color: '#a855f7',
      match: (q) => /\bORDER\s+BY\b/i.test(q),
      title: 'Stage 7: ORDER BY (Sorting & Spooling)',
      physics: 'Sorts the final projection set into ascending or descending sequence. Can safely access column aliases created in Stage 5.',
      trap: 'Sorting large unindexed datasets can trigger expensive temp table disk writes (filesort).'
    },
    {
      num: 8,
      key: 'limit',
      label: 'LIMIT',
      color: '#f97316',
      match: (q) => /\b(LIMIT|OFFSET)\b/i.test(q),
      title: 'Stage 8: LIMIT & OFFSET (Output Stream Slicing)',
      physics: 'Halts the result cursor after returning the requested page row count, discarding the remainder.',
      trap: 'LIMIT without an explicit ORDER BY produces non-deterministic, unpredictable row slices.'
    }
  ];

  function getStagesForQuery(query) {
    const q = (query || '').toUpperCase();
    return EXECUTION_STAGES.map(stage => {
      const isPresent = stage.match(q);
      return {
        ...stage,
        active: isPresent
      };
    });
  }

  function renderTimelineHtml(caseId, targetQuery) {
    const stages = getStagesForQuery(targetQuery);

    const nodesHtml = stages.map((s, idx) => {
      const isLast = idx === stages.length - 1;
      return `
        <div class="timeline-stage-node ${s.active ? 'stage-active' : 'stage-bypassed'}" 
             id="stage_node_${caseId}_${s.key}"
             onclick="window.GYM_TIMELINE_ENGINE.toggleStageDetail('${caseId}', ${s.num})"
             title="Stage ${s.num}: ${s.label} (${s.active ? 'Used in this drill' : 'Bypassed'})">
          <div class="stage-num-badge" style="background: ${s.active ? s.color : '#334155'}; color: ${s.active ? '#000000' : '#94a3b8'};">
            ${s.num}
          </div>
          <div class="stage-label-text" style="color: ${s.active ? '#f8fafc' : '#64748b'};">
            ${s.label}
          </div>
        </div>
        ${!isLast ? `<div class="timeline-arrow ${s.active ? 'arrow-active' : 'arrow-dim'}">➔</div>` : ''}
      `;
    }).join('');

    return `
      <div class="gym-timeline-card" id="timeline_card_${caseId}">
        <div class="gym-timeline-header">
          <div class="gym-timeline-title-group">
            <span style="font-size: 13px;">⚡</span>
            <span class="gym-timeline-title">Physical Execution Sequence (Engine Pipeline)</span>
          </div>
          <span class="gym-timeline-hint">Click any stage for physical storage physics</span>
        </div>
        <div class="gym-timeline-track">
          ${nodesHtml}
        </div>
        <div class="gym-stage-callout-drawer" id="stage_callout_${caseId}" style="display: none;"></div>
      </div>
    `;
  }

  function toggleStageDetail(caseId, stageNum) {
    const callout = document.getElementById(`stage_callout_${caseId}`);
    if (!callout) return;

    const stage = EXECUTION_STAGES.find(s => s.num === stageNum);
    if (!stage) return;

    if (callout.getAttribute('data-current-stage') === String(stageNum) && callout.style.display === 'block') {
      callout.style.display = 'none';
      if (window.soundFX) window.soundFX.playClick();
      return;
    }

    callout.setAttribute('data-current-stage', String(stageNum));
    callout.style.display = 'block';
    callout.innerHTML = `
      <div class="stage-callout-box" style="border-left-color: ${stage.color};">
        <div style="display: flex; justify-content: space-between; align-items: flex-start; margin-bottom: 6px;">
          <div style="font-weight: 900; font-size: 12px; color: ${stage.color}; text-transform: uppercase;">
            ${stage.title}
          </div>
          <button class="micro-text-btn" style="color: #94a3b8;" onclick="document.getElementById('stage_callout_${caseId}').style.display='none';">✕</button>
        </div>
        <div style="font-size: 11.5px; color: #e2e8f0; line-height: 1.45; margin-bottom: 6px;">
          ⚙️ <strong>Storage Physics:</strong> ${stage.physics}
        </div>
        <div style="font-size: 11px; color: #fca5a5; line-height: 1.4; background: rgba(239, 68, 68, 0.1); padding: 5px 8px; border-radius: 4px; border: 1px solid rgba(239, 68, 68, 0.3);">
          ⚠️ <strong>Execution Trap:</strong> ${stage.trap}
        </div>
      </div>
    `;

    if (window.soundFX) window.soundFX.playPop();
  }

  function pulseStage(caseId, tokenText) {
    if (!tokenText) return;
    const txt = tokenText.trim().toUpperCase();

    let matchedKey = null;
    if (txt.includes('FROM') || txt.includes('JOIN')) matchedKey = 'from';
    else if (txt.includes('WHERE')) matchedKey = 'where';
    else if (txt.includes('GROUP')) matchedKey = 'groupby';
    else if (txt.includes('HAVING')) matchedKey = 'having';
    else if (txt.includes('SELECT')) matchedKey = 'select';
    else if (txt.includes('DISTINCT')) matchedKey = 'distinct';
    else if (txt.includes('ORDER')) matchedKey = 'orderby';
    else if (txt.includes('LIMIT') || txt.includes('OFFSET')) matchedKey = 'limit';

    if (matchedKey) {
      const node = document.getElementById(`stage_node_${caseId}_${matchedKey}`);
      if (node) {
        node.classList.add('stage-pulsing');
        setTimeout(() => node.classList.remove('stage-pulsing'), 650);
      }
    }
  }

  window.GYM_TIMELINE_ENGINE = {
    renderTimelineHtml: renderTimelineHtml,
    toggleStageDetail: toggleStageDetail,
    pulseStage: pulseStage
  };

})(window);
